// packages/angular-file-preview/src/renderers/lazy.ts
import type { Type } from '@angular/core';

export type LazyRenderer = () => Promise<Type<unknown>>;

export const ImageRenderer: LazyRenderer = () =>
  import('./image/image-renderer.component').then((m) => m.ImageRendererComponent);
export const PdfRenderer: LazyRenderer = () =>
  import('./pdf/pdf-renderer.component').then((m) => m.PdfRendererComponent);
export const DocxRenderer: LazyRenderer = () =>
  import('./docx/docx-renderer.component').then((m) => m.DocxRendererComponent);
export const XlsxRenderer: LazyRenderer = () =>
  import('./xlsx/xlsx-renderer.component').then((m) => m.XlsxRendererComponent);
export const PptxRenderer: LazyRenderer = () =>
  import('./pptx/pptx-renderer.component').then((m) => m.PptxRendererComponent);
export const MsgRenderer: LazyRenderer = () =>
  import('./msg/msg-renderer.component').then((m) => m.MsgRendererComponent);
export const EpubRenderer: LazyRenderer = () =>
  import('./epub/epub-renderer.component').then((m) => m.EpubRendererComponent);
export const MobiRenderer: LazyRenderer = () =>
  import('./mobi/mobi-renderer.component').then((m) => m.MobiRendererComponent);
export const VideoRenderer: LazyRenderer = () =>
  import('./video/video-renderer.component').then((m) => m.VideoRendererComponent);
export const AudioRenderer: LazyRenderer = () =>
  import('./audio/audio-renderer.component').then((m) => m.AudioRendererComponent);
export const MarkdownRenderer: LazyRenderer = () =>
  import('./markdown/markdown-renderer.component').then((m) => m.MarkdownRendererComponent);
export const JsonRenderer: LazyRenderer = () =>
  import('./json/json-renderer.component').then((m) => m.JsonRendererComponent);
export const CsvRenderer: LazyRenderer = () =>
  import('./csv/csv-renderer.component').then((m) => m.CsvRendererComponent);
export const XmlRenderer: LazyRenderer = () =>
  import('./xml/xml-renderer.component').then((m) => m.XmlRendererComponent);
export const SubtitleRenderer: LazyRenderer = () =>
  import('./subtitle/subtitle-renderer.component').then((m) => m.SubtitleRendererComponent);
export const ZipRenderer: LazyRenderer = () =>
  import('./zip/zip-renderer.component').then((m) => m.ZipRendererComponent);
export const TextRenderer: LazyRenderer = () =>
  import('./text/text-renderer.component').then((m) => m.TextRendererComponent);
export const FontRenderer: LazyRenderer = () =>
  import('./font/font-renderer.component').then((m) => m.FontRendererComponent);
export const CadRenderer: LazyRenderer = () =>
  import('./cad/cad-renderer.component').then((m) => m.CadRendererComponent);

// packages/react-file-preview/src/renderers/lazy.tsx
// 集中的 lazy 装饰：把每个 renderer 转为 React.lazy(import).then(default)，
// 让 rollup 自动按 chunk 分割。
// 显式声明 LazyExoticComponent 以避免 TS4023（要求把内部 Props 类型导入到当前文件作用域）。
import { lazy, type LazyExoticComponent, type ComponentType } from 'react';
import type { ImageRenderer as ImageRendererImpl } from './Image';
import type { PdfRenderer as PdfRendererImpl } from './Pdf';
import type { DocxRenderer as DocxRendererImpl } from './Docx';
import type { XlsxRenderer as XlsxRendererImpl } from './Xlsx';
import type { PptxRenderer as PptxRendererImpl } from './Pptx';
import type { MsgRenderer as MsgRendererImpl } from './Msg';
import type { EpubRenderer as EpubRendererImpl } from './Epub';
import type { MobiRenderer as MobiRendererImpl } from './Mobi';
import type { VideoRenderer as VideoRendererImpl } from './Video';
import type { AudioRenderer as AudioRendererImpl } from './Audio';
import type { MarkdownRenderer as MarkdownRendererImpl } from './Markdown';
import type { JsonRenderer as JsonRendererImpl } from './Json';
import type { CsvRenderer as CsvRendererImpl } from './Csv';
import type { XmlRenderer as XmlRendererImpl } from './Xml';
import type { SubtitleRenderer as SubtitleRendererImpl } from './Subtitle';
import type { ZipRenderer as ZipRendererImpl } from './Zip';
import type { TextRenderer as TextRendererImpl } from './Text';
import type { FontRenderer as FontRendererImpl } from './Font';
import type { CadRenderer as CadRendererImpl } from './Cad';

type Lazy<T> = LazyExoticComponent<T extends ComponentType<infer P> ? ComponentType<P> : never>;

export const ImageRenderer: Lazy<typeof ImageRendererImpl> = lazy(() =>
  import('./Image').then((m) => ({ default: m.ImageRenderer })),
);

export const PdfRenderer: Lazy<typeof PdfRendererImpl> = lazy(() =>
  import('./Pdf').then((m) => ({ default: m.PdfRenderer })),
);

export const DocxRenderer: Lazy<typeof DocxRendererImpl> = lazy(() =>
  import('./Docx').then((m) => ({ default: m.DocxRenderer })),
);

export const XlsxRenderer: Lazy<typeof XlsxRendererImpl> = lazy(() =>
  import('./Xlsx').then((m) => ({ default: m.XlsxRenderer })),
);

export const PptxRenderer: Lazy<typeof PptxRendererImpl> = lazy(() =>
  import('./Pptx').then((m) => ({ default: m.PptxRenderer })),
);

export const MsgRenderer: Lazy<typeof MsgRendererImpl> = lazy(() =>
  import('./Msg').then((m) => ({ default: m.MsgRenderer })),
);

export const EpubRenderer: Lazy<typeof EpubRendererImpl> = lazy(() =>
  import('./Epub').then((m) => ({ default: m.EpubRenderer })),
);

export const MobiRenderer: Lazy<typeof MobiRendererImpl> = lazy(() =>
  import('./Mobi').then((m) => ({ default: m.MobiRenderer })),
);

export const VideoRenderer: Lazy<typeof VideoRendererImpl> = lazy(() =>
  import('./Video').then((m) => ({ default: m.VideoRenderer })),
);

export const AudioRenderer: Lazy<typeof AudioRendererImpl> = lazy(() =>
  import('./Audio').then((m) => ({ default: m.AudioRenderer })),
);

export const MarkdownRenderer: Lazy<typeof MarkdownRendererImpl> = lazy(() =>
  import('./Markdown').then((m) => ({ default: m.MarkdownRenderer })),
);

export const JsonRenderer: Lazy<typeof JsonRendererImpl> = lazy(() =>
  import('./Json').then((m) => ({ default: m.JsonRenderer })),
);

export const CsvRenderer: Lazy<typeof CsvRendererImpl> = lazy(() =>
  import('./Csv').then((m) => ({ default: m.CsvRenderer })),
);

export const XmlRenderer: Lazy<typeof XmlRendererImpl> = lazy(() =>
  import('./Xml').then((m) => ({ default: m.XmlRenderer })),
);

export const SubtitleRenderer: Lazy<typeof SubtitleRendererImpl> = lazy(() =>
  import('./Subtitle').then((m) => ({ default: m.SubtitleRenderer })),
);

export const ZipRenderer: Lazy<typeof ZipRendererImpl> = lazy(() =>
  import('./Zip').then((m) => ({ default: m.ZipRenderer })),
);

export const TextRenderer: Lazy<typeof TextRendererImpl> = lazy(() =>
  import('./Text').then((m) => ({ default: m.TextRenderer })),
);

export const FontRenderer: Lazy<typeof FontRendererImpl> = lazy(() =>
  import('./Font').then((m) => ({ default: m.FontRenderer })),
);

export const CadRenderer: Lazy<typeof CadRendererImpl> = lazy(() =>
  import('./Cad').then((m) => ({ default: m.CadRenderer })),
);
