// packages/vue-file-preview/src/FilePreviewEmbed.vue
<script setup lang="ts">
import { toRef } from 'vue';
import type { CSSProperties } from 'vue';
import type { PreviewFile, PreviewFileInput, Locale, Messages, Theme, CustomRendererEventPayload, RequestHandler, RequestInitFactory, ShouldFetchAsBlob } from '@eternalheart/file-preview-core';
import type { CustomRenderer } from './types';
import FilePreviewContent from './FilePreviewContent.vue';
import { useThemeMode } from './composables/useThemeMode';

interface Props {
  files: PreviewFileInput[];
  currentIndex?: number;
  customRenderers?: CustomRenderer[];
  /** 宽度,默认 100% 填充父容器 */
  width?: number | string;
  /** 高度,默认 100% 填充父容器 */
  height?: number | string;
  /** 语言 */
  locale?: Locale;
  /** 自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义 RequestInit（或工厂函数）：注入 Authorization 等鉴权头 */
  requestInit?: RequestInitFactory;
  /** 自定义请求处理器：完全接管库内 fetch */
  requestHandler?: RequestHandler;
  /** 返回 true 时，对应文件先 fetcher→blob URL 后喂给 image/video/audio/pdf 等 renderer */
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  /** 自定义下载回调；不传时库内默认通过 fetcher 拉 Blob 触发下载 */
  onDownload?: (file: PreviewFile) => void | Promise<void>;
  /** 关闭回调 */
  onClose?: () => void;
  /** 是否显示关闭按钮，默认根据 mode 决定（embed: false） */
  showClose?: boolean;
  /** 是否显示下载按钮，默认 true */
  showDownload?: boolean;
  /** 是否显示文件导航箭头，默认 true */
  showNavigation?: boolean;
  /** 是否循环导航文件，默认 false */
  loopNavigation?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  currentIndex: 0,
  customRenderers: () => [],
  width: '100%',
  height: '100%',
  locale: undefined,
  messages: undefined,
  headless: false,
  theme: 'dark',
  requestInit: undefined,
  requestHandler: undefined,
  shouldFetchAsBlob: undefined,
  onDownload: undefined,
  onClose: undefined,
  showClose: undefined,
  showDownload: true,
  showNavigation: true,
  loopNavigation: false,
});

const emit = defineEmits<{
  (e: 'navigate', index: number): void;
  (e: 'custom-event', payload: CustomRendererEventPayload): void;
  (e: 'close'): void;
}>();

const resolvedTheme = useThemeMode(toRef(props, 'theme'));

const wrapperStyle: CSSProperties = {
  width: typeof props.width === 'number' ? `${props.width}px` : props.width,
  height: typeof props.height === 'number' ? `${props.height}px` : props.height,
};
</script>

<template>
  <div class="vfp-root" :style="wrapperStyle" :data-theme="resolvedTheme">
    <div class="vfp-relative vfp-w-full vfp-h-full vfp-overflow-hidden vfp-bg-surface-overlay">
      <FilePreviewContent
        mode="embed"
        :files="files"
        :current-index="currentIndex"
        :custom-renderers="customRenderers"
        :locale="locale"
        :messages="messages"
        :headless="headless"
        :theme="theme"
        :request-init="requestInit"
        :request-handler="requestHandler"
        :should-fetch-as-blob="shouldFetchAsBlob"
        :on-download="onDownload"
        :on-close="onClose"
        :show-close="showClose"
        :show-download="showDownload"
        :show-navigation="showNavigation"
        :loop-navigation="loopNavigation"
        @navigate="(i) => emit('navigate', i)"
        @custom-event="(p) => emit('custom-event', p)"
        @close="() => emit('close')"
      />
    </div>
  </div>
</template>

// packages/angular-file-preview/src/file-preview-embed.ts
import { ChangeDetectionStrategy, Component, computed, effect, input, output } from '@angular/core';
import type {
  CustomRendererEventPayload,
  Locale,
  Messages,
  PreviewFile,
  PreviewFileInput,
  RequestHandler,
  RequestInitFactory,
  ShouldFetchAsBlob,
  Theme,
} from './fp-core';
import type { CustomRenderer } from './types';
import { FilePreviewContent } from './file-preview-content';
import { createSystemDarkSignal, resolveTheme } from './di/theme-mode';

@Component({
  selector: 'FilePreviewEmbed, afp-file-preview-embed',
  standalone: true,
  imports: [FilePreviewContent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'afp-block afp-w-full afp-h-full' },
  template: `
    <div
      class="afp-root"
      [attr.data-theme]="resolvedTheme()"
      [style.width]="widthCss()"
      [style.height]="heightCss()"
    >
      <div class="afp-relative afp-w-full afp-h-full afp-overflow-hidden afp-bg-surface-overlay">
        <FilePreviewContent
          mode="embed"
          [files]="files()"
          [currentIndex]="currentIndex()"
          [customRenderers]="customRenderers()"
          [locale]="locale()"
          [messages]="messages()"
          [headless]="headless()"
          [theme]="theme()"
          [requestInit]="requestInit()"
          [requestHandler]="requestHandler()"
          [shouldFetchAsBlob]="shouldFetchAsBlob()"
          [onDownload]="onDownload()"
          [showClose]="showClose()"
          [showDownload]="showDownload()"
          [showNavigation]="showNavigation()"
          [loopNavigation]="loopNavigation()"
          (close)="close.emit()"
          (navigate)="navigate.emit($event)"
          (customEvent)="customEvent.emit($event)"
        />
      </div>
    </div>
  `,
})
export class FilePreviewEmbed {
  files = input.required<PreviewFileInput[]>();
  currentIndex = input(0);
  customRenderers = input<CustomRenderer[]>([]);
  width = input<number | string>('100%');
  height = input<number | string>('100%');
  locale = input<Locale | undefined>(undefined);
  messages = input<Partial<Record<Locale, Partial<Messages>>> | undefined>(undefined);
  headless = input(false);
  theme = input<Theme>('dark');
  requestInit = input<RequestInitFactory | undefined>(undefined);
  requestHandler = input<RequestHandler | undefined>(undefined);
  shouldFetchAsBlob = input<ShouldFetchAsBlob | undefined>(undefined);
  onDownload = input<((file: PreviewFile) => void | Promise<void>) | undefined>(undefined);
  showClose = input<boolean | undefined>(undefined);
  showDownload = input(true);
  showNavigation = input(true);
  loopNavigation = input(false);

  navigate = output<number>();
  customEvent = output<CustomRendererEventPayload>();
  close = output<void>();

  private readonly system = createSystemDarkSignal();
  readonly resolvedTheme = computed(() => resolveTheme(this.theme(), this.system.systemDark()));
  readonly widthCss = computed(() => {
    const w = this.width();
    return typeof w === 'number' ? `${w}px` : w;
  });
  readonly heightCss = computed(() => {
    const h = this.height();
    return typeof h === 'number' ? `${h}px` : h;
  });

  constructor() {
    effect(() => this.system.bind(this.theme()));
  }
}
