// packages/vue-file-preview/src/FilePreviewContent.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onBeforeUnmount, toRef, provide } from 'vue';
import { X, Download } from 'lucide-vue-next';
import {
  normalizeFiles,
  getFileType,
  downloadFileWithFetcher,
  type PreviewFile,
  type PreviewFileInput,
  type Locale,
  type Messages,
  type Theme,
  type CustomRendererEventPayload,
  type RequestHandler,
  type RequestInitFactory,
  type ShouldFetchAsBlob,
} from '@eternalheart/file-preview-core';
import type { CustomRenderer, CustomRendererContext } from './types';
import { provideLocale, useTranslator } from './composables/useTranslator';
import { provideResolvedTheme } from './composables/useResolvedTheme';
import { provideRequestContext, useResolvedUrl, useFetcher } from './composables/useRequest';
import type { ToolbarGroup, ToolbarButtonItem, ToolbarTextItem } from './renderers/toolbar.types';
import type { RendererHandle } from './renderers/base.types';
import { BUILTIN_RENDERERS } from './renderers/registry';
// Unsupported 体量极小且每次回退都用，直接静态打包到主入口
import UnsupportedRenderer from './renderers/Unsupported/index.vue';
import NavArrows from './components/NavArrows.vue';

const MAX_ZIP_NESTING_DEPTH = 3;

interface Props {
  files: PreviewFileInput[];
  currentIndex: number;
  customRenderers?: CustomRenderer[];
  /** 运行模式: modal(弹窗) 或 embed(嵌入) */
  mode?: 'modal' | 'embed';
  /** ZIP 嵌套深度（内部使用），超过上限时不再递归渲染 ZIP */
  zipNestingDepth?: number;
  /** 语言 */
  locale?: Locale;
  /** 自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头，仅渲染文件内容 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义 RequestInit（或工厂函数）：注入 Authorization 等鉴权头 */
  requestInit?: RequestInitFactory;
  /** 自定义请求处理器：完全接管库内 fetch */
  requestHandler?: RequestHandler;
  /** 返回 true 时，对应文件先 fetcher→blob URL 后喂给 image/video/audio/pdf 等 renderer */
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  /** 自定义下载回调；不传时库内默认通过 fetcher 拉 Blob 触发下载 */
  onDownload?: (file: PreviewFile) => void | Promise<void>;
  /** 关闭回调：传入后工具栏显示关闭按钮 */
  onClose?: () => void;
}

const props = withDefaults(defineProps<Props>(), {
  customRenderers: () => [],
  mode: 'modal',
  zipNestingDepth: 0,
  locale: undefined,
  messages: undefined,
  headless: false,
  theme: 'dark',
  requestInit: undefined,
  requestHandler: undefined,
  shouldFetchAsBlob: undefined,
  onDownload: undefined,
  onClose: undefined,
});

provideRequestContext(() => ({
  requestInit: props.requestInit,
  requestHandler: props.requestHandler,
  shouldFetchAsBlob: props.shouldFetchAsBlob,
}));

const emit = defineEmits<{
  (e: 'navigate', index: number): void;
  (e: 'close'): void;
  (e: 'custom-event', payload: CustomRendererEventPayload): void;
}>();

provideLocale(toRef(props, 'locale'), toRef(props, 'messages'));
const { t } = useTranslator();

const systemDark = ref(
  typeof window !== 'undefined'
    ? window.matchMedia('(prefers-color-scheme: dark)').matches
    : true,
);

let mediaQueryCleanup: (() => void) | null = null;

watch(
  () => props.theme,
  (theme) => {
    if (mediaQueryCleanup) {
      mediaQueryCleanup();
      mediaQueryCleanup = null;
    }
    if (theme === 'auto') {
      const mql = window.matchMedia('(prefers-color-scheme: dark)');
      const handler = (e: MediaQueryListEvent) => { systemDark.value = e.matches; };
      mql.addEventListener('change', handler);
      mediaQueryCleanup = () => mql.removeEventListener('change', handler);
    }
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  if (mediaQueryCleanup) mediaQueryCleanup();
});

const resolvedTheme = computed(() =>
  props.theme === 'auto' ? (systemDark.value ? 'dark' : 'light') : props.theme,
);
provideResolvedTheme(resolvedTheme);

const contentRef = ref<HTMLDivElement | null>(null);
const rootRef = ref<HTMLDivElement | null>(null);

// 渲染器 ref 和工具栏事件订阅
const rendererRef = ref<RendererHandle | null>(null);
const rendererToolbarGroups = ref<ToolbarGroup[]>([]);
let unsubscribeToolbar: (() => void) | null = null;

const cleanupSubscription = () => {
  if (unsubscribeToolbar) {
    unsubscribeToolbar();
    unsubscribeToolbar = null;
  }
};

// 当渲染器变化时，重新订阅工具栏事件
watch(rendererRef, (newRenderer) => {
  cleanupSubscription();
  rendererToolbarGroups.value = [];

  if (!newRenderer) return;

  // 如果渲染器支持事件机制，订阅事件
  if (newRenderer.onToolbarChange) {
    unsubscribeToolbar = newRenderer.onToolbarChange(() => {
      rendererToolbarGroups.value = newRenderer.getToolbarGroups?.() ?? [];
    });
  }

  // 立即获取一次初始工具栏配置
  rendererToolbarGroups.value = newRenderer.getToolbarGroups?.() ?? [];
});

onBeforeUnmount(() => {
  cleanupSubscription();
});

// 标准化文件输入
const normalizedFiles = computed(() => normalizeFiles(props.files));

const currentFile = computed(() => normalizedFiles.value[props.currentIndex]);

// 命中 shouldFetchAsBlob 时，把 file.url 转成 blob: URL 喂给 src 类 renderer
const resolvedUrl = useResolvedUrl(currentFile);

// 自定义渲染器匹配
const customRenderer = computed(() => {
  if (!currentFile.value) return null;
  return props.customRenderers.find((r) => r.test(currentFile.value!)) || null;
});

const customRendererComponent = computed(() => {
  if (!customRenderer.value || !currentFile.value) return null;
  return customRenderer.value.render(currentFile.value, customCtx.value);
});

const fileType = computed(() => (currentFile.value ? getFileType(currentFile.value) : 'unsupported'));

// 从注册表中查找匹配当前 fileType 的内置渲染器
const builtinRenderer = computed(() =>
  BUILTIN_RENDERERS.find((r) => r.fileType === fileType.value) ?? null,
);

// 计算传给内置渲染器的 props
const builtinRendererProps = computed(() => {
  if (!builtinRenderer.value || !currentFile.value) return {};
  return builtinRenderer.value.getProps({
    resolvedUrl: resolvedUrl.value,
    zipNestingDepth: props.zipNestingDepth,
    currentFile: currentFile.value,
  });
});

// 自定义渲染器事件派发器：未绑定 @custom-event 时仍调用 emit（Vue 会安全忽略未声明监听）
const emitCustom = (name: string, payload?: unknown) => {
  if (!currentFile.value) return;
  const ev: CustomRendererEventPayload = { name, payload, file: currentFile.value };
  emit('custom-event', ev);
};

// 自定义渲染器上下文
const customCtx = computed<CustomRendererContext>(() => ({
  emit: emitCustom,
  t: t.value,
  theme: resolvedTheme.value,
  locale: (props.locale ?? 'zh-CN') as Locale,
}));

// 通过 provide 暴露给深层子组件 inject 使用
provide('file-preview:custom-ctx', customCtx);

// 重置状态当文件改变时
watch(
  () => props.currentIndex,
  () => {
    // 重置 epub 状态
    epubCurrent.value = 0;
    epubTotal.value = 0;
    epubFullWidth.value = false;
    // 重置 mobi 状态
    mobiCurrent.value = 0;
    mobiTotal.value = 0;
    mobiFullWidth.value = false;
  }
);

// 图片加载后默认适应窗口（已禁用，改为手动点击"适应窗口"按钮）

// 键盘导航
const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Escape' && props.mode === 'modal') {
    emit('close');
  } else if (e.key === 'ArrowLeft' && props.currentIndex > 0) {
    emit('navigate', props.currentIndex - 1);
  } else if (e.key === 'ArrowRight' && props.currentIndex < normalizedFiles.value.length - 1) {
    emit('navigate', props.currentIndex + 1);
  }
};

onMounted(() => {
  if (props.mode === 'modal') {
    window.addEventListener('keydown', handleKeyDown);
  } else if (rootRef.value) {
    rootRef.value.addEventListener('keydown', handleKeyDown as EventListener);
  }
});

onBeforeUnmount(() => {
  if (props.mode === 'modal') {
    window.removeEventListener('keydown', handleKeyDown);
  } else if (rootRef.value) {
    rootRef.value.removeEventListener('keydown', handleKeyDown as EventListener);
  }
});


const fetcher = useFetcher();
const handleDownload = async () => {
  if (!currentFile.value) return;
  if (props.onDownload) {
    await props.onDownload(currentFile.value);
    return;
  }
  try {
    await downloadFileWithFetcher(currentFile.value.url, currentFile.value.name, fetcher.value);
  } catch (err) {
    console.error('[file-preview] download failed:', err);
  }
};

const showCloseButton = computed(() => !!props.onClose);

const epubCurrent = ref(0);
const epubTotal = ref(0);
const epubFullWidth = ref(false);

const mobiCurrent = ref(0);
const mobiTotal = ref(0);
const mobiFullWidth = ref(false);

// 防止 ESLint 报未使用警告（仍由模板中的事件回调使用）
void epubCurrent; void epubTotal; void epubFullWidth;
void mobiCurrent; void mobiTotal; void mobiFullWidth;

// 工具栏配置 — 各 Renderer 自行通过 ref 暴露 getToolbarGroups 和 onToolbarChange
const toolGroups = computed(() => {
  if (customRenderer.value) {
    return (
      customRenderer.value.getToolbarGroups?.(currentFile.value!, customCtx.value) ?? []
    );
  }
  // 所有内置渲染器都通过事件驱动机制提供工具栏
  return rendererToolbarGroups.value;
});

// 操作组：下载、关闭（通用，不属于任何 Renderer）
const actionGroups = computed<ToolbarGroup[]>(() => {
  const groups: ToolbarGroup[] = [
    {
      items: [
        { type: 'button', icon: Download, tooltip: t.value('common.download'), action: handleDownload },
      ],
    },
  ];
  if (showCloseButton.value) {
    groups.push({
      items: [
        { type: 'button', icon: X, tooltip: t.value('common.close'), action: () => emit('close') },
      ],
    });
  }
  return groups;
});

const hasToolGroups = computed(() => toolGroups.value.length > 0);
</script>

<template>
  <div
    ref="rootRef"
    :tabindex="mode === 'embed' ? 0 : -1"
    :data-theme="resolvedTheme"
    class="vfp-relative vfp-w-full vfp-h-full vfp-flex vfp-flex-col vfp-overflow-hidden vfp-outline-none"
  >
    <!-- 顶部工具栏 -->
    <div
      v-if="!headless"
      class="vfp-flex-shrink-0 vfp-z-10 vfp-backdrop-blur-md vfp-border-b vfp-bg-surface-toolbar vfp-border-line"
      style="padding-top: env(safe-area-inset-top, 0px)"
    >
      <!-- 第一行: 文件名 + 桌面端工具按钮 -->
      <div class="vfp-flex vfp-items-center vfp-justify-between vfp-px-3 md:vfp-px-5 vfp-py-1.5 md:vfp-py-2.5">
        <!-- 左侧: 文件名 + 分页 -->
        <div class="vfp-flex vfp-items-center vfp-flex-1 vfp-min-w-0 vfp-mr-2 md:vfp-mr-3">
          <h2 class="vfp-font-medium vfp-text-xs md:vfp-text-sm vfp-truncate vfp-text-fg-primary">
            {{ currentFile?.name }}
          </h2>
          <span class="vfp-text-xs vfp-ml-2 vfp-flex-shrink-0 vfp-text-fg-muted">
            {{ currentIndex + 1 }}/{{ normalizedFiles.length }}
          </span>
        </div>

        <!-- 移动端: 仅下载 + 关闭 -->
        <div class="vfp-flex vfp-items-center vfp-gap-1 md:vfp-hidden vfp-flex-shrink-0">
          <template v-for="(group, gi) in actionGroups" :key="'m-action-' + gi">
            <template v-for="(item, ii) in group.items" :key="'m-action-' + gi + '-' + ii">
              <button
                v-if="item.type === 'button'"
                class="toolbar-btn"
                :data-tooltip="(item as ToolbarButtonItem).tooltip"
                :disabled="(item as ToolbarButtonItem).disabled"
                @click="(item as ToolbarButtonItem).action"
              >
                <component :is="(item as ToolbarButtonItem).icon" class="vfp-w-4 vfp-h-4" />
              </button>
            </template>
          </template>
        </div>

        <!-- 桌面端: 完整工具按钮 -->
        <div class="vfp-hidden md:vfp-flex vfp-items-center vfp-gap-1 vfp-flex-shrink-0">
          <template v-for="(group, gi) in toolGroups" :key="'d-tool-' + gi">
            <template v-for="(item, ii) in group.items" :key="'d-tool-' + gi + '-' + ii">
              <button
                v-if="item.type === 'button'"
                class="toolbar-btn"
                :data-tooltip="(item as ToolbarButtonItem).tooltip"
                :disabled="(item as ToolbarButtonItem).disabled"
                @click="(item as ToolbarButtonItem).action"
              >
                <component :is="(item as ToolbarButtonItem).icon" class="vfp-w-4 vfp-h-4" />
              </button>
              <span
                v-else-if="item.type === 'text'"
                class="vfp-text-xs vfp-text-center vfp-font-medium vfp-tabular-nums vfp-text-fg-tertiary"
                :style="{ minWidth: (item as ToolbarTextItem).minWidth || 'auto' }"
              >
                {{ (item as ToolbarTextItem).content }}
              </span>
            </template>
            <div class="vfp-w-px vfp-h-4 vfp-mx-1 vfp-bg-divide" />
          </template>
          <template v-for="(group, gi) in actionGroups" :key="'d-action-' + gi">
            <template v-for="(item, ii) in group.items" :key="'d-action-' + gi + '-' + ii">
              <button
                v-if="item.type === 'button'"
                class="toolbar-btn"
                :data-tooltip="(item as ToolbarButtonItem).tooltip"
                :disabled="(item as ToolbarButtonItem).disabled"
                @click="(item as ToolbarButtonItem).action"
              >
                <component :is="(item as ToolbarButtonItem).icon" class="vfp-w-4 vfp-h-4" />
              </button>
            </template>
          </template>
        </div>
      </div>

      <!-- 移动端第二行工具按钮 -->
      <div
        v-if="hasToolGroups"
        class="vfp-flex vfp-items-center vfp-gap-1 vfp-px-3 vfp-pb-1.5 vfp-overflow-x-auto scrollbar-hide md:vfp-hidden"
      >
        <template v-for="(group, gi) in toolGroups" :key="'m-tool-' + gi">
          <div v-if="gi > 0" class="vfp-w-px vfp-h-4 vfp-mx-0.5 vfp-bg-divide" />
          <template v-for="(item, ii) in group.items" :key="'m-tool-' + gi + '-' + ii">
            <button
              v-if="item.type === 'button'"
              class="toolbar-btn"
              :data-tooltip="(item as ToolbarButtonItem).tooltip"
              :disabled="(item as ToolbarButtonItem).disabled"
              @click="(item as ToolbarButtonItem).action"
            >
              <component :is="(item as ToolbarButtonItem).icon" class="vfp-w-4 vfp-h-4" />
            </button>
            <span
              v-else-if="item.type === 'text'"
              class="vfp-text-xs vfp-text-center vfp-font-medium vfp-tabular-nums vfp-text-fg-tertiary"
              :style="{ minWidth: (item as ToolbarTextItem).minWidth || 'auto' }"
            >
              {{ (item as ToolbarTextItem).content }}
            </span>
          </template>
        </template>
      </div>
    </div>

    <!-- 内容区域 -->
    <div
      ref="contentRef"
      class="vfp-flex-1 vfp-flex vfp-items-center vfp-justify-center vfp-overflow-auto"
      :key="currentFile?.url"
    >
      <template v-if="currentFile">
        <component :is="customRendererComponent" v-if="customRendererComponent" :file="currentFile" :ctx="customCtx" />
        <template v-else>
          <!-- ZIP 嵌套深度超限：fallback 到 Unsupported -->
          <UnsupportedRenderer
            v-if="fileType === 'zip' && props.zipNestingDepth >= MAX_ZIP_NESTING_DEPTH"
            :file-name="currentFile.name"
            :file-type="currentFile.type"
            @download="handleDownload"
          />
          <!-- 从注册表查找匹配的渲染器 -->
          <component
            v-else-if="builtinRenderer"
            :is="builtinRenderer.component"
            ref="rendererRef"
            v-bind="builtinRendererProps"
          />
          <!-- 未匹配：fallback 到 UnsupportedRenderer -->
          <UnsupportedRenderer
            v-else
            :file-name="currentFile.name"
            :file-type="currentFile.type"
            @download="handleDownload"
          />
        </template>
      </template>
    </div>

    <!-- 左右导航箭头：state 隔离在 NavArrows 内部,避免 mousemove/timer 引起整树 patch -->
    <NavArrows
      v-if="!headless && normalizedFiles.length > 1"
      :container-ref="contentRef"
      :has-prev="currentIndex > 0"
      :has-next="currentIndex < normalizedFiles.length - 1"
      :reset-key="currentIndex"
      @prev="emit('navigate', currentIndex - 1)"
      @next="emit('navigate', currentIndex + 1)"
    />
  </div>
</template>

<style scoped>
.toolbar-btn {
  position: relative;
  padding: 0.5rem;
  border-radius: 0.375rem;
  transition: all 0.15s;
  user-select: none;
  color: var(--fp-fg-primary);
  background: transparent;
  border: 0;
  cursor: pointer;
}
@media (min-width: 768px) {
  .toolbar-btn {
    padding: 0.375rem;
  }
}
.toolbar-btn:hover {
  background: var(--fp-surface-2);
}
.toolbar-btn:active {
  background: var(--fp-surface-3);
}
.toolbar-btn:disabled {
  color: var(--fp-fg-disabled);
  cursor: not-allowed;
}
/* Tooltip */
.toolbar-btn[data-tooltip]::after {
  content: attr(data-tooltip);
  position: absolute;
  left: 50%;
  top: 100%;
  transform: translateX(-50%);
  margin-top: 6px;
  padding: 4px 8px;
  background: var(--fp-fg-primary);
  color: var(--fp-fg-inverse);
  font-size: 12px;
  line-height: 1.5;
  border-radius: 4px;
  white-space: nowrap;
  pointer-events: none;
  opacity: 0;
  visibility: hidden;
  transition: opacity 0.2s, visibility 0.2s;
  z-index: 50;
}
.toolbar-btn[data-tooltip]::before {
  content: '';
  position: absolute;
  left: 50%;
  top: 100%;
  transform: translateX(-50%);
  margin-top: 2px;
  border: 4px solid transparent;
  border-bottom-color: var(--fp-fg-primary);
  pointer-events: none;
  opacity: 0;
  visibility: hidden;
  transition: opacity 0.2s, visibility 0.2s;
  z-index: 50;
}
.toolbar-btn[data-tooltip]:hover::after,
.toolbar-btn[data-tooltip]:hover::before {
  opacity: 1;
  visibility: visible;
}

/* 移动端隐藏 tooltip */
@media (max-width: 1023px) {
  .toolbar-btn[data-tooltip]::after,
  .toolbar-btn[data-tooltip]::before {
    display: none !important;
  }
}
</style>

// packages/angular-file-preview/src/file-preview-content.component.ts
import {
  afterEveryRender,
  Component,
  computed,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { NgComponentOutlet } from '@angular/common';
import { LucideAngularModule, X, Download } from 'lucide-angular';
import {
  downloadFileWithFetcher,
  fetchAsBlobUrl,
  getFileType,
  normalizeFiles,
  resolveShowClose,
  type CustomRendererEventPayload,
  type Locale,
  type Messages,
  type PreviewFile,
  type PreviewFileInput,
  type RequestHandler,
  type RequestInitFactory,
  type ShouldFetchAsBlob,
  type Theme,
} from '@eternalheart/file-preview-core';
import type { CustomRenderer, CustomRendererContext } from './types';
import { AFP_LOCALE, AFP_REQUEST, AFP_THEME } from './inject/tokens';
import { AfpLocaleStore, AfpRequestStore, AfpThemeStore } from './inject/stores';
import type { ToolbarButtonItem, ToolbarGroup, ToolbarTextItem } from './renderers/toolbar.types';
import type { RendererHandle } from './renderers/base.types';
import { BUILTIN_RENDERERS } from './renderers/registry';
import { UnsupportedRendererComponent } from './renderers/unsupported/unsupported-renderer.component';
import { RendererLoadingComponent } from './renderers/renderer-loading.component';
import { NavArrowsComponent } from './components/nav-arrows.component';

const MAX_ZIP_NESTING_DEPTH = 3;

@Component({
  selector: 'afp-file-preview-content',
  standalone: true,
  imports: [
    NgComponentOutlet,
    LucideAngularModule,
    UnsupportedRendererComponent,
    RendererLoadingComponent,
    NavArrowsComponent,
  ],
  providers: [
    AfpLocaleStore,
    AfpThemeStore,
    AfpRequestStore,
    {
      provide: AFP_LOCALE,
      useFactory: (s: AfpLocaleStore) => ({ locale: s.locale.asReadonly(), t: s.t }),
      deps: [AfpLocaleStore],
    },
    { provide: AFP_THEME, useFactory: (s: AfpThemeStore) => s.theme.asReadonly(), deps: [AfpThemeStore] },
    { provide: AFP_REQUEST, useFactory: (s: AfpRequestStore) => s.value, deps: [AfpRequestStore] },
  ],
  template: `
    <div
      #rootRef
      [attr.tabindex]="mode() === 'embed' ? 0 : -1"
      [attr.data-theme]="resolvedTheme()"
      class="afp-relative afp-w-full afp-h-full afp-flex afp-flex-col afp-overflow-hidden afp-outline-none"
    >
      @if (!headless()) {
        <div
          class="afp-flex-shrink-0 afp-z-10 afp-backdrop-blur-md afp-border-b afp-bg-surface-toolbar afp-border-line"
          style="padding-top: env(safe-area-inset-top, 0px)"
        >
          <div class="afp-flex afp-items-center afp-justify-between afp-px-3 md:afp-px-5 afp-py-1.5 md:afp-py-2.5">
            <div class="afp-flex afp-items-center afp-flex-1 afp-min-w-0 afp-mr-2 md:afp-mr-3">
              <h2 class="afp-font-medium afp-text-xs md:afp-text-sm afp-truncate afp-text-fg-primary">
                {{ currentFile()?.name }}
              </h2>
              <span class="afp-text-xs afp-ml-2 afp-flex-shrink-0 afp-text-fg-muted">
                {{ currentIndex() + 1 }}/{{ normalizedFiles().length }}
              </span>
            </div>

            <div class="afp-flex afp-items-center afp-gap-1 md:afp-hidden afp-flex-shrink-0">
              @for (group of actionGroups(); track $index; let gi = $index) {
                @for (item of group.items; track $index; let ii = $index) {
                  @if (isButton(item)) {
                    <button
                      type="button"
                      class="toolbar-btn"
                      [class.active]="item.active"
                      [attr.data-tooltip]="item.tooltip"
                      [disabled]="item.disabled"
                      [attr.aria-pressed]="item.active"
                      (click)="item.action()"
                    >
                      <lucide-icon [img]="$any(item.icon)" class="afp-w-4 afp-h-4" />
                    </button>
                  }
                }
              }
            </div>

            <div class="afp-hidden md:afp-flex afp-items-center afp-gap-1 afp-flex-shrink-0">
              @for (group of toolGroups(); track $index; let gi = $index) {
                @for (item of group.items; track $index) {
                  @if (isButton(item)) {
                    <button
                      type="button"
                      class="toolbar-btn"
                      [class.active]="item.active"
                      [attr.data-tooltip]="item.tooltip"
                      [disabled]="item.disabled"
                      [attr.aria-pressed]="item.active"
                      (click)="item.action()"
                    >
                      <lucide-icon [img]="$any(item.icon)" class="afp-w-4 afp-h-4" />
                    </button>
                  } @else if (isText(item)) {
                    <span
                      class="afp-text-xs afp-text-center afp-font-medium afp-tabular-nums afp-text-fg-tertiary"
                      [style.minWidth]="item.minWidth || 'auto'"
                    >
                      {{ item.content }}
                    </span>
                  }
                }
                @if (gi < toolGroups().length - 1 || actionGroups().length > 0) {
                  <div class="afp-w-px afp-h-4 afp-mx-1 afp-bg-divide"></div>
                }
              }
              @for (group of actionGroups(); track $index) {
                @for (item of group.items; track $index) {
                  @if (isButton(item)) {
                    <button
                      type="button"
                      class="toolbar-btn"
                      [class.active]="item.active"
                      [attr.data-tooltip]="item.tooltip"
                      [disabled]="item.disabled"
                      [attr.aria-pressed]="item.active"
                      (click)="item.action()"
                    >
                      <lucide-icon [img]="$any(item.icon)" class="afp-w-4 afp-h-4" />
                    </button>
                  }
                }
              }
            </div>
          </div>

          @if (hasToolGroups()) {
            <div class="afp-flex afp-items-center afp-gap-1 afp-px-3 afp-pb-1.5 afp-overflow-x-auto scrollbar-hide md:afp-hidden">
              @for (group of toolGroups(); track $index; let gi = $index) {
                @if (gi > 0) {
                  <div class="afp-w-px afp-h-4 afp-mx-0.5 afp-bg-divide"></div>
                }
                @for (item of group.items; track $index) {
                  @if (isButton(item)) {
                    <button
                      type="button"
                      class="toolbar-btn"
                      [class.active]="item.active"
                      [attr.data-tooltip]="item.tooltip"
                      [disabled]="item.disabled"
                      [attr.aria-pressed]="item.active"
                      (click)="item.action()"
                    >
                      <lucide-icon [img]="$any(item.icon)" class="afp-w-4 afp-h-4" />
                    </button>
                  } @else if (isText(item)) {
                    <span
                      class="afp-text-xs afp-text-center afp-font-medium afp-tabular-nums afp-text-fg-tertiary"
                      [style.minWidth]="item.minWidth || 'auto'"
                    >
                      {{ item.content }}
                    </span>
                  }
                }
              }
            </div>
          }
        </div>
      }

      <div
        #contentRef
        class="afp-flex-1 afp-flex afp-items-center afp-justify-center afp-overflow-auto"
      >
        @if (currentFile(); as file) {
          @if (customRendererCmp(); as cmp) {
            <ng-container *ngComponentOutlet="cmp; inputs: customInputs()" />
          } @else if (fileType() === 'zip' && zipNestingDepth() >= maxZipDepth) {
            <afp-unsupported-renderer
              [fileName]="file.name"
              [fileType]="file.type"
              (download)="handleDownload()"
            />
          } @else if (loadedRenderer(); as cmp) {
            <ng-container *ngComponentOutlet="cmp; inputs: builtinInputs()" />
          } @else if (loadingRenderer()) {
            <afp-renderer-loading />
          } @else {
            <afp-unsupported-renderer
              [fileName]="file.name"
              [fileType]="file.type"
              (download)="handleDownload()"
            />
          }
        }
      </div>

      @if (!headless() && normalizedFiles().length > 1) {
        <afp-nav-arrows
          [containerEl]="contentEl()"
          [hasPrev]="currentIndex() > 0"
          [hasNext]="currentIndex() < normalizedFiles().length - 1"
          [resetKey]="currentIndex()"
          (prev)="navigate.emit(currentIndex() - 1)"
          (next)="navigate.emit(currentIndex() + 1)"
        />
      }
    </div>
  `,
  styles: [`
    .toolbar-btn {
      position: relative;
      padding: 0.5rem;
      border-radius: 0.375rem;
      transition: all 0.15s;
      user-select: none;
      color: var(--fp-fg-primary);
      background: transparent;
      border: 0;
      cursor: pointer;
    }
    @media (min-width: 768px) {
      .toolbar-btn { padding: 0.375rem; }
    }
    .toolbar-btn:hover { background: var(--fp-surface-2); }
    .toolbar-btn:active { background: var(--fp-surface-3); }
    .toolbar-btn.active,
    .toolbar-btn.active:hover,
    .toolbar-btn.active:active { background: var(--fp-surface-3); }
    .toolbar-btn:disabled {
      color: var(--fp-fg-disabled);
      cursor: not-allowed;
    }
    .toolbar-btn[data-tooltip]::after {
      content: attr(data-tooltip);
      position: absolute;
      left: 50%;
      top: 100%;
      transform: translateX(-50%);
      margin-top: 6px;
      padding: 4px 8px;
      background: var(--fp-fg-primary);
      color: var(--fp-fg-inverse);
      font-size: 12px;
      line-height: 1.5;
      border-radius: 4px;
      white-space: nowrap;
      pointer-events: none;
      opacity: 0;
      visibility: hidden;
      transition: opacity 0.2s, visibility 0.2s;
      z-index: 50;
    }
    .toolbar-btn[data-tooltip]::before {
      content: '';
      position: absolute;
      left: 50%;
      top: 100%;
      transform: translateX(-50%);
      margin-top: 2px;
      border: 4px solid transparent;
      border-bottom-color: var(--fp-fg-primary);
      pointer-events: none;
      opacity: 0;
      visibility: hidden;
      transition: opacity 0.2s, visibility 0.2s;
      z-index: 50;
    }
    .toolbar-btn[data-tooltip]:hover::after,
    .toolbar-btn[data-tooltip]:hover::before {
      opacity: 1;
      visibility: visible;
    }
    @media (max-width: 1023px) {
      .toolbar-btn[data-tooltip]::after,
      .toolbar-btn[data-tooltip]::before {
        display: none !important;
      }
    }
  `],
})
export class FilePreviewContentComponent {
  readonly files = input.required<PreviewFileInput[]>();
  readonly currentIndex = input.required<number>();
  readonly customRenderers = input<CustomRenderer[]>([]);
  readonly mode = input<'modal' | 'embed'>('modal');
  readonly zipNestingDepth = input(0);
  readonly locale = input<Locale>();
  readonly messages = input<Partial<Record<Locale, Partial<Messages>>>>();
  readonly headless = input(false);
  readonly theme = input<Theme>('dark');
  readonly requestInit = input<RequestInitFactory>();
  readonly requestHandler = input<RequestHandler>();
  readonly shouldFetchAsBlob = input<ShouldFetchAsBlob>();
  readonly onDownload = input<(file: PreviewFile) => void | Promise<void>>();
  readonly onClose = input<() => void>();
  readonly showClose = input<boolean>();
  readonly showDownload = input(true);

  readonly navigate = output<number>();
  readonly close = output<void>();
  readonly customEvent = output<CustomRendererEventPayload>();

  readonly maxZipDepth = MAX_ZIP_NESTING_DEPTH;
  readonly downloadIcon = Download;
  readonly closeIcon = X;

  private readonly localeStore = inject(AfpLocaleStore);
  private readonly themeStore = inject(AfpThemeStore);
  private readonly requestStore = inject(AfpRequestStore);
  private readonly destroyRef = inject(DestroyRef);
  private readonly host = inject(ElementRef<HTMLElement>);

  readonly rootRef = viewChild<ElementRef<HTMLDivElement>>('rootRef');
  readonly contentRef = viewChild<ElementRef<HTMLDivElement>>('contentRef');
  readonly outlet = viewChild(NgComponentOutlet);

  readonly systemDark = signal(
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-color-scheme: dark)').matches
      : true,
  );

  readonly resolvedTheme = computed(() =>
    this.theme() === 'auto' ? (this.systemDark() ? 'dark' : 'light') : this.theme(),
  );

  readonly normalizedFiles = computed(() => normalizeFiles(this.files()));
  readonly currentFile = computed(() => this.normalizedFiles()[this.currentIndex()]);
  readonly fileType = computed(() => {
    const file = this.currentFile();
    return file ? getFileType(file) : 'unsupported';
  });

  readonly blobUrl = signal('');
  readonly resolvedUrl = computed(() => {
    const file = this.currentFile();
    if (!file) return '';
    const need = !!this.requestStore.value().shouldFetchAsBlob?.(file);
    if (!need) return file.url;
    return this.blobUrl();
  });

  readonly customRenderer = computed(() => {
    const file = this.currentFile();
    if (!file) return null;
    return this.customRenderers().find((r) => r.test(file)) || null;
  });

  readonly customCtx = computed<CustomRendererContext>(() => ({
    emit: (name, payload) => this.emitCustom(name, payload),
    t: this.localeStore.t(),
    theme: this.resolvedTheme(),
    locale: (this.locale() ?? 'zh-CN') as Locale,
  }));

  readonly customRendererCmp = computed(() => {
    const renderer = this.customRenderer();
    const file = this.currentFile();
    if (!renderer || !file) return null;
    return renderer.render(file, this.customCtx());
  });

  readonly customInputs = computed(() => ({
    file: this.currentFile(),
    ctx: this.customCtx(),
  }));

  readonly builtinRenderer = computed(() =>
    BUILTIN_RENDERERS.find((r) => r.fileType === this.fileType()) ?? null,
  );

  readonly loadedRenderer = signal<ReturnType<typeof Object> | null>(null);
  readonly loadingRenderer = signal(false);
  readonly builtinInputs = signal<Record<string, unknown>>({});

  readonly rendererToolbarGroups = signal<ToolbarGroup[]>([]);

  readonly toolGroups = computed(() => {
    const custom = this.customRenderer();
    const file = this.currentFile();
    if (custom && file) {
      return custom.getToolbarGroups?.(file, this.customCtx()) ?? [];
    }
    return this.rendererToolbarGroups();
  });

  readonly showCloseButton = computed(() => resolveShowClose(this.mode(), this.showClose()));

  readonly actionGroups = computed<ToolbarGroup[]>(() => {
    const groups: ToolbarGroup[] = [];
    if (this.showDownload()) {
      groups.push({
        items: [
          { type: 'button', icon: Download, tooltip: this.localeStore.t()('common.download'), action: () => void this.handleDownload() },
        ],
      });
    }
    if (this.showCloseButton()) {
      groups.push({
        items: [
          { type: 'button', icon: X, tooltip: this.localeStore.t()('common.close'), action: () => this.emitClose() },
        ],
      });
    }
    return groups;
  });

  readonly hasToolGroups = computed(() => this.toolGroups().length > 0);
  readonly contentEl = computed(() => this.contentRef()?.nativeElement ?? null);

  private unsubscribeToolbar: (() => void) | null = null;
  private lastRendererInstance: RendererHandle | null = null;
  private createdBlobUrl: string | null = null;
  private blobGen = 0;

  constructor() {
    effect(() => {
      this.localeStore.locale.set(this.locale() ?? 'zh-CN');
      this.localeStore.messages.set(this.messages());
    });

    effect(() => {
      this.themeStore.theme.set(this.resolvedTheme());
    });

    effect(() => {
      this.requestStore.requestInit.set(this.requestInit());
      this.requestStore.requestHandler.set(this.requestHandler());
      this.requestStore.shouldFetchAsBlob.set(this.shouldFetchAsBlob());
    });

    effect(() => {
      const theme = this.theme();
      if (typeof window === 'undefined') return;
      if (theme !== 'auto') return;
      const mql = window.matchMedia('(prefers-color-scheme: dark)');
      const handler = (e: MediaQueryListEvent) => this.systemDark.set(e.matches);
      mql.addEventListener('change', handler);
      this.systemDark.set(mql.matches);
      return () => mql.removeEventListener('change', handler);
    });

    effect(() => {
      const file = this.currentFile();
      const ctx = this.requestStore.value();
      const need = !!(file && ctx.shouldFetchAsBlob?.(file));
      const gen = ++this.blobGen;
      if (this.createdBlobUrl) {
        URL.revokeObjectURL(this.createdBlobUrl);
        this.createdBlobUrl = null;
      }
      this.blobUrl.set('');
      if (!file || !need) return;
      void fetchAsBlobUrl(file.url, ctx.fetcher).then((url) => {
        if (gen !== this.blobGen) {
          URL.revokeObjectURL(url);
          return;
        }
        this.createdBlobUrl = url;
        this.blobUrl.set(url);
      }).catch((err) => {
        if (gen === this.blobGen) {
          console.error('[file-preview] resolve blob url failed:', err);
          this.blobUrl.set(file.url);
        }
      });
    });

    effect(() => {
      const builtin = this.builtinRenderer();
      const file = this.currentFile();
      const url = this.resolvedUrl();
      if (!builtin || !file) {
        this.loadedRenderer.set(null);
        this.loadingRenderer.set(false);
        this.builtinInputs.set({});
        return;
      }
      this.builtinInputs.set(builtin.getProps({
        resolvedUrl: url,
        zipNestingDepth: this.zipNestingDepth(),
        currentFile: file,
      }));
      this.loadingRenderer.set(true);
      this.loadedRenderer.set(null);
      void builtin.load().then((cmp) => {
        if (this.builtinRenderer() === builtin) {
          this.loadedRenderer.set(cmp);
          this.loadingRenderer.set(false);
        }
      }).catch((err) => {
        console.error('[file-preview] load renderer failed:', err);
        if (this.builtinRenderer() === builtin) {
          this.loadedRenderer.set(null);
          this.loadingRenderer.set(false);
        }
      });
    });

    afterEveryRender(() => {
      const instance = this.outlet()?.componentInstance as RendererHandle | undefined;
      if (instance !== this.lastRendererInstance) {
        this.attachRenderer(instance ?? null);
      }
    });

    const onKey = (e: KeyboardEvent) => this.handleKeyDown(e);
    const mode = this.mode();
    if (typeof window !== 'undefined' && mode === 'modal') {
      window.addEventListener('keydown', onKey);
      this.destroyRef.onDestroy(() => window.removeEventListener('keydown', onKey));
    } else {
      const el = this.host.nativeElement;
      el.addEventListener('keydown', onKey);
      this.destroyRef.onDestroy(() => el.removeEventListener('keydown', onKey));
    }

    this.destroyRef.onDestroy(() => {
      this.cleanupSubscription();
      if (this.createdBlobUrl) URL.revokeObjectURL(this.createdBlobUrl);
    });
  }

  isButton(item: ToolbarGroup['items'][number]): item is ToolbarButtonItem {
    return item.type === 'button';
  }

  isText(item: ToolbarGroup['items'][number]): item is ToolbarTextItem {
    return item.type === 'text';
  }

  async handleDownload() {
    const file = this.currentFile();
    if (!file) return;
    const custom = this.onDownload();
    if (custom) {
      await custom(file);
      return;
    }
    try {
      await downloadFileWithFetcher(file.url, file.name, this.requestStore.value().fetcher);
    } catch (err) {
      console.error('[file-preview] download failed:', err);
    }
  }

  emitClose() {
    this.onClose()?.();
    this.close.emit();
  }

  private emitCustom(name: string, payload?: unknown) {
    const file = this.currentFile();
    if (!file) return;
    this.customEvent.emit({ name, payload, file });
  }

  private handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape' && this.mode() === 'modal') {
      this.emitClose();
    } else if (e.key === 'ArrowLeft' && this.currentIndex() > 0) {
      this.navigate.emit(this.currentIndex() - 1);
    } else if (e.key === 'ArrowRight' && this.currentIndex() < this.normalizedFiles().length - 1) {
      this.navigate.emit(this.currentIndex() + 1);
    }
  }

  private cleanupSubscription() {
    if (this.unsubscribeToolbar) {
      this.unsubscribeToolbar();
      this.unsubscribeToolbar = null;
    }
  }

  private attachRenderer(instance: RendererHandle | null) {
    this.cleanupSubscription();
    this.lastRendererInstance = instance;
    this.rendererToolbarGroups.set([]);
    if (!instance) return;
    if (instance.onToolbarChange) {
      this.unsubscribeToolbar = instance.onToolbarChange(() => {
        this.rendererToolbarGroups.set(instance.getToolbarGroups?.() ?? []);
      });
    }
    this.rendererToolbarGroups.set(instance.getToolbarGroups?.() ?? []);
  }
}
