// packages/angular-file-preview/src/file-preview-modal.component.ts
import {
  Component,
  computed,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  input,
  output,
  signal,
} from '@angular/core';
import type {
  CustomRendererEventPayload,
  Locale,
  Messages,
  PreviewFile,
  PreviewFileInput,
  RequestHandler,
  RequestInitFactory,
  ShouldFetchAsBlob,
  Theme,
} from '@eternalheart/file-preview-core';
import type { CustomRenderer } from './types';
import { FilePreviewContentComponent } from './file-preview-content.component';
import { createScrollLock } from './inject/scroll-lock';

@Component({
  selector: 'afp-file-preview-modal',
  standalone: true,
  imports: [FilePreviewContentComponent],
  host: {
    style: 'display: contents',
  },
  template: `
    @if (isOpen()) {
      <div class="afp-root" [attr.data-theme]="resolvedTheme()">
        <div
          class="afp-fixed afp-inset-0 afp-z-[9999] afp-flex afp-items-center afp-justify-center afp-backdrop-blur-md afp-overflow-hidden afp-bg-surface-overlay afp-fade-enter-active"
          (click)="close.emit()"
          (wheel)="$event.stopPropagation()"
        >
          <div class="afp-relative afp-w-full afp-h-full" (click)="$event.stopPropagation()">
            <afp-file-preview-content
              mode="modal"
              [files]="files()"
              [currentIndex]="currentIndex()"
              [customRenderers]="customRenderers()"
              [locale]="locale()"
              [messages]="messages()"
              [headless]="headless()"
              [theme]="theme()"
              [requestInit]="requestInit()"
              [requestHandler]="requestHandler()"
              [shouldFetchAsBlob]="shouldFetchAsBlob()"
              [onDownload]="onDownload()"
              [showClose]="showClose()"
              [showDownload]="showDownload()"
              (close)="close.emit()"
              (navigate)="navigate.emit($event)"
              (customEvent)="customEvent.emit($event)"
            />
          </div>
        </div>
      </div>
    }
  `,
})
export class FilePreviewModalComponent {
  readonly files = input.required<PreviewFileInput[]>();
  readonly currentIndex = input.required<number>();
  readonly isOpen = input.required<boolean>();
  readonly customRenderers = input<CustomRenderer[]>([]);
  readonly locale = input<Locale>();
  readonly messages = input<Partial<Record<Locale, Partial<Messages>>>>();
  readonly headless = input(false);
  readonly theme = input<Theme>('dark');
  readonly requestInit = input<RequestInitFactory>();
  readonly requestHandler = input<RequestHandler>();
  readonly shouldFetchAsBlob = input<ShouldFetchAsBlob>();
  readonly onDownload = input<(file: PreviewFile) => void | Promise<void>>();
  readonly showClose = input<boolean>();
  readonly showDownload = input(true);

  readonly close = output<void>();
  readonly navigate = output<number>();
  readonly customEvent = output<CustomRendererEventPayload>();

  readonly systemDark = signal(
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-color-scheme: dark)').matches
      : true,
  );

  readonly resolvedTheme = computed(() =>
    this.theme() === 'auto' ? (this.systemDark() ? 'dark' : 'light') : this.theme(),
  );

  private readonly host = inject(ElementRef<HTMLElement>);
  private readonly scroll = createScrollLock();

  constructor() {
    const destroyRef = inject(DestroyRef);
    if (typeof document !== 'undefined') {
      document.body.appendChild(this.host.nativeElement);
      destroyRef.onDestroy(() => {
        this.scroll.unlock();
        this.host.nativeElement.remove();
      });
    }

    effect(() => {
      const theme = this.theme();
      if (typeof window === 'undefined' || theme !== 'auto') return;
      const mql = window.matchMedia('(prefers-color-scheme: dark)');
      const handler = (e: MediaQueryListEvent) => this.systemDark.set(e.matches);
      mql.addEventListener('change', handler);
      this.systemDark.set(mql.matches);
      return () => mql.removeEventListener('change', handler);
    });

    effect(() => {
      if (this.isOpen()) this.scroll.lock();
      else this.scroll.unlock();
    });
  }
}

// packages/vue-file-preview/src/FilePreviewModal.vue
<script setup lang="ts">
import { watch, ref, onBeforeUnmount, computed } from 'vue';
import type { PreviewFile, PreviewFileInput, Locale, Messages, Theme, CustomRendererEventPayload, RequestHandler, RequestInitFactory, ShouldFetchAsBlob } from '@eternalheart/file-preview-core';
import type { CustomRenderer } from './types';
import FilePreviewContent from './FilePreviewContent.vue';
import { useScrollLock } from './composables/useScrollLock';

interface Props {
  files: PreviewFileInput[];
  currentIndex: number;
  isOpen: boolean;
  customRenderers?: CustomRenderer[];
  /** 语言 */
  locale?: Locale;
  /** 自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义 RequestInit（或工厂函数）：注入 Authorization 等鉴权头 */
  requestInit?: RequestInitFactory;
  /** 自定义请求处理器：完全接管库内 fetch */
  requestHandler?: RequestHandler;
  /** 返回 true 时，对应文件先 fetcher→blob URL 后喂给 image/video/audio/pdf 等 renderer */
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  /** 自定义下载回调；不传时库内默认通过 fetcher 拉 Blob 触发下载 */
  onDownload?: (file: PreviewFile) => void | Promise<void>;
  /** 是否显示下载按钮，默认 true */
  showDownload?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  customRenderers: () => [],
  locale: undefined,
  messages: undefined,
  headless: false,
  theme: 'dark',
  requestInit: undefined,
  requestHandler: undefined,
  shouldFetchAsBlob: undefined,
  onDownload: undefined,
  showDownload: true,
});

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'navigate', index: number): void;
  (e: 'custom-event', payload: CustomRendererEventPayload): void;
}>();

const { lock, unlock } = useScrollLock(() => props.isOpen);

watch(
  () => props.isOpen,
  (open) => {
    if (open) lock();
    else unlock();
  }
);

const systemDark = ref(
  typeof window !== 'undefined'
    ? window.matchMedia('(prefers-color-scheme: dark)').matches
    : true,
);

let mediaQueryCleanup: (() => void) | null = null;

watch(
  () => props.theme,
  (theme) => {
    if (mediaQueryCleanup) {
      mediaQueryCleanup();
      mediaQueryCleanup = null;
    }
    if (theme === 'auto') {
      const mql = window.matchMedia('(prefers-color-scheme: dark)');
      const handler = (e: MediaQueryListEvent) => { systemDark.value = e.matches; };
      mql.addEventListener('change', handler);
      mediaQueryCleanup = () => mql.removeEventListener('change', handler);
    }
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  if (mediaQueryCleanup) mediaQueryCleanup();
});

const resolvedTheme = computed(() =>
  props.theme === 'auto' ? (systemDark.value ? 'dark' : 'light') : props.theme,
);

const handleBackdropClick = () => emit('close');
const handleContentClick = (e: MouseEvent) => e.stopPropagation();
const handleWheel = (e: WheelEvent) => e.stopPropagation();
</script>

<template>
  <Teleport to="body">
    <Transition name="vfp-fade">
      <div v-if="isOpen" class="vfp-root" :data-theme="resolvedTheme">
        <div
          class="vfp-fixed vfp-inset-0 vfp-z-[9999] vfp-flex vfp-items-center vfp-justify-center vfp-backdrop-blur-md vfp-overflow-hidden vfp-bg-surface-overlay"
          @click="handleBackdropClick"
          @wheel="handleWheel"
        >
          <div class="vfp-relative vfp-w-full vfp-h-full" @click="handleContentClick">
            <FilePreviewContent
              mode="modal"
              :files="files"
              :current-index="currentIndex"
              :custom-renderers="customRenderers"
              :locale="locale"
              :messages="messages"
              :headless="headless"
              :theme="theme"
              :request-init="requestInit"
              :request-handler="requestHandler"
              :should-fetch-as-blob="shouldFetchAsBlob"
              :on-download="onDownload"
              :on-close="() => emit('close')"
              :show-download="showDownload"
              @close="emit('close')"
              @navigate="(i) => emit('navigate', i)"
              @custom-event="(p) => emit('custom-event', p)"
            />
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>
