// packages/react-file-preview/src/FilePreviewContent.tsx
import React, { useState, useEffect, useCallback, useMemo, useRef, Suspense } from 'react';
import { motion } from 'framer-motion';
import { X, Download, ChevronLeft, ChevronRight } from 'lucide-react';
import { getFileType, createTranslator, type Locale, type Messages, type Translator, type Theme } from '@eternalheart/file-preview-core';
import { LocaleProvider } from './i18n/LocaleContext';
import { ThemeProvider } from './ThemeContext';
import type { ToolbarGroup } from './renderers/toolbar.types';
import { getImageToolbarGroups } from './renderers/Image/toolbar';
import { getPdfToolbarGroups } from './renderers/Pdf/toolbar';
import { getEpubToolbarGroups } from './renderers/Epub/toolbar';
import { getMobiToolbarGroups } from './renderers/Mobi/toolbar';
import { getZipToolbarGroups, type ZipToolbarStats } from './renderers/Zip/toolbar';
import { getTextToolbarGroups } from './renderers/Text/toolbar';
import { getMarkdownToolbarGroups } from './renderers/Markdown/toolbar';

import { PreviewFileInput, CustomRenderer, CustomRendererContext } from './types';
import type { CustomRendererEventPayload, PreviewFile, RequestHandler, RequestInitFactory, ShouldFetchAsBlob } from '@eternalheart/file-preview-core';
import { downloadFileWithFetcher } from '@eternalheart/file-preview-core';
import { normalizeFiles } from './utils/fileNormalizer';
import { RequestProvider, useResolvedUrl, useFetcher } from './RequestContext';
// Renderer 通过 React.lazy 动态加载，运行时按需下载对应 chunk
import {
  ImageRenderer,
  PdfRenderer,
  DocxRenderer,
  XlsxRenderer,
  PptxRenderer,
  MsgRenderer,
  EpubRenderer,
  MobiRenderer,
  VideoRenderer,
  AudioRenderer,
  MarkdownRenderer,
  JsonRenderer,
  CsvRenderer,
  XmlRenderer,
  SubtitleRenderer,
  ZipRenderer,
  TextRenderer,
  FontRenderer,
} from './renderers/lazy';
import type { EpubRendererHandle } from './renderers/Epub';
import type { MobiRendererHandle } from './renderers/Mobi';
// 不支持类型回退；体积极小，仍静态打包到主入口
import { UnsupportedRenderer } from './renderers/Unsupported';
import { RendererLoading } from './renderers/RendererLoading';

const MAX_ZIP_NESTING_DEPTH = 3;

export interface FilePreviewContentProps {
  files: PreviewFileInput[];
  currentIndex: number;
  onNavigate?: (index: number) => void;
  customRenderers?: CustomRenderer[];
  /** 运行模式:modal(弹窗) 或 embed(嵌入) */
  mode?: 'modal' | 'embed';
  /** 关闭回调,仅 modal 模式使用 */
  onClose?: () => void;
  /** ZIP 嵌套深度（内部使用），超过上限时不再递归渲染 ZIP */
  zipNestingDepth?: number;
  /** 国际化语言，默认 'zh-CN' */
  locale?: Locale;
  /** 用户自定义翻译字典，浅合并到内置字典之上 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头，仅渲染文件内容 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义渲染器派发的事件出口，载荷为 `{ name, payload, file }` */
  onCustomEvent?: (event: CustomRendererEventPayload) => void;
  /** 自定义 RequestInit（或工厂函数）：用于注入 Authorization 等鉴权头 */
  requestInit?: RequestInitFactory;
  /** 自定义请求处理器：完全接管库内 fetch；与 requestInit 同时存在时 handler 接收已合并的 init */
  requestHandler?: RequestHandler;
  /** 返回 true 时，对应文件会先经 fetcher 拉成 blob: URL 再喂给 image/video/audio/pdf 等 renderer */
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  /**
   * 自定义下载回调。提供后完全接管下载行为；
   * 不提供时，库内默认通过 fetcher 拉成 Blob 触发下载（鉴权 URL 场景自动可用）。
   */
  onDownload?: (file: PreviewFile) => void | Promise<void>;
}

export const FilePreviewContent: React.FC<FilePreviewContentProps> = (props) => {
  const { requestInit, requestHandler, shouldFetchAsBlob } = props;
  return (
    <RequestProvider
      requestInit={requestInit}
      requestHandler={requestHandler}
      shouldFetchAsBlob={shouldFetchAsBlob}
    >
      <FilePreviewContentInner {...props} />
    </RequestProvider>
  );
};

const FilePreviewContentInner: React.FC<FilePreviewContentProps> = ({
  files,
  currentIndex,
  onNavigate,
  customRenderers = [],
  mode = 'modal',
  onClose,
  zipNestingDepth = 0,
  locale = 'zh-CN',
  messages: userMessages,
  headless = false,
  theme = 'dark',
  onCustomEvent,
  onDownload,
  // 以下三项已由外层 RequestProvider 消费，Inner 内不再直接使用
  requestInit: _requestInit,
  requestHandler: _requestHandler,
  shouldFetchAsBlob: _shouldFetchAsBlob,
}) => {
  const t: Translator = useMemo(
    () => createTranslator({ locale, messages: userMessages }),
    [locale, userMessages],
  );

  const [systemDark, setSystemDark] = useState(() =>
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-color-scheme: dark)').matches
      : true,
  );

  useEffect(() => {
    if (theme !== 'auto') return;
    const mql = window.matchMedia('(prefers-color-scheme: dark)');
    const handler = (e: MediaQueryListEvent) => setSystemDark(e.matches);
    mql.addEventListener('change', handler);
    return () => mql.removeEventListener('change', handler);
  }, [theme]);

  const resolvedTheme = theme === 'auto' ? (systemDark ? 'dark' : 'light') : theme;

  const [zoom, setZoom] = useState(1);
  const [rotation, setRotation] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  const [, setTotalPages] = useState(1);
  const [contentNaturalWidth, setContentNaturalWidth] = useState(0);
  const [contentNaturalHeight, setContentNaturalHeight] = useState(0);
  const [imageResetKey, setImageResetKey] = useState(0);
  const contentRef = useRef<HTMLDivElement>(null);
  const rootRef = useRef<HTMLDivElement>(null);
  const epubRef = useRef<EpubRendererHandle>(null);
  const [epubCurrent, setEpubCurrent] = useState(0);
  const [epubTotal, setEpubTotal] = useState(0);
  const [epubFullWidth, setEpubFullWidth] = useState(false);
  const mobiRef = useRef<MobiRendererHandle>(null);
  const [mobiCurrent, setMobiCurrent] = useState(0);
  const [mobiTotal, setMobiTotal] = useState(0);
  const [mobiFullWidth, setMobiFullWidth] = useState(false);
  const [zipStats, setZipStats] = useState<ZipToolbarStats | null>(null);
  const [textWordWrap, setTextWordWrap] = useState(true);
  const [textHtmlPreview, setTextHtmlPreview] = useState(false);
  const [markdownViewMode, setMarkdownViewMode] = useState<'preview' | 'source'>('preview');

  // 标准化文件输入
  const normalizedFiles = useMemo(() => normalizeFiles(files), [files]);

  const currentFile = normalizedFiles[currentIndex];

  // 命中 shouldFetchAsBlob 时，把 file.url 转成 blob: URL 喂给 src 类 renderer
  const resolvedUrl = useResolvedUrl(currentFile);

  // 检查是否有自定义渲染器匹配当前文件
  const customRenderer = useMemo(() => {
    if (!currentFile) return null;
    return customRenderers.find(renderer => renderer.test(currentFile));
  }, [currentFile, customRenderers]);

  const fileType = currentFile ? getFileType(currentFile) : 'unsupported';

  // 自定义渲染器事件派发器：未绑定 onCustomEvent 时静默忽略
  const emitCustom = useCallback(
    (name: string, payload?: unknown) => {
      if (!currentFile) return;
      onCustomEvent?.({ name, payload, file: currentFile });
    },
    [currentFile, onCustomEvent],
  );

  // 自定义渲染器上下文：注入给 render / getToolbarGroups
  const customCtx = useMemo<CustomRendererContext>(
    () => ({
      emit: emitCustom,
      t,
      theme: resolvedTheme,
      locale,
    }),
    [emitCustom, t, resolvedTheme, locale],
  );

  // 重置状态当文件改变时
  useEffect(() => {
    setZoom(1);
    setRotation(0);
    setCurrentPage(1);
    setTotalPages(1);
    setContentNaturalWidth(0);
    setContentNaturalHeight(0);
    setImageResetKey(0);
    // 重置 epub 状态
    setEpubCurrent(0);
    setEpubTotal(0);
    setEpubFullWidth(false);
    // 重置 mobi 状态
    setMobiCurrent(0);
    setMobiTotal(0);
    setMobiFullWidth(false);
    // 重置 zip 状态
    setZipStats(null);
    // 重置 text 状态
    setTextWordWrap(true);
    setTextHtmlPreview(false);
    // 重置 markdown 状态
    setMarkdownViewMode('preview');
  }, [currentIndex]);

  // 图片加载后默认适应窗口
  useEffect(() => {
    if (fileType === 'image' && contentNaturalWidth > 0 && contentNaturalHeight > 0 && contentRef.current) {
      const containerWidth = contentRef.current.clientWidth;
      const containerHeight = contentRef.current.clientHeight;
      const scaleX = containerWidth / contentNaturalWidth;
      const scaleY = containerHeight / contentNaturalHeight;
      const newZoom = Math.min(scaleX, scaleY);
      setZoom(Math.max(0.01, Math.min(10, newZoom)));
    }
  }, [fileType, contentNaturalWidth, contentNaturalHeight]);

  // 键盘导航
  // - modal 模式:全局监听(window)
  // - embed 模式:只在根容器 focus 时监听,避免影响外部页面交互
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && mode === 'modal') {
        onClose?.();
      } else if (e.key === 'ArrowLeft' && currentIndex > 0) {
        onNavigate?.(currentIndex - 1);
      } else if (e.key === 'ArrowRight' && currentIndex < normalizedFiles.length - 1) {
        onNavigate?.(currentIndex + 1);
      }
    };

    if (mode === 'modal') {
      window.addEventListener('keydown', handleKeyDown);
      return () => window.removeEventListener('keydown', handleKeyDown);
    } else {
      const el = rootRef.current;
      if (!el) return;
      el.addEventListener('keydown', handleKeyDown as EventListener);
      return () => el.removeEventListener('keydown', handleKeyDown as EventListener);
    }
  }, [mode, currentIndex, normalizedFiles.length, onClose, onNavigate]);

  const handleZoomIn = useCallback(() => {
    setZoom((prev) => Math.min(prev + 0.1, 10));
  }, []);

  const handleZoomOut = useCallback(() => {
    setZoom((prev) => Math.max(prev - 0.1, 0.01));
  }, []);

  const handleRotate = useCallback(() => {
    setRotation((prev) => prev + 90);
  }, []);

  const handleRotateLeft = useCallback(() => {
    setRotation((prev) => prev - 90);
  }, []);

  const handleFitToWidth = useCallback(() => {
    if (contentRef.current && contentNaturalWidth > 0 && contentNaturalHeight > 0) {
      const containerWidth = contentRef.current.clientWidth;
      const containerHeight = contentRef.current.clientHeight;
      const scaleX = containerWidth / contentNaturalWidth;
      const scaleY = containerHeight / contentNaturalHeight;
      const newZoom = Math.min(scaleX, scaleY);
      setZoom(Math.max(0.01, Math.min(10, newZoom)));
    } else {
      setZoom(1);
    }
    setRotation(0);
    setImageResetKey(k => k + 1);
  }, [contentNaturalWidth, contentNaturalHeight]);

  const handleOriginalSize = useCallback(() => {
    setZoom(1);
    setRotation(0);
    setImageResetKey(k => k + 1);
  }, []);

  const handleZoomChange = useCallback((newZoom: number) => {
    setZoom(newZoom);
  }, []);

  const handleReset = useCallback(() => {
    setZoom(1);
    setRotation(0);
    setImageResetKey(k => k + 1);
  }, []);

  const fetcher = useFetcher();
  const handleDownload = useCallback(async () => {
    if (!currentFile) return;
    if (onDownload) {
      await onDownload(currentFile);
      return;
    }
    try {
      await downloadFileWithFetcher(currentFile.url, currentFile.name, fetcher);
    } catch (err) {
      console.error('[file-preview] download failed:', err);
    }
  }, [currentFile, onDownload, fetcher]);

  const handleEpubChapterChange = useCallback((current: number, total: number) => {
    setEpubCurrent(current);
    setEpubTotal(total);
  }, []);

  const handleMobiChapterChange = useCallback((current: number, total: number) => {
    setMobiCurrent(current);
    setMobiTotal(total);
  }, []);

  const handleZipStatsChange = useCallback((stats: ZipToolbarStats | null) => {
    setZipStats(stats);
  }, []);

  if (!currentFile) return null;

  const showCloseButton = mode === 'modal' && !!onClose;

  // 工具栏配置 — 各 Renderer 自行声明。命中自定义渲染器时优先使用其 getToolbarGroups
  const toolGroups: ToolbarGroup[] = (() => {
    if (customRenderer) {
      return customRenderer.getToolbarGroups?.(currentFile, customCtx) ?? [];
    }
    if (fileType === 'image') {
      return getImageToolbarGroups({
        zoom,
        onZoomIn: handleZoomIn,
        onZoomOut: handleZoomOut,
        onFitToWidth: handleFitToWidth,
        onOriginalSize: handleOriginalSize,
        onRotateLeft: handleRotateLeft,
        onRotateRight: handleRotate,
        onReset: handleReset,
        t,
      });
    }
    if (fileType === 'pdf') {
      return getPdfToolbarGroups({
        zoom,
        onZoomIn: handleZoomIn,
        onZoomOut: handleZoomOut,
        onReset: handleReset,
        t,
      });
    }
    if (fileType === 'epub') {
      return getEpubToolbarGroups({
        epubRef,
        current: epubCurrent,
        total: epubTotal,
        fullWidth: epubFullWidth,
        t,
      });
    }
    if (fileType === 'mobi') {
      return getMobiToolbarGroups({
        mobiRef,
        current: mobiCurrent,
        total: mobiTotal,
        fullWidth: mobiFullWidth,
        t,
      });
    }
    if (fileType === 'zip') {
      return getZipToolbarGroups({ stats: zipStats, t });
    }
    if (fileType === 'text') {
      const ext = currentFile.name.split('.').pop()?.toLowerCase() || '';
      return getTextToolbarGroups({
        wordWrap: textWordWrap,
        onToggleWrap: () => setTextWordWrap(prev => !prev),
        isHtml: ext === 'html' || ext === 'htm',
        htmlPreview: textHtmlPreview,
        onToggleHtmlPreview: () => setTextHtmlPreview(prev => !prev),
        t,
      });
    }
    if (fileType === 'markdown') {
      return getMarkdownToolbarGroups({
        viewMode: markdownViewMode,
        onToggleViewMode: () => setMarkdownViewMode(prev => prev === 'preview' ? 'source' : 'preview'),
        t,
      });
    }
    return [];
  })();

  // 操作组：下载、关闭（通用，不属于任何 Renderer）
  const actionGroups: ToolbarGroup[] = [
    {
      items: [
        { type: 'button', icon: <Download className="rfp-w-4 rfp-h-4" />, tooltip: t('common.download'), action: handleDownload },
      ],
    },
    ...(showCloseButton ? [{
      items: [
        { type: 'button' as const, icon: <X className="rfp-w-4 rfp-h-4" />, tooltip: t('common.close'), action: onClose! },
      ],
    }] : []),
  ];

  const renderToolbarItems = (groups: ToolbarGroup[], dividerClass: string) =>
    groups.map((group, gi, arr) => (
      <React.Fragment key={gi}>
        {group.items.map((item, ii) =>
          item.type === 'button' ? (
            <ToolbarButton
              key={`${gi}-${ii}`}
              icon={item.icon}
              label={item.tooltip}
              onClick={item.action}
              disabled={item.disabled}
            />
          ) : (
            <span
              key={`${gi}-${ii}`}
              className="rfp-text-xs rfp-text-center rfp-font-medium rfp-tabular-nums rfp-text-fg-tertiary"
              style={{ minWidth: item.minWidth || 'auto' }}
            >
              {item.content}
            </span>
          )
        )}
        {gi < arr.length - 1 && <div className={`rfp-w-px rfp-h-4 rfp-bg-divide ${dividerClass}`} />}
      </React.Fragment>
    ));

  return (
    <LocaleProvider locale={locale} messages={userMessages}>
    <ThemeProvider theme={resolvedTheme}>
    <div
      ref={rootRef}
      tabIndex={mode === 'embed' ? 0 : -1}
      data-theme={resolvedTheme}
      className="rfp-relative rfp-w-full rfp-h-full rfp-flex rfp-flex-col rfp-overflow-hidden rfp-outline-none"
    >
      {/* 顶部工具栏 - 全屏融合式 */}
      {!headless && (
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="rfp-flex-shrink-0 rfp-z-10 rfp-backdrop-blur-md rfp-border-b rfp-bg-surface-toolbar rfp-border-line"
        style={{ paddingTop: 'env(safe-area-inset-top, 0px)' }}
      >
        {/* 第一行:文件名 + 分页 + 关闭/下载(移动端右侧)/ 全部按钮(桌面端) */}
        <div className="rfp-flex rfp-items-center rfp-justify-between rfp-px-3 md:rfp-px-5 rfp-py-1.5 md:rfp-py-2.5">
          {/* 左侧:文件名 + 分页 */}
          <div className="rfp-flex rfp-items-center rfp-flex-1 rfp-min-w-0 rfp-mr-2 md:rfp-mr-3">
            <h2 className="rfp-font-medium rfp-text-xs md:rfp-text-sm rfp-truncate rfp-text-fg-primary">
              {currentFile.name}
            </h2>
            <span className="rfp-text-xs rfp-ml-2 rfp-flex-shrink-0 rfp-text-fg-muted">
              {currentIndex + 1}/{normalizedFiles.length}
            </span>
          </div>

          {/* 移动端:仅显示下载+关闭 */}
          <div className="rfp-flex rfp-items-center rfp-gap-1 md:rfp-hidden rfp-flex-shrink-0">
            {renderToolbarItems(actionGroups, 'rfp-mx-0.5')}
          </div>

          {/* 桌面端:所有工具按钮 */}
          <div className="rfp-hidden md:rfp-flex rfp-items-center rfp-gap-1 rfp-flex-shrink-0">
            {renderToolbarItems(toolGroups, 'rfp-mx-1')}
            {toolGroups.length > 0 && <div className="rfp-w-px rfp-h-4 rfp-mx-1 rfp-bg-divide" />}
            {renderToolbarItems(actionGroups, 'rfp-mx-1')}
          </div>
        </div>

        {/* 第二行:移动端工具按钮(image/pdf/epub) */}
        {toolGroups.length > 0 && (
          <div className="rfp-flex rfp-items-center rfp-gap-1 rfp-px-3 rfp-pb-1.5 rfp-overflow-x-auto scrollbar-hide md:rfp-hidden">
            {renderToolbarItems(toolGroups, 'rfp-mx-0.5')}
          </div>
        )}
      </motion.div>
      )}

      {/* 内容区域 */}
      <div
        ref={contentRef}
        className="rfp-flex-1 rfp-flex rfp-items-center rfp-justify-center rfp-overflow-auto"
      >
        {customRenderer ? (
          customRenderer.render(currentFile, customCtx)
        ) : (
          <Suspense fallback={<RendererLoading />} key={currentFile.url}>
            {fileType === 'image' && (
              <ImageRenderer
                url={resolvedUrl}
                zoom={zoom}
                rotation={rotation}
                resetKey={imageResetKey}
                fileSize={currentFile.size}
                file={currentFile}
                onZoomChange={handleZoomChange}
                onNaturalWidthChange={setContentNaturalWidth}
                onNaturalHeightChange={setContentNaturalHeight}
              />
            )}
            {fileType === 'pdf' && (
              <PdfRenderer
                url={resolvedUrl}
                zoom={zoom}
                currentPage={currentPage}
                onPageChange={setCurrentPage}
                onTotalPagesChange={setTotalPages}
                onPageWidthChange={setContentNaturalWidth}
              />
            )}
            {fileType === 'docx' && <DocxRenderer url={resolvedUrl} />}
            {fileType === 'xlsx' && <XlsxRenderer url={resolvedUrl} />}
            {fileType === 'pptx' && <PptxRenderer url={resolvedUrl} />}
            {fileType === 'msg' && <MsgRenderer url={resolvedUrl} />}
            {fileType === 'epub' && (
              <EpubRenderer
                ref={epubRef}
                url={resolvedUrl}
                onChapterChange={handleEpubChapterChange}
                onFullWidthChange={setEpubFullWidth}
              />
            )}
            {fileType === 'mobi' && (
              <MobiRenderer
                ref={mobiRef}
                url={resolvedUrl}
                onChapterChange={handleMobiChapterChange}
                onFullWidthChange={setMobiFullWidth}
              />
            )}
            {fileType === 'video' && <VideoRenderer url={resolvedUrl} fileName={currentFile.name} />}
            {fileType === 'audio' && (
              <AudioRenderer url={resolvedUrl} fileName={currentFile.name} />
            )}
            {fileType === 'markdown' && <MarkdownRenderer url={resolvedUrl} viewMode={markdownViewMode} />}
            {fileType === 'json' && (
              <JsonRenderer url={resolvedUrl} fileName={currentFile.name} />
            )}
            {fileType === 'csv' && (
              <CsvRenderer url={resolvedUrl} fileName={currentFile.name} />
            )}
            {fileType === 'xml' && (
              <XmlRenderer url={resolvedUrl} fileName={currentFile.name} />
            )}
            {fileType === 'subtitle' && (
              <SubtitleRenderer url={resolvedUrl} fileName={currentFile.name} />
            )}
            {fileType === 'zip' && (
              zipNestingDepth >= MAX_ZIP_NESTING_DEPTH ? (
                <UnsupportedRenderer
                  fileName={currentFile.name}
                  fileType={currentFile.type}
                  onDownload={handleDownload}
                />
              ) : (
                <ZipRenderer url={resolvedUrl} onStatsChange={handleZipStatsChange} nestingDepth={zipNestingDepth} />
              )
            )}
            {fileType === 'text' && (
              <TextRenderer
                url={resolvedUrl}
                fileName={currentFile.name}
                wordWrap={textWordWrap}
                htmlPreview={textHtmlPreview}
              />
            )}
            {fileType === 'font' && <FontRenderer url={resolvedUrl} />}
            {fileType === 'unsupported' && (
              <UnsupportedRenderer
                fileName={currentFile.name}
                fileType={currentFile.type}
                onDownload={handleDownload}
              />
            )}
          </Suspense>
        )}
      </div>

      {/* 左右导航箭头 - 自动隐藏（隔离 state,避免拖选时的 mousemove/timer 污染整树 re-render） */}
      {!headless && normalizedFiles.length > 1 && (
        <NavArrows
          containerRef={contentRef}
          hasPrev={currentIndex > 0}
          hasNext={currentIndex < normalizedFiles.length - 1}
          onPrev={() => onNavigate?.(currentIndex - 1)}
          onNext={() => onNavigate?.(currentIndex + 1)}
          resetKey={currentIndex}
        />
      )}
    </div>
    </ThemeProvider>
    </LocaleProvider>
  );
};

// 工具栏按钮组件
interface ToolbarButtonProps {
  icon: React.ReactNode;
  label: string;
  onClick: () => void;
  disabled?: boolean;
}

const ToolbarButton: React.FC<ToolbarButtonProps> = ({ icon, label, onClick, disabled }) => {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className={`rfp-relative rfp-group rfp-p-2 md:rfp-p-1.5 rfp-rounded-md rfp-transition-all rfp-select-none ${
        disabled
          ? 'rfp-text-fg-disabled rfp-cursor-not-allowed'
          : 'rfp-text-fg-primary hover:rfp-bg-surface-2 active:rfp-bg-surface-3'
      }`}
    >
      {icon}
      <span className="rfp-absolute rfp-left-1/2 -rfp-translate-x-1/2 rfp-top-full rfp-mt-1.5 rfp-px-2 rfp-py-1 rfp-text-xs rfp-rounded rfp-whitespace-nowrap rfp-pointer-events-none rfp-opacity-0 rfp-invisible group-hover:rfp-opacity-100 group-hover:rfp-visible rfp-transition-opacity rfp-duration-200 rfp-z-50 rfp-bg-fg-primary rfp-text-fg-inverse max-[1023px]:!rfp-hidden">
        <span className="rfp-absolute rfp-left-1/2 -rfp-translate-x-1/2 -rfp-top-1 rfp-w-2 rfp-h-2 rfp-rotate-45 rfp-bg-fg-primary" />
        <span className="rfp-relative">{label}</span>
      </span>
    </button>
  );
};

// 导航箭头：自带 mousemove 监听 + 2s 自动隐藏定时器,
// state 隔离在本组件,避免 FilePreviewContent 整树因 navVisible 变化而 re-render
interface NavArrowsProps {
  containerRef: React.RefObject<HTMLDivElement | null>;
  hasPrev: boolean;
  hasNext: boolean;
  onPrev: () => void;
  onNext: () => void;
  resetKey: number;
}

const NAV_HIDE_DELAY = 2000;

const NavArrows: React.FC<NavArrowsProps> = ({
  containerRef,
  hasPrev,
  hasNext,
  onPrev,
  onNext,
  resetKey,
}) => {
  const [visible, setVisible] = useState(true);
  const timerRef = useRef<number | null>(null);

  const scheduleHide = useCallback(() => {
    if (timerRef.current) clearTimeout(timerRef.current);
    timerRef.current = window.setTimeout(() => setVisible(false), NAV_HIDE_DELAY);
  }, []);

  const show = useCallback(() => {
    setVisible((prev) => (prev ? prev : true));
    scheduleHide();
  }, [scheduleHide]);

  // 监听容器的 mousemove,触发显示+重置隐藏定时器
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const handler = () => show();
    el.addEventListener('mousemove', handler);
    return () => {
      el.removeEventListener('mousemove', handler);
    };
  }, [containerRef, show]);

  // currentIndex 切换时,显示一次并重置定时器
  useEffect(() => {
    setVisible(true);
    scheduleHide();
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [resetKey, scheduleHide]);

  return (
    <>
      {hasPrev && (
        <motion.button
          initial={{ opacity: 0 }}
          animate={{ opacity: visible ? 1 : 0, x: visible ? 0 : -20 }}
          transition={{ duration: 0.2 }}
          onClick={onPrev}
          onMouseEnter={show}
          style={{ pointerEvents: visible ? 'auto' : 'none' }}
          className="rfp-absolute rfp-z-20 rfp-left-2 md:rfp-left-4 rfp-top-1/2 -rfp-translate-y-1/2 rfp-w-10 rfp-h-10 md:rfp-w-12 md:rfp-h-12 rfp-rounded-full rfp-backdrop-blur-xl rfp-border rfp-flex rfp-items-center rfp-justify-center rfp-transition-colors rfp-shadow-2xl rfp-bg-surface-nav rfp-border-line hover:rfp-bg-surface-nav-hover rfp-text-fg-primary"
        >
          <ChevronLeft className="rfp-w-5 rfp-h-5 md:rfp-w-6 md:rfp-h-6" />
        </motion.button>
      )}
      {hasNext && (
        <motion.button
          initial={{ opacity: 0 }}
          animate={{ opacity: visible ? 1 : 0, x: visible ? 0 : 20 }}
          transition={{ duration: 0.2 }}
          onClick={onNext}
          onMouseEnter={show}
          style={{ pointerEvents: visible ? 'auto' : 'none' }}
          className="rfp-absolute rfp-z-20 rfp-right-2 md:rfp-right-4 rfp-top-1/2 -rfp-translate-y-1/2 rfp-w-10 rfp-h-10 md:rfp-w-12 md:rfp-h-12 rfp-rounded-full rfp-backdrop-blur-xl rfp-border rfp-flex rfp-items-center rfp-justify-center rfp-transition-colors rfp-shadow-2xl rfp-bg-surface-nav rfp-border-line hover:rfp-bg-surface-nav-hover rfp-text-fg-primary"
        >
          <ChevronRight className="rfp-w-5 rfp-h-5 md:rfp-w-6 md:rfp-h-6" />
        </motion.button>
      )}
    </>
  );
};

// packages/vue-file-preview/src/FilePreviewContent.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onBeforeUnmount, toRef, provide } from 'vue';
import { X, Download, ChevronLeft, ChevronRight } from 'lucide-vue-next';
import {
  normalizeFiles,
  getFileType,
  downloadFileWithFetcher,
  type PreviewFile,
  type PreviewFileInput,
  type Locale,
  type Messages,
  type Theme,
  type CustomRendererEventPayload,
  type RequestHandler,
  type RequestInitFactory,
  type ShouldFetchAsBlob,
} from '@eternalheart/file-preview-core';
import type { CustomRenderer, CustomRendererContext } from './types';
import { provideLocale, useTranslator } from './composables/useTranslator';
import { provideResolvedTheme } from './composables/useResolvedTheme';
import { provideRequestContext, useResolvedUrl, useFetcher } from './composables/useRequest';
import type { ToolbarGroup, ToolbarButtonItem, ToolbarTextItem } from './renderers/toolbar.types';
import { getImageToolbarGroups } from './renderers/Image/toolbar';
import { getPdfToolbarGroups } from './renderers/Pdf/toolbar';
import { getEpubToolbarGroups } from './renderers/Epub/toolbar';
import { getMobiToolbarGroups } from './renderers/Mobi/toolbar';
import { getZipToolbarGroups, type ZipToolbarStats } from './renderers/Zip/toolbar';
import { getTextToolbarGroups } from './renderers/Text/toolbar';
import { getMarkdownToolbarGroups } from './renderers/Markdown/toolbar';
// Renderer 通过 defineAsyncComponent 动态加载，运行时按需下载对应 chunk
import {
  ImageRenderer,
  PdfRenderer,
  DocxRenderer,
  XlsxRenderer,
  PptxRenderer,
  MsgRenderer,
  EpubRenderer,
  MobiRenderer,
  VideoRenderer,
  AudioRenderer,
  MarkdownRenderer,
  JsonRenderer,
  CsvRenderer,
  XmlRenderer,
  SubtitleRenderer,
  ZipRenderer,
  TextRenderer,
  FontRenderer,
} from './renderers/lazy';
// Unsupported 体量极小且每次回退都用，直接静态打包到主入口
import UnsupportedRenderer from './renderers/Unsupported/index.vue';

const MAX_ZIP_NESTING_DEPTH = 3;

interface Props {
  files: PreviewFileInput[];
  currentIndex: number;
  customRenderers?: CustomRenderer[];
  /** 运行模式: modal(弹窗) 或 embed(嵌入) */
  mode?: 'modal' | 'embed';
  /** ZIP 嵌套深度（内部使用），超过上限时不再递归渲染 ZIP */
  zipNestingDepth?: number;
  /** 语言 */
  locale?: Locale;
  /** 自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头，仅渲染文件内容 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义 RequestInit（或工厂函数）：注入 Authorization 等鉴权头 */
  requestInit?: RequestInitFactory;
  /** 自定义请求处理器：完全接管库内 fetch */
  requestHandler?: RequestHandler;
  /** 返回 true 时，对应文件先 fetcher→blob URL 后喂给 image/video/audio/pdf 等 renderer */
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  /** 自定义下载回调；不传时库内默认通过 fetcher 拉 Blob 触发下载 */
  onDownload?: (file: PreviewFile) => void | Promise<void>;
}

const props = withDefaults(defineProps<Props>(), {
  customRenderers: () => [],
  mode: 'modal',
  zipNestingDepth: 0,
  locale: undefined,
  messages: undefined,
  headless: false,
  theme: 'dark',
  requestInit: undefined,
  requestHandler: undefined,
  shouldFetchAsBlob: undefined,
  onDownload: undefined,
});

provideRequestContext(() => ({
  requestInit: props.requestInit,
  requestHandler: props.requestHandler,
  shouldFetchAsBlob: props.shouldFetchAsBlob,
}));

const emit = defineEmits<{
  (e: 'navigate', index: number): void;
  (e: 'close'): void;
  (e: 'custom-event', payload: CustomRendererEventPayload): void;
}>();

provideLocale(toRef(props, 'locale'), toRef(props, 'messages'));
const { t } = useTranslator();

const systemDark = ref(
  typeof window !== 'undefined'
    ? window.matchMedia('(prefers-color-scheme: dark)').matches
    : true,
);

let mediaQueryCleanup: (() => void) | null = null;

watch(
  () => props.theme,
  (theme) => {
    if (mediaQueryCleanup) {
      mediaQueryCleanup();
      mediaQueryCleanup = null;
    }
    if (theme === 'auto') {
      const mql = window.matchMedia('(prefers-color-scheme: dark)');
      const handler = (e: MediaQueryListEvent) => { systemDark.value = e.matches; };
      mql.addEventListener('change', handler);
      mediaQueryCleanup = () => mql.removeEventListener('change', handler);
    }
  },
  { immediate: true },
);

onBeforeUnmount(() => {
  if (mediaQueryCleanup) mediaQueryCleanup();
});

const resolvedTheme = computed(() =>
  props.theme === 'auto' ? (systemDark.value ? 'dark' : 'light') : props.theme,
);
provideResolvedTheme(resolvedTheme);

const zoom = ref(1);
const rotation = ref(0);
const currentPage = ref(1);
const totalPages = ref(1);
const contentNaturalWidth = ref(0);
const contentNaturalHeight = ref(0);
const imageResetKey = ref(0);

const contentRef = ref<HTMLDivElement | null>(null);
const rootRef = ref<HTMLDivElement | null>(null);

// 导航箭头自动隐藏
const navVisible = ref(true);
let navHideTimer: number | null = null;
const NAV_HIDE_DELAY = 2000;

const resetNavTimer = () => {
  navVisible.value = true;
  if (navHideTimer !== null) {
    clearTimeout(navHideTimer);
  }
  navHideTimer = window.setTimeout(() => {
    navVisible.value = false;
  }, NAV_HIDE_DELAY);
};

const handleMouseMove = () => resetNavTimer();

// 标准化文件输入
const normalizedFiles = computed(() => normalizeFiles(props.files));

const currentFile = computed(() => normalizedFiles.value[props.currentIndex]);

// 命中 shouldFetchAsBlob 时，把 file.url 转成 blob: URL 喂给 src 类 renderer
const resolvedUrl = useResolvedUrl(currentFile);

// 自定义渲染器匹配
const customRenderer = computed(() => {
  if (!currentFile.value) return null;
  return props.customRenderers.find((r) => r.test(currentFile.value!)) || null;
});

const customRendererComponent = computed(() => {
  if (!customRenderer.value || !currentFile.value) return null;
  return customRenderer.value.render(currentFile.value, customCtx.value);
});

const fileType = computed(() => (currentFile.value ? getFileType(currentFile.value) : 'unsupported'));

// 自定义渲染器事件派发器：未绑定 @custom-event 时仍调用 emit（Vue 会安全忽略未声明监听）
const emitCustom = (name: string, payload?: unknown) => {
  if (!currentFile.value) return;
  const ev: CustomRendererEventPayload = { name, payload, file: currentFile.value };
  emit('custom-event', ev);
};

// 自定义渲染器上下文
const customCtx = computed<CustomRendererContext>(() => ({
  emit: emitCustom,
  t: t.value,
  theme: resolvedTheme.value,
  locale: (props.locale ?? 'zh-CN') as Locale,
}));

// 通过 provide 暴露给深层子组件 inject 使用
provide('file-preview:custom-ctx', customCtx);

// 重置状态当文件改变时
watch(
  () => props.currentIndex,
  () => {
    zoom.value = 1;
    rotation.value = 0;
    currentPage.value = 1;
    totalPages.value = 1;
    contentNaturalWidth.value = 0;
    contentNaturalHeight.value = 0;
    navVisible.value = true;
    if (navHideTimer !== null) {
      clearTimeout(navHideTimer);
    }
  }
);

// 图片加载后默认适应窗口
watch(
  [fileType, contentNaturalWidth, contentNaturalHeight],
  () => {
    if (
      fileType.value === 'image' &&
      contentNaturalWidth.value > 0 &&
      contentNaturalHeight.value > 0 &&
      contentRef.value
    ) {
      const containerWidth = contentRef.value.clientWidth;
      const containerHeight = contentRef.value.clientHeight;
      const scaleX = containerWidth / contentNaturalWidth.value;
      const scaleY = containerHeight / contentNaturalHeight.value;
      const newZoom = Math.min(scaleX, scaleY);
      zoom.value = Math.max(0.01, Math.min(10, newZoom));
    }
  }
);

// 导航箭头自动隐藏计时器
watch(
  () => normalizedFiles.value.length,
  (len) => {
    if (len > 1) resetNavTimer();
  },
  { immediate: true }
);

// 键盘导航
const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Escape' && props.mode === 'modal') {
    emit('close');
  } else if (e.key === 'ArrowLeft' && props.currentIndex > 0) {
    emit('navigate', props.currentIndex - 1);
  } else if (e.key === 'ArrowRight' && props.currentIndex < normalizedFiles.value.length - 1) {
    emit('navigate', props.currentIndex + 1);
  }
};

onMounted(() => {
  if (props.mode === 'modal') {
    window.addEventListener('keydown', handleKeyDown);
  } else if (rootRef.value) {
    rootRef.value.addEventListener('keydown', handleKeyDown as EventListener);
  }
});

onBeforeUnmount(() => {
  if (navHideTimer !== null) clearTimeout(navHideTimer);
  if (props.mode === 'modal') {
    window.removeEventListener('keydown', handleKeyDown);
  } else if (rootRef.value) {
    rootRef.value.removeEventListener('keydown', handleKeyDown as EventListener);
  }
});

const handleZoomIn = () => {
  zoom.value = Math.min(zoom.value + 0.1, 10);
};
const handleZoomOut = () => {
  zoom.value = Math.max(zoom.value - 0.1, 0.01);
};
const handleRotate = () => {
  rotation.value = rotation.value + 90;
};
const handleRotateLeft = () => {
  rotation.value = rotation.value - 90;
};

const handleFitToWidth = () => {
  if (contentRef.value && contentNaturalWidth.value > 0 && contentNaturalHeight.value > 0) {
    const containerWidth = contentRef.value.clientWidth;
    const containerHeight = contentRef.value.clientHeight;
    const scaleX = containerWidth / contentNaturalWidth.value;
    const scaleY = containerHeight / contentNaturalHeight.value;
    const newZoom = Math.min(scaleX, scaleY);
    zoom.value = Math.max(0.01, Math.min(10, newZoom));
  } else {
    zoom.value = 1;
  }
  rotation.value = 0;
  imageResetKey.value++;
};

const handleOriginalSize = () => {
  zoom.value = 1;
  rotation.value = 0;
  imageResetKey.value++;
};

const handleZoomChange = (newZoom: number) => {
  zoom.value = newZoom;
};

const handleReset = () => {
  zoom.value = 1;
  rotation.value = 0;
  imageResetKey.value++;
};

const fetcher = useFetcher();
const handleDownload = async () => {
  if (!currentFile.value) return;
  if (props.onDownload) {
    await props.onDownload(currentFile.value);
    return;
  }
  try {
    await downloadFileWithFetcher(currentFile.value.url, currentFile.value.name, fetcher.value);
  } catch (err) {
    console.error('[file-preview] download failed:', err);
  }
};

const showCloseButton = computed(() => props.mode === 'modal');

const epubRef = ref<{ prevPage: () => void; nextPage: () => void; toggleFullWidth: () => void; toggleToc: () => void } | null>(null);
const epubCurrent = ref(0);
const epubTotal = ref(0);
const epubFullWidth = ref(false);

const mobiRef = ref<{ prevPage: () => void; nextPage: () => void; toggleFullWidth: () => void; toggleToc: () => void } | null>(null);
const mobiCurrent = ref(0);
const mobiTotal = ref(0);
const mobiFullWidth = ref(false);

const handleEpubChapterChange = (current: number, total: number) => {
  epubCurrent.value = current;
  epubTotal.value = total;
};

const handleMobiChapterChange = (current: number, total: number) => {
  mobiCurrent.value = current;
  mobiTotal.value = total;
};

const zipStats = ref<ZipToolbarStats | null>(null);
const handleZipStatsChange = (stats: ZipToolbarStats | null) => {
  zipStats.value = stats;
};

const textWordWrap = ref(true);
const textHtmlPreview = ref(false);
const markdownViewMode = ref<'preview' | 'source'>('preview');

// 工具栏配置 — 各 Renderer 自行声明。命中自定义渲染器时优先使用其 getToolbarGroups
const toolGroups = computed(() => {
  if (customRenderer.value) {
    return (
      customRenderer.value.getToolbarGroups?.(currentFile.value!, customCtx.value) ?? []
    );
  }
  if (fileType.value === 'image') {
    return getImageToolbarGroups({
      zoom: zoom.value,
      onZoomIn: handleZoomIn,
      onZoomOut: handleZoomOut,
      onFitToWidth: handleFitToWidth,
      onOriginalSize: handleOriginalSize,
      onRotateLeft: handleRotateLeft,
      onRotateRight: handleRotate,
      onReset: handleReset,
      t: t.value,
    });
  }
  if (fileType.value === 'pdf') {
    return getPdfToolbarGroups({
      zoom: zoom.value,
      onZoomIn: handleZoomIn,
      onZoomOut: handleZoomOut,
      onReset: handleReset,
      t: t.value,
    });
  }
  if (fileType.value === 'epub') {
    return getEpubToolbarGroups({
      epubRef: epubRef.value,
      current: epubCurrent.value,
      total: epubTotal.value,
      fullWidth: epubFullWidth.value,
      t: t.value,
    });
  }
  if (fileType.value === 'mobi') {
    return getMobiToolbarGroups({
      mobiRef: mobiRef.value,
      current: mobiCurrent.value,
      total: mobiTotal.value,
      fullWidth: mobiFullWidth.value,
      t: t.value,
    });
  }
  if (fileType.value === 'zip') {
    return getZipToolbarGroups({ stats: zipStats.value, t: t.value });
  }
  if (fileType.value === 'text') {
    const ext = currentFile.value!.name.split('.').pop()?.toLowerCase() || '';
    return getTextToolbarGroups({
      wordWrap: textWordWrap.value,
      onToggleWrap: () => { textWordWrap.value = !textWordWrap.value; },
      isHtml: ext === 'html' || ext === 'htm',
      htmlPreview: textHtmlPreview.value,
      onToggleHtmlPreview: () => { textHtmlPreview.value = !textHtmlPreview.value; },
      t: t.value,
    });
  }
  if (fileType.value === 'markdown') {
    return getMarkdownToolbarGroups({
      viewMode: markdownViewMode.value,
      onToggleViewMode: () => { markdownViewMode.value = markdownViewMode.value === 'preview' ? 'source' : 'preview'; },
      t: t.value,
    });
  }
  return [];
});

// 操作组：下载、关闭（通用，不属于任何 Renderer）
const actionGroups = computed<ToolbarGroup[]>(() => {
  const groups: ToolbarGroup[] = [
    {
      items: [
        { type: 'button', icon: Download, tooltip: t.value('common.download'), action: handleDownload },
      ],
    },
  ];
  if (showCloseButton.value) {
    groups.push({
      items: [
        { type: 'button', icon: X, tooltip: t.value('common.close'), action: () => emit('close') },
      ],
    });
  }
  return groups;
});

const hasToolGroups = computed(() => toolGroups.value.length > 0);
</script>

<template>
  <div
    ref="rootRef"
    :tabindex="mode === 'embed' ? 0 : -1"
    :data-theme="resolvedTheme"
    class="vfp-relative vfp-w-full vfp-h-full vfp-flex vfp-flex-col vfp-overflow-hidden vfp-outline-none"
  >
    <!-- 顶部工具栏 -->
    <div
      v-if="!headless"
      class="vfp-flex-shrink-0 vfp-z-10 vfp-backdrop-blur-md vfp-border-b vfp-bg-surface-toolbar vfp-border-line"
      style="padding-top: env(safe-area-inset-top, 0px)"
    >
      <!-- 第一行: 文件名 + 桌面端工具按钮 -->
      <div class="vfp-flex vfp-items-center vfp-justify-between vfp-px-3 md:vfp-px-5 vfp-py-1.5 md:vfp-py-2.5">
        <!-- 左侧: 文件名 + 分页 -->
        <div class="vfp-flex vfp-items-center vfp-flex-1 vfp-min-w-0 vfp-mr-2 md:vfp-mr-3">
          <h2 class="vfp-font-medium vfp-text-xs md:vfp-text-sm vfp-truncate vfp-text-fg-primary">
            {{ currentFile?.name }}
          </h2>
          <span class="vfp-text-xs vfp-ml-2 vfp-flex-shrink-0 vfp-text-fg-muted">
            {{ currentIndex + 1 }}/{{ normalizedFiles.length }}
          </span>
        </div>

        <!-- 移动端: 仅下载 + 关闭 -->
        <div class="vfp-flex vfp-items-center vfp-gap-1 md:vfp-hidden vfp-flex-shrink-0">
          <template v-for="(group, gi) in actionGroups" :key="'m-action-' + gi">
            <template v-for="(item, ii) in group.items" :key="'m-action-' + gi + '-' + ii">
              <button
                v-if="item.type === 'button'"
                class="toolbar-btn"
                :data-tooltip="(item as ToolbarButtonItem).tooltip"
                :disabled="(item as ToolbarButtonItem).disabled"
                @click="(item as ToolbarButtonItem).action"
              >
                <component :is="(item as ToolbarButtonItem).icon" class="vfp-w-4 vfp-h-4" />
              </button>
            </template>
          </template>
        </div>

        <!-- 桌面端: 完整工具按钮 -->
        <div class="vfp-hidden md:vfp-flex vfp-items-center vfp-gap-1 vfp-flex-shrink-0">
          <template v-for="(group, gi) in toolGroups" :key="'d-tool-' + gi">
            <template v-for="(item, ii) in group.items" :key="'d-tool-' + gi + '-' + ii">
              <button
                v-if="item.type === 'button'"
                class="toolbar-btn"
                :data-tooltip="(item as ToolbarButtonItem).tooltip"
                :disabled="(item as ToolbarButtonItem).disabled"
                @click="(item as ToolbarButtonItem).action"
              >
                <component :is="(item as ToolbarButtonItem).icon" class="vfp-w-4 vfp-h-4" />
              </button>
              <span
                v-else-if="item.type === 'text'"
                class="vfp-text-xs vfp-text-center vfp-font-medium vfp-tabular-nums vfp-text-fg-tertiary"
                :style="{ minWidth: (item as ToolbarTextItem).minWidth || 'auto' }"
              >
                {{ (item as ToolbarTextItem).content }}
              </span>
            </template>
            <div class="vfp-w-px vfp-h-4 vfp-mx-1 vfp-bg-divide" />
          </template>
          <template v-for="(group, gi) in actionGroups" :key="'d-action-' + gi">
            <template v-for="(item, ii) in group.items" :key="'d-action-' + gi + '-' + ii">
              <button
                v-if="item.type === 'button'"
                class="toolbar-btn"
                :data-tooltip="(item as ToolbarButtonItem).tooltip"
                :disabled="(item as ToolbarButtonItem).disabled"
                @click="(item as ToolbarButtonItem).action"
              >
                <component :is="(item as ToolbarButtonItem).icon" class="vfp-w-4 vfp-h-4" />
              </button>
            </template>
          </template>
        </div>
      </div>

      <!-- 移动端第二行工具按钮 -->
      <div
        v-if="hasToolGroups"
        class="vfp-flex vfp-items-center vfp-gap-1 vfp-px-3 vfp-pb-1.5 vfp-overflow-x-auto scrollbar-hide md:vfp-hidden"
      >
        <template v-for="(group, gi) in toolGroups" :key="'m-tool-' + gi">
          <div v-if="gi > 0" class="vfp-w-px vfp-h-4 vfp-mx-0.5 vfp-bg-divide" />
          <template v-for="(item, ii) in group.items" :key="'m-tool-' + gi + '-' + ii">
            <button
              v-if="item.type === 'button'"
              class="toolbar-btn"
              :data-tooltip="(item as ToolbarButtonItem).tooltip"
              :disabled="(item as ToolbarButtonItem).disabled"
              @click="(item as ToolbarButtonItem).action"
            >
              <component :is="(item as ToolbarButtonItem).icon" class="vfp-w-4 vfp-h-4" />
            </button>
            <span
              v-else-if="item.type === 'text'"
              class="vfp-text-xs vfp-text-center vfp-font-medium vfp-tabular-nums vfp-text-fg-tertiary"
              :style="{ minWidth: (item as ToolbarTextItem).minWidth || 'auto' }"
            >
              {{ (item as ToolbarTextItem).content }}
            </span>
          </template>
        </template>
      </div>
    </div>

    <!-- 内容区域 -->
    <div
      ref="contentRef"
      class="vfp-flex-1 vfp-flex vfp-items-center vfp-justify-center vfp-overflow-auto"
      @mousemove="handleMouseMove"
    >
      <template v-if="currentFile">
        <component :is="customRendererComponent" v-if="customRendererComponent" :file="currentFile" :ctx="customCtx" />
        <template v-else>
          <ImageRenderer
            v-if="fileType === 'image'"
            :url="resolvedUrl"
            :zoom="zoom"
            :rotation="rotation"
            :reset-key="imageResetKey"
            :file-size="currentFile.size"
            @zoom-change="handleZoomChange"
            @natural-width-change="(w: number) => (contentNaturalWidth = w)"
            @natural-height-change="(h: number) => (contentNaturalHeight = h)"
          />
          <PdfRenderer
            v-else-if="fileType === 'pdf'"
            :url="resolvedUrl"
            :zoom="zoom"
            :current-page="currentPage"
            @page-change="(p: number) => (currentPage = p)"
            @total-pages-change="(t: number) => (totalPages = t)"
            @page-width-change="(w: number) => (contentNaturalWidth = w)"
          />
          <DocxRenderer v-else-if="fileType === 'docx'" :url="resolvedUrl" />
          <XlsxRenderer v-else-if="fileType === 'xlsx'" :url="resolvedUrl" />
          <PptxRenderer v-else-if="fileType === 'pptx'" :url="resolvedUrl" />
          <MsgRenderer v-else-if="fileType === 'msg'" :url="resolvedUrl" />
          <EpubRenderer
            v-else-if="fileType === 'epub'"
            ref="epubRef"
            :url="resolvedUrl"
            @chapter-change="handleEpubChapterChange"
            @full-width-change="(v: boolean) => (epubFullWidth = v)"
          />
          <MobiRenderer
            v-else-if="fileType === 'mobi'"
            ref="mobiRef"
            :url="resolvedUrl"
            @chapter-change="handleMobiChapterChange"
            @full-width-change="(v: boolean) => (mobiFullWidth = v)"
          />
          <VideoRenderer v-else-if="fileType === 'video'" :url="resolvedUrl" />
          <AudioRenderer
            v-else-if="fileType === 'audio'"
            :url="resolvedUrl"
            :file-name="currentFile.name"
          />
          <MarkdownRenderer v-else-if="fileType === 'markdown'" :url="resolvedUrl" :view-mode="markdownViewMode" />
          <JsonRenderer
            v-else-if="fileType === 'json'"
            :url="resolvedUrl"
            :file-name="currentFile.name"
          />
          <CsvRenderer
            v-else-if="fileType === 'csv'"
            :url="resolvedUrl"
            :file-name="currentFile.name"
          />
          <XmlRenderer
            v-else-if="fileType === 'xml'"
            :url="resolvedUrl"
            :file-name="currentFile.name"
          />
          <SubtitleRenderer
            v-else-if="fileType === 'subtitle'"
            :url="resolvedUrl"
            :file-name="currentFile.name"
          />
          <template v-else-if="fileType === 'zip' && props.zipNestingDepth >= MAX_ZIP_NESTING_DEPTH">
            <UnsupportedRenderer
              :file-name="currentFile.name"
              :file-type="currentFile.type"
              @download="handleDownload"
            />
          </template>
          <ZipRenderer
            v-else-if="fileType === 'zip'"
            :url="resolvedUrl"
            :nesting-depth="props.zipNestingDepth"
            @stats-change="handleZipStatsChange"
          />
          <TextRenderer
            v-else-if="fileType === 'text'"
            :url="resolvedUrl"
            :file-name="currentFile.name"
            :word-wrap="textWordWrap"
            :html-preview="textHtmlPreview"
          />
          <FontRenderer v-else-if="fileType === 'font'" :url="resolvedUrl" />
          <UnsupportedRenderer
            v-else
            :file-name="currentFile.name"
            :file-type="currentFile.type"
            @download="handleDownload"
          />
        </template>
      </template>
    </div>

    <!-- 左右导航箭头 -->
    <template v-if="!headless && normalizedFiles.length > 1">
      <button
        v-if="currentIndex > 0"
        :style="{
          opacity: navVisible ? 1 : 0,
          transform: navVisible ? 'translateY(-50%)' : 'translateY(-50%) translateX(-20px)',
          pointerEvents: navVisible ? 'auto' : 'none',
          transition: 'opacity 0.2s, transform 0.2s',
        }"
        class="vfp-absolute vfp-z-20 vfp-left-2 md:vfp-left-4 vfp-top-1/2 vfp-w-10 vfp-h-10 md:vfp-w-12 md:vfp-h-12 vfp-rounded-full vfp-backdrop-blur-xl vfp-border vfp-flex vfp-items-center vfp-justify-center vfp-transition-colors vfp-shadow-2xl vfp-bg-surface-nav vfp-border-line hover:vfp-bg-surface-nav-hover vfp-text-fg-primary"
        @click="emit('navigate', currentIndex - 1)"
        @mouseenter="navVisible = true"
      >
        <ChevronLeft class="vfp-w-5 vfp-h-5 md:vfp-w-6 md:vfp-h-6" />
      </button>

      <button
        v-if="currentIndex < normalizedFiles.length - 1"
        :style="{
          opacity: navVisible ? 1 : 0,
          transform: navVisible ? 'translateY(-50%)' : 'translateY(-50%) translateX(20px)',
          pointerEvents: navVisible ? 'auto' : 'none',
          transition: 'opacity 0.2s, transform 0.2s',
        }"
        class="vfp-absolute vfp-z-20 vfp-right-2 md:vfp-right-4 vfp-top-1/2 vfp-w-10 vfp-h-10 md:vfp-w-12 md:vfp-h-12 vfp-rounded-full vfp-backdrop-blur-xl vfp-border vfp-flex vfp-items-center vfp-justify-center vfp-transition-colors vfp-shadow-2xl vfp-bg-surface-nav vfp-border-line hover:vfp-bg-surface-nav-hover vfp-text-fg-primary"
        @click="emit('navigate', currentIndex + 1)"
        @mouseenter="navVisible = true"
      >
        <ChevronRight class="vfp-w-5 vfp-h-5 md:vfp-w-6 md:vfp-h-6" />
      </button>
    </template>
  </div>
</template>

<style scoped>
.toolbar-btn {
  position: relative;
  padding: 0.5rem;
  border-radius: 0.375rem;
  transition: all 0.15s;
  user-select: none;
  color: var(--fp-fg-primary);
  background: transparent;
  border: 0;
  cursor: pointer;
}
@media (min-width: 768px) {
  .toolbar-btn {
    padding: 0.375rem;
  }
}
.toolbar-btn:hover {
  background: var(--fp-surface-2);
}
.toolbar-btn:active {
  background: var(--fp-surface-3);
}
.toolbar-btn:disabled {
  color: var(--fp-fg-disabled);
  cursor: not-allowed;
}
/* Tooltip */
.toolbar-btn[data-tooltip]::after {
  content: attr(data-tooltip);
  position: absolute;
  left: 50%;
  top: 100%;
  transform: translateX(-50%);
  margin-top: 6px;
  padding: 4px 8px;
  background: var(--fp-fg-primary);
  color: var(--fp-fg-inverse);
  font-size: 12px;
  line-height: 1.5;
  border-radius: 4px;
  white-space: nowrap;
  pointer-events: none;
  opacity: 0;
  visibility: hidden;
  transition: opacity 0.2s, visibility 0.2s;
  z-index: 50;
}
.toolbar-btn[data-tooltip]::before {
  content: '';
  position: absolute;
  left: 50%;
  top: 100%;
  transform: translateX(-50%);
  margin-top: 2px;
  border: 4px solid transparent;
  border-bottom-color: var(--fp-fg-primary);
  pointer-events: none;
  opacity: 0;
  visibility: hidden;
  transition: opacity 0.2s, visibility 0.2s;
  z-index: 50;
}
.toolbar-btn[data-tooltip]:hover::after,
.toolbar-btn[data-tooltip]:hover::before {
  opacity: 1;
  visibility: visible;
}
</style>
