// packages/vue-file-preview/src/renderers/Markdown/index.vue
<script setup lang="ts">
import { ref, computed, watch, nextTick } from 'vue';
import MarkdownIt from 'markdown-it';
import MarkdownItKatex from '@traptitech/markdown-it-katex';
import { codeToHtml } from 'shiki';
import { fetchTextUtf8 } from '@eternalheart/file-preview-core';
import { useTranslator } from '../../composables/useTranslator';
import { useResolvedTheme } from '../../composables/useResolvedTheme';
import 'katex/dist/katex.min.css';

const props = defineProps<{
  url: string;
  viewMode?: 'preview' | 'source';
}>();

const { t } = useTranslator();
const resolvedTheme = useResolvedTheme();
const shikiTheme = computed(() => (resolvedTheme.value === 'light' ? 'github-light' : 'github-dark'));

const content = ref('');
const html = ref('');
const highlightedSource = ref('');
const loading = ref(true);
const error = ref<string | null>(null);
const containerRef = ref<HTMLDivElement | null>(null);

// 创建 markdown-it 实例（支持 GFM 表格、删除线、任务列表、HTML、数学公式）
const md = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: false,
  breaks: false,
});
md.use(MarkdownItKatex);

// 自定义代码块渲染：包裹 code-block-wrapper + header（不含复制按钮，由 JS 动态注入）
md.renderer.rules.fence = (tokens, idx) => {
  const token = tokens[idx];
  const info = token.info ? token.info.trim() : '';
  const code = token.content;

  if (!info) {
    return `<div class="code-block-wrapper">
    <pre class="no-lang-pre"><code>${md.utils.escapeHtml(code)}</code></pre>
  </div>`;
  }

  return `<div class="code-block-wrapper">
    <div class="code-block-header">
      <span>${info}</span>
    </div>
    <pre data-shiki-pending="1" data-lang="${info}"><code>${md.utils.escapeHtml(code)}</code></pre>
  </div>`;
};

// 4-space 缩进代码块：同样包裹 code-block-wrapper（无头，注入浮动复制按钮）
md.renderer.rules.code_block = (tokens, idx) => {
  const code = tokens[idx].content;
  return `<div class="code-block-wrapper">
    <pre class="no-lang-pre"><code>${md.utils.escapeHtml(code)}</code></pre>
  </div>`;
};

// 表格添加包裹层（用于横向滚动）
const defaultTableOpen =
  md.renderer.rules.table_open ||
  ((tokens, idx, options, _env, self) => self.renderToken(tokens, idx, options));
md.renderer.rules.table_open = (tokens, idx, options, env, self) => {
  return '<div class="table-wrapper">' + defaultTableOpen(tokens, idx, options, env, self);
};
const defaultTableClose =
  md.renderer.rules.table_close ||
  ((tokens, idx, options, _env, self) => self.renderToken(tokens, idx, options));
md.renderer.rules.table_close = (tokens, idx, options, env, self) => {
  return defaultTableClose(tokens, idx, options, env, self) + '</div>';
};

const loadMarkdown = async () => {
  loading.value = true;
  error.value = null;
  try {
    const text = await fetchTextUtf8(props.url);
    content.value = text;
    html.value = md.render(text);
    loading.value = false;
    // 异步生成源码高亮（不阻塞预览渲染）
    try {
      highlightedSource.value = await codeToHtml(text, { lang: 'markdown', theme: shikiTheme.value });
    } catch {
      highlightedSource.value = '';
    }
  } catch (err) {
    console.error(err);
    error.value = t.value('markdown.load_failed');
    loading.value = false;
  }
};

const COPY_SVG_SM = `<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>`;
const COPY_SVG_MD = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>`;
const CHECK_SVG_SM = `<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg>`;
const CHECK_SVG_MD = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg>`;

const createCopyButton = (code: string, inline: boolean): HTMLButtonElement => {
  const btn = document.createElement('button');
  btn.type = 'button';
  btn.className = inline ? 'code-copy-btn' : 'code-copy-btn code-copy-float';
  btn.title = t.value('markdown.copy_code');
  btn.innerHTML = inline ? COPY_SVG_SM : COPY_SVG_MD;
  btn.addEventListener('click', async (e) => {
    e.stopPropagation();
    try {
      await navigator.clipboard.writeText(code);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = code;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
    }
    btn.innerHTML = inline ? CHECK_SVG_SM : CHECK_SVG_MD;
    btn.title = t.value('markdown.copied');
    setTimeout(() => {
      btn.innerHTML = inline ? COPY_SVG_SM : COPY_SVG_MD;
      btn.title = t.value('markdown.copy_code');
    }, 2000);
  });
  return btn;
};

const highlightAndInjectCopyButtons = async () => {
  if (!containerRef.value) return;

  // 1. shiki 高亮有语言的代码块
  const pending = containerRef.value.querySelectorAll<HTMLPreElement>('pre[data-shiki-pending="1"]');
  for (const pre of pending) {
    const lang = pre.getAttribute('data-lang') || 'text';
    const code = pre.querySelector('code')?.textContent || '';
    try {
      const highlighted = await codeToHtml(code, { lang, theme: shikiTheme.value });
      const tmp = document.createElement('div');
      tmp.innerHTML = highlighted;
      const newPre = tmp.firstElementChild as HTMLElement;
      if (newPre) pre.replaceWith(newPre);
    } catch {
      pre.style.backgroundColor = 'var(--fp-code-bg)';
      pre.removeAttribute('data-shiki-pending');
    }
  }

  // 2. 为所有代码块注入复制按钮（避免重复注入）
  const wrappers = containerRef.value.querySelectorAll<HTMLElement>('.code-block-wrapper');
  for (const wrapper of wrappers) {
    if (wrapper.querySelector('.code-copy-btn')) continue;
    const header = wrapper.querySelector('.code-block-header');
    const pre = wrapper.querySelector('pre');
    const code = pre?.querySelector('code')?.textContent ?? pre?.textContent ?? '';
    if (header) {
      // 有语言：按钮放入 header 右侧
      header.appendChild(createCopyButton(code, true));
    } else {
      // 无语言：浮动按钮
      wrapper.appendChild(createCopyButton(code, false));
    }
  }
};

watch(() => props.url, loadMarkdown, { immediate: true });

watch(html, async () => {
  if (!html.value) return;
  await nextTick();
  highlightAndInjectCopyButtons();
});

// 主题切换时重新加载（让 shiki 用新主题重新高亮）
watch(shikiTheme, () => {
  if (content.value) loadMarkdown();
});
</script>

<template>
  <div v-if="loading" class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full">
    <div
      class="vfp-w-12 vfp-h-12 vfp-border-4 vfp-border-line-strong vfp-border-t-spinner-head vfp-rounded-full vfp-animate-spin"
    />
  </div>

  <div v-else-if="error" class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full">
    <div class="vfp-text-fg-secondary vfp-text-center">
      <p class="vfp-text-lg">{{ error }}</p>
    </div>
  </div>

  <!-- 源码视图 -->
  <div v-else-if="viewMode === 'source'" class="vfp-w-full vfp-h-full vfp-overflow-auto" style="background: var(--fp-code-bg);">
    <pre
      v-if="!highlightedSource"
      class="vfp-p-6 vfp-text-fg-primary vfp-font-mono vfp-text-sm vfp-whitespace-pre-wrap vfp-break-words"
      >{{ content }}</pre
    >
    <div v-else class="shiki-wrapper" v-html="highlightedSource" />
  </div>

  <!-- 预览视图 -->
  <div v-else class="vfp-w-full vfp-h-full vfp-overflow-auto vfp-p-6 md:vfp-p-10">
    <div class="vfp-max-w-full md:vfp-max-w-4xl vfp-mx-auto">
      <div ref="containerRef" class="markdown-body" v-html="html" />
    </div>
  </div>
</template>

<style scoped>
.markdown-body :deep(.table-wrapper) {
  overflow-x: auto;
  margin: 1rem 0;
  border-radius: 0.375rem;
  border: 1px solid var(--fp-surface-3);
}
.markdown-body :deep(.table-wrapper > table) {
  margin: 0;
  border: 0;
  border-radius: 0;
}
/* shiki 生成的 pre：修正在 code-block-wrapper 内的边距与圆角 */
.markdown-body :deep(.code-block-wrapper pre.shiki) {
  margin: 0;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
  border-top: 0;
}
/* 无语言代码块：pre 不裁剪，让浮动按钮可见 */
.markdown-body :deep(.code-block-wrapper) {
  overflow: visible;
}
.markdown-body :deep(.code-block-wrapper pre) {
  overflow: visible;
}
/* 无语言代码块纯文本样式 */
.markdown-body :deep(.no-lang-pre) {
  margin: 0;
  padding: 1rem;
  background: var(--fp-code-bg);
  border-radius: 0.375rem;
  border: 1px solid var(--fp-line);
}
.markdown-body :deep(.no-lang-pre code) {
  display: block;
  font-size: 0.8125rem;
  line-height: 1.5;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  color: var(--fp-fg-primary);
  white-space: pre;
  overflow-x: auto;
}
/* shiki 生成的 code：补充 padding，使代码有适当内边距 */
.markdown-body :deep(pre.shiki code) {
  display: block;
  padding: 1rem;
  font-size: 0.8125rem;
  line-height: 1.5;
  overflow-x: auto;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
}
/* KaTeX 公式颜色适配暗色背景 */
.markdown-body :deep(.katex) {
  color: var(--fp-fg-primary);
}
.markdown-body :deep(.katex-display) {
  margin: 1.25rem 0;
  overflow-x: auto;
  overflow-y: hidden;
}
/* 源码视图 shiki */
.shiki-wrapper :deep(pre) {
  margin: 0;
  padding: 1.5rem;
  background: transparent !important;
  font-size: 0.875rem;
  overflow-x: auto;
}
.shiki-wrapper :deep(code) {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
}
</style>

// packages/react-file-preview/src/renderers/Markdown/index.tsx
import { useState, useEffect, useCallback } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import rehypeRaw from 'rehype-raw';
import { Copy, Check } from 'lucide-react';
import { fetchTextUtf8 } from '@eternalheart/file-preview-core';
import { useTranslator } from '../../i18n/LocaleContext';
import { useShikiHighlight } from '../../hooks/useShikiHighlight';
import 'katex/dist/katex.min.css';

interface MarkdownRendererProps {
  url: string;
  viewMode?: 'preview' | 'source';
}

const useCopy = (text: string) => {
  const [copied, setCopied] = useState(false);
  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [text]);
  return { copied, handleCopy };
};

/** 内联版复制按钮：放在代码块 header 行内，始终可见 */
const InlineCopyButton = ({ text }: { text: string }) => {
  const t = useTranslator();
  const { copied, handleCopy } = useCopy(text);
  return (
    <button
      onClick={handleCopy}
      className="rfp-p-1 rfp-rounded rfp-text-fg-muted hover:rfp-text-fg-secondary rfp-transition-colors rfp-flex rfp-items-center rfp-gap-1"
      title={copied ? t('markdown.copied') : t('markdown.copy_code')}
    >
      {copied ? <Check size={13} /> : <Copy size={13} />}
    </button>
  );
};

/** 浮动版复制按钮：无 header 时绝对定位于代码块右上角（hover 显示） */
const FloatingCopyButton = ({ text }: { text: string }) => {
  const t = useTranslator();
  const { copied, handleCopy } = useCopy(text);
  return (
    <button
      onClick={handleCopy}
      className="rfp-absolute rfp-top-2 rfp-right-2 rfp-p-1.5 rfp-rounded-md rfp-bg-surface-2 hover:rfp-bg-surface-3 rfp-text-fg-tertiary hover:rfp-text-fg-secondary rfp-transition-colors rfp-opacity-0 group-hover:rfp-opacity-100 rfp-border rfp-border-line"
      title={copied ? t('markdown.copied') : t('markdown.copy_code')}
    >
      {copied ? <Check size={14} /> : <Copy size={14} />}
    </button>
  );
};

/** 带语言标注的代码块：shiki 高亮 + header + 复制按钮 */
const ShikiCodeBlock = ({ code, lang }: { code: string; lang: string }) => {
  const { html } = useShikiHighlight(code, lang);
  return (
    <div className="rfp-relative rfp-group rfp-my-4">
      <div className="rfp-flex rfp-items-center rfp-justify-between rfp-px-4 rfp-py-1.5 rfp-bg-surface-1 rfp-border rfp-border-line-weak rfp-rounded-t-md rfp-border-b-0">
        <span className="rfp-text-xs rfp-text-fg-secondary rfp-font-mono rfp-select-none">{lang}</span>
        <InlineCopyButton text={code} />
      </div>
      {html ? (
        <div
          className="rfp-shiki-wrapper rfp-rounded-b-md rfp-border rfp-border-line-weak rfp-border-t-0 rfp-overflow-x-auto"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      ) : (
        <pre
          className="rfp-m-0 rfp-rounded-b-md rfp-border rfp-border-line-weak rfp-border-t-0 rfp-overflow-x-auto rfp-p-4 rfp-bg-code-bg"
          style={{ fontSize: '13px', lineHeight: '1.5' }}
        >
          <code className="rfp-font-mono rfp-text-code-fg rfp-text-sm">{code}</code>
        </pre>
      )}
    </div>
  );
};

export const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({ url, viewMode = 'preview' }) => {
  const t = useTranslator();
  const [content, setContent] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const { html: sourceHtml } = useShikiHighlight(
    viewMode === 'source' ? content : '',
    'markdown',
  );

  useEffect(() => {
    const loadMarkdown = async () => {
      try {
        setLoading(true);
        setError(null);
        const text = await fetchTextUtf8(url);
        setContent(text);
      } catch (err) {
        setError(t('markdown.load_failed'));
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    loadMarkdown();
  }, [url]);

  if (loading) {
    return (
      <div className="rfp-flex rfp-items-center rfp-justify-center rfp-w-full rfp-h-full">
        <div className="rfp-w-12 rfp-h-12 rfp-border-4 rfp-border-line-strong rfp-border-t-spinner-head rfp-rounded-full rfp-animate-spin" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="rfp-flex rfp-items-center rfp-justify-center rfp-w-full rfp-h-full">
        <div className="rfp-text-fg-secondary rfp-text-center">
          <p className="rfp-text-lg">{error}</p>
        </div>
      </div>
    );
  }

  // 源码视图
  if (viewMode === 'source') {
    return (
      <div className="rfp-w-full rfp-h-full rfp-overflow-auto rfp-bg-code-bg">
        {sourceHtml ? (
          <div
            className="rfp-shiki-wrapper with-line-numbers"
            dangerouslySetInnerHTML={{ __html: sourceHtml }}
          />
        ) : (
          <pre className="rfp-p-6 rfp-text-fg-primary rfp-font-mono rfp-text-sm rfp-whitespace-pre-wrap rfp-break-words">
            {content}
          </pre>
        )}
      </div>
    );
  }

  // 预览视图
  return (
    <div className="rfp-w-full rfp-h-full rfp-overflow-auto rfp-p-6 md:rfp-p-10">
      <div className="rfp-max-w-full md:rfp-max-w-4xl rfp-mx-auto">
        <ReactMarkdown
            remarkPlugins={[remarkGfm, remarkMath]}
            rehypePlugins={[rehypeRaw, rehypeKatex]}
            components={{
              code({ node, inline, className, children, ...props }: any) {
                const match = /language-(\w+)/.exec(className || '');
                const codeString = String(children).replace(/\n$/, '');
                if (!inline && match) {
                  // 有语言标注的代码块 - shiki 高亮
                  return <ShikiCodeBlock code={codeString} lang={match[1]} />;
                }
                if (!inline) {
                  // 无语言标注的代码块 - 纯文本暗色显示
                  return (
                    <div className="rfp-relative rfp-group rfp-my-4">
                      <FloatingCopyButton text={codeString} />
                      <pre
                        className="rfp-m-0 rfp-rounded-md rfp-border rfp-border-line-weak rfp-overflow-x-auto rfp-p-4 rfp-bg-code-bg"
                        style={{ fontSize: '13px', lineHeight: '1.5' }}
                      >
                        <code className="rfp-font-mono rfp-text-code-fg rfp-text-sm">{children}</code>
                      </pre>
                    </div>
                  );
                }
                // 行内代码
                return (
                  <code
                    className="rfp-bg-surface-2 rfp-px-1.5 rfp-py-0.5 rfp-rounded rfp-text-sm rfp-font-mono rfp-text-fg-primary rfp-border rfp-border-line-weak"
                    {...props}
                  >
                    {children}
                  </code>
                );
              },
              h1: ({ children }) => (
                <h1 className="rfp-text-3xl rfp-font-semibold rfp-mb-4 rfp-mt-6 rfp-text-fg-primary first:rfp-mt-0">
                  {children}
                </h1>
              ),
              h2: ({ children }) => (
                <h2 className="rfp-text-2xl rfp-font-semibold rfp-mb-3 rfp-mt-8 rfp-text-fg-primary">
                  {children}
                </h2>
              ),
              h3: ({ children }) => (
                <h3 className="rfp-text-xl rfp-font-semibold rfp-mb-2 rfp-mt-6 rfp-text-fg-primary">{children}</h3>
              ),
              h4: ({ children }) => (
                <h4 className="rfp-text-lg rfp-font-semibold rfp-mb-2 rfp-mt-4 rfp-text-fg-primary">{children}</h4>
              ),
              p: ({ children }) => (
                <p className="rfp-text-fg-secondary rfp-mb-4 rfp-leading-7 rfp-text-base">{children}</p>
              ),
              a: ({ href, children }) => (
                <a
                  href={href}
                  className="rfp-text-indigo-400 hover:rfp-text-indigo-300 rfp-underline rfp-decoration-indigo-600 hover:rfp-decoration-indigo-400"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {children}
                </a>
              ),
              ul: ({ children }) => (
                <ul className="rfp-list-disc rfp-pl-6 rfp-mb-4 rfp-text-fg-secondary rfp-space-y-1">{children}</ul>
              ),
              ol: ({ children }) => (
                <ol className="rfp-list-decimal rfp-pl-6 rfp-mb-4 rfp-text-fg-secondary rfp-space-y-1">{children}</ol>
              ),
              li: ({ children }) => <li className="rfp-leading-7">{children}</li>,
              blockquote: ({ children }) => (
                <blockquote className="rfp-border-l-4 rfp-border-line-strong rfp-pl-4 rfp-text-fg-tertiary rfp-my-4 rfp-italic">
                  {children}
                </blockquote>
              ),
              table: ({ children }) => (
                <div className="rfp-overflow-x-auto rfp-my-4 rfp-rounded-md rfp-border rfp-border-line">
                  <table className="rfp-min-w-full rfp-divide-y rfp-divide-divide">{children}</table>
                </div>
              ),
              thead: ({ children }) => <thead className="rfp-bg-surface-1">{children}</thead>,
              tbody: ({ children }) => (
                <tbody className="rfp-divide-y rfp-divide-divide rfp-bg-transparent">{children}</tbody>
              ),
              tr: ({ children }) => (
                <tr className="hover:rfp-bg-surface-1 rfp-transition-colors">{children}</tr>
              ),
              th: ({ children }) => (
                <th className="rfp-px-4 rfp-py-3 rfp-text-left rfp-text-xs rfp-font-semibold rfp-text-fg-tertiary rfp-uppercase rfp-tracking-wider">
                  {children}
                </th>
              ),
              td: ({ children }) => (
                <td className="rfp-px-4 rfp-py-3 rfp-text-sm rfp-text-fg-secondary">{children}</td>
              ),
              hr: () => <hr className="rfp-border-line rfp-my-6" />,
              img: ({ src, alt }) => (
                <img
                  src={src}
                  alt={alt}
                  className="rfp-rounded-md rfp-max-w-full rfp-h-auto rfp-my-4 rfp-mx-auto rfp-block rfp-shadow-sm"
                />
              ),
              input: ({ type, checked, ...props }) => {
                if (type === 'checkbox') {
                  return (
                    <input
                      type="checkbox"
                      checked={checked}
                      readOnly
                      className="rfp-mr-2 rfp-rounded rfp-border-line"
                      {...props}
                    />
                  );
                }
                return <input type={type} {...props} />;
              },
              strong: ({ children }) => (
                <strong className="rfp-font-semibold rfp-text-fg-primary">{children}</strong>
              ),
              em: ({ children }) => <em className="rfp-italic">{children}</em>,
              del: ({ children }) => (
                <del className="rfp-text-fg-muted rfp-line-through">{children}</del>
              ),
            }}
          >
            {content}
          </ReactMarkdown>
      </div>
    </div>
  );
};
