// packages/angular-file-preview/src/renderers/renderer-loading.component.ts
import { Component } from '@angular/core';
import { injectTranslator } from '../inject/translator';

@Component({
  selector: 'afp-renderer-loading',
  standalone: true,
  template: `
    <div class="afp-flex afp-items-center afp-justify-center afp-w-full afp-h-full afp-text-fg-muted">
      <div class="afp-flex afp-flex-col afp-items-center afp-gap-3">
        <div class="afp-w-8 afp-h-8 afp-rounded-full afp-border-2 afp-border-fg-muted afp-border-t-transparent afp-animate-spin"></div>
        <span class="afp-text-sm">{{ t('common.loading') || 'Loading...' }}</span>
      </div>
    </div>
  `,
})
export class RendererLoadingComponent {
  private readonly translator = injectTranslator();
  readonly t = this.translator.t;
}

// packages/vue-file-preview/src/renderers/RendererLoading.vue
<script setup lang="ts">
import { useTranslator } from '../composables/useTranslator';
const { t } = useTranslator();
</script>

<template>
  <div class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full vfp-text-fg-muted">
    <div class="vfp-flex vfp-flex-col vfp-items-center vfp-gap-3">
      <div class="vfp-w-8 vfp-h-8 vfp-rounded-full vfp-border-2 vfp-border-fg-muted vfp-border-t-transparent vfp-animate-spin" />
      <span class="vfp-text-sm">{{ t('common.loading') || 'Loading...' }}</span>
    </div>
  </div>
</template>
