// packages/angular-file-preview/src/renderers/unsupported/unsupported-renderer.component.ts
import { Component, input, output } from '@angular/core';
import { LucideAngularModule, FileQuestion, Download } from 'lucide-angular';
import { injectTranslator } from '../../inject/translator';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';

@Component({
  selector: 'afp-unsupported-renderer',
  standalone: true,
  imports: [LucideAngularModule],
  template: `
    <div class="afp-flex afp-flex-col afp-items-center afp-justify-center afp-w-full afp-h-full afp-p-6 afp-gap-4">
      <div class="afp-w-20 afp-h-20 afp-rounded-full afp-bg-surface-2 afp-flex afp-items-center afp-justify-center">
        <lucide-icon [img]="fileQuestion" class="afp-w-10 afp-h-10 afp-text-fg-secondary" />
      </div>
      <div class="afp-text-fg-primary afp-text-center">
        <p class="afp-text-lg afp-font-medium afp-mb-2">{{ fileName() }}</p>
        <p class="afp-text-fg-secondary">{{ t('common.unsupported_preview', { type: fileType() }) }}</p>
      </div>
      <button
        type="button"
        class="afp-flex afp-items-center afp-gap-2 afp-px-4 afp-py-2 afp-bg-surface-2 hover:afp-bg-surface-3 afp-backdrop-blur-sm afp-rounded-lg afp-text-fg-primary afp-font-medium afp-transition-all"
        (click)="download.emit()"
      >
        <lucide-icon [img]="downloadIcon" class="afp-w-5 afp-h-5" />
        {{ t('common.download') }}
      </button>
    </div>
  `,
})
export class UnsupportedRendererComponent implements RendererHandle {
  readonly fileName = input.required<string>();
  readonly fileType = input.required<string>();
  readonly download = output<void>();

  readonly fileQuestion = FileQuestion;
  readonly downloadIcon = Download;

  private readonly translator = injectTranslator();
  readonly t = this.translator.t;

  getToolbarGroups(): ToolbarGroup[] {
    return [];
  }
}

// packages/vue-file-preview/src/renderers/UnsupportedRenderer.vue
<script setup lang="ts">
import { FileQuestion, Download } from 'lucide-vue-next';

defineProps<{
  fileName: string;
  fileType: string;
}>();

const emit = defineEmits<{
  (e: 'download'): void;
}>();
</script>

<template>
  <div
    class="vfp-flex vfp-flex-col vfp-items-center vfp-justify-center vfp-w-full vfp-h-full vfp-p-8 vfp-gap-6"
  >
    <div
      class="vfp-w-32 vfp-h-32 vfp-rounded-full vfp-bg-white/10 vfp-flex vfp-items-center vfp-justify-center"
    >
      <FileQuestion class="vfp-w-16 vfp-h-16 vfp-text-white/70" />
    </div>

    <div class="vfp-text-white vfp-text-center">
      <p class="vfp-text-xl vfp-font-medium vfp-mb-2">{{ fileName }}</p>
      <p class="vfp-text-white/70">不支持预览此文件类型 ({{ fileType }})</p>
    </div>

    <button
      class="vfp-flex vfp-items-center vfp-gap-2 vfp-px-6 vfp-py-3 vfp-bg-white/10 hover:vfp-bg-white/20 vfp-backdrop-blur-sm vfp-rounded-lg vfp-text-white vfp-font-medium vfp-transition-all"
      @click="emit('download')"
    >
      <Download class="vfp-w-5 vfp-h-5" />
      下载文件查看
    </button>
  </div>
</template>
