// packages/vue-file-preview/src/renderers/Msg/index.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import MsgReader from '@kenjiuno/msgreader';
import type { FieldsData } from '@kenjiuno/msgreader';
import { User, Users, Paperclip, Calendar, Mail, Tag, Clock, Hash } from 'lucide-vue-next';
import { useTranslator } from '../../composables/useTranslator';

const props = defineProps<{
  url: string;
}>();

const { t } = useTranslator();

const loading = ref(true);
const error = ref<string | null>(null);
const fields = ref<FieldsData | null>(null);

function formatRecipients(recipients: FieldsData[] | undefined, type: 'to' | 'cc' | 'bcc'): string {
  if (!recipients) return '';
  return recipients
    .filter((r) => r.recipType === type)
    .map((r) => {
      const name = r.name || '';
      const email = r.smtpAddress || r.email || '';
      if (name && email && name !== email) return `${name} <${email}>`;
      return name || email;
    })
    .filter(Boolean)
    .join('; ');
}

function formatDate(dateStr: string | undefined): string {
  if (!dateStr) return '';
  try {
    const date = new Date(dateStr);
    if (isNaN(date.getTime())) return dateStr;
    return date.toLocaleString();
  } catch {
    return dateStr;
  }
}

function decodeHtmlBody(f: FieldsData, emptyBodyText: string): string {
  if (f.bodyHtml) return f.bodyHtml;
  if (f.html) {
    try {
      const decoder = new TextDecoder('utf-8');
      return decoder.decode(f.html);
    } catch {
      // fallback
    }
  }
  if (f.body) {
    return `<pre style="white-space: pre-wrap; word-wrap: break-word; font-family: system-ui, sans-serif;">${f.body
      .replace(/&/g, '&amp;')
      .replace(/\x3c/g, '&lt;')
      .replace(/>/g, '&gt;')}</pre>`;
  }
  return `<p style="color: #999;">${emptyBodyText}</p>`;
}

function formatMessageClass(messageClass: string | undefined): string {
  if (!messageClass) return '';
  const classMap: Record<string, string> = {
    'IPM.Note': 'Email',
    'IPM.Note.SMIME': 'Encrypted Email',
    'IPM.Note.SMIME.MultipartSigned': 'Signed Email',
    'IPM.Appointment': 'Appointment',
    'IPM.Schedule.Meeting.Request': 'Meeting Request',
    'IPM.Schedule.Meeting.Canceled': 'Meeting Cancellation',
    'IPM.Contact': 'Contact',
    'IPM.Task': 'Task',
    'IPM.StickyNote': 'Sticky Note',
  };
  return classMap[messageClass] || messageClass;
}

const loadMsg = async () => {
  loading.value = true;
  error.value = null;
  fields.value = null;

  try {
    const response = await fetch(props.url);
    if (!response.ok) throw new Error('文件加载失败');
    const arrayBuffer = await response.arrayBuffer();
    const msgReader = new MsgReader(arrayBuffer);
    fields.value = msgReader.getFileData();
  } catch (err) {
    console.error('MSG 解析错误:', err);
    error.value = t.value('msg.parse_failed');
  } finally {
    loading.value = false;
  }
};

watch(() => props.url, loadMsg, { immediate: true });

const subject = computed(() => fields.value?.subject || '（无主题）');
const sender = computed(() => {
  if (!fields.value) return '';
  const senderName = fields.value.senderName || '';
  const senderEmail = fields.value.senderSmtpAddress || fields.value.senderEmail || '';
  if (senderName && senderEmail && senderName !== senderEmail) {
    return `${senderName} <${senderEmail}>`;
  }
  return senderName || senderEmail;
});
const toStr = computed(() => formatRecipients(fields.value?.recipients, 'to'));
const ccStr = computed(() => formatRecipients(fields.value?.recipients, 'cc'));
const bccStr = computed(() => formatRecipients(fields.value?.recipients, 'bcc'));
const sentDate = computed(() => formatDate(fields.value?.clientSubmitTime));
const receivedDate = computed(() => formatDate(fields.value?.messageDeliveryTime));
const createdDate = computed(() => formatDate(fields.value?.creationTime));
const lastModified = computed(() => formatDate(fields.value?.lastModificationTime));
const attachments = computed(() => (fields.value?.attachments || []).filter((a) => !a.attachmentHidden));
const bodyHtml = computed(() => (fields.value ? decodeHtmlBody(fields.value, t.value('msg.empty_body')) : ''));
const messageClass = computed(() => formatMessageClass(fields.value?.messageClass));
const messageId = computed(() => fields.value?.messageId || '');

const importance = computed(() => {
  const f = fields.value as (FieldsData & Record<string, unknown>) | null;
  return f && typeof f.importance === 'number' ? f.importance : undefined;
});
const importanceLabel = computed(() => {
  if (importance.value === 2) return 'High';
  if (importance.value === 0) return 'Low';
  return '';
});

const sensitivity = computed(() => {
  const f = fields.value as (FieldsData & Record<string, unknown>) | null;
  return f && typeof f.sensitivity === 'number' ? f.sensitivity : undefined;
});
const sensitivityLabel = computed(() => {
  if (sensitivity.value === undefined || sensitivity.value === 0) return '';
  const labels: Record<number, string> = {
    1: 'Personal',
    2: 'Private',
    3: 'Confidential',
  };
  return labels[sensitivity.value] || '';
});

const formatAttachmentSize = (size: number | undefined) => {
  if (!size) return '';
  if (size > 1048576) return `${(size / 1048576).toFixed(1)} MB`;
  if (size > 1024) return `${(size / 1024).toFixed(0)} KB`;
  return `${size} B`;
};
</script>

<template>
  <div v-if="loading" class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full">
    <div
      class="vfp-w-12 vfp-h-12 vfp-border-4 vfp-border-line-strong vfp-border-t-spinner-head vfp-rounded-full vfp-animate-spin"
    />
  </div>

  <div v-else-if="error || !fields" class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full">
    <div class="vfp-text-fg-secondary vfp-text-center">
      <p class="vfp-text-lg">{{ error || t('msg.parse_failed_short') }}</p>
    </div>
  </div>

  <div v-else class="vfp-w-full vfp-h-full vfp-overflow-auto" style="background: white">
    <div class="msg-container">
      <!-- 邮件头部 -->
      <div class="msg-header">
        <h2 class="msg-subject">{{ subject }}</h2>

        <div class="msg-meta">
          <div v-if="sender" class="msg-row">
            <span class="msg-icon-wrap"><User :size="16" class="msg-icon" /></span>
            <div class="msg-row-content"><span class="msg-label">From</span><span class="msg-value">{{ sender }}</span></div>
          </div>

          <div v-if="toStr" class="msg-row">
            <span class="msg-icon-wrap"><Users :size="16" class="msg-icon" /></span>
            <div class="msg-row-content"><span class="msg-label">To</span><span class="msg-value">{{ toStr }}</span></div>
          </div>

          <div v-if="ccStr" class="msg-row">
            <span class="msg-icon-wrap"><Users :size="16" class="msg-icon" /></span>
            <div class="msg-row-content"><span class="msg-label">Cc</span><span class="msg-value">{{ ccStr }}</span></div>
          </div>

          <div v-if="bccStr" class="msg-row">
            <span class="msg-icon-wrap"><Users :size="16" class="msg-icon" /></span>
            <div class="msg-row-content"><span class="msg-label">Bcc</span><span class="msg-value">{{ bccStr }}</span></div>
          </div>

          <div v-if="sentDate" class="msg-row">
            <span class="msg-icon-wrap"><Calendar :size="16" class="msg-icon" /></span>
            <div class="msg-row-content"><span class="msg-label">Sent</span><span class="msg-value">{{ sentDate }}</span></div>
          </div>

          <div v-if="receivedDate && receivedDate !== sentDate" class="msg-row">
            <span class="msg-icon-wrap"><Clock :size="16" class="msg-icon" /></span>
            <div class="msg-row-content"><span class="msg-label">Received</span><span class="msg-value">{{ receivedDate }}</span></div>
          </div>

          <div v-if="!sentDate && !receivedDate && createdDate" class="msg-row">
            <span class="msg-icon-wrap"><Calendar :size="16" class="msg-icon" /></span>
            <div class="msg-row-content"><span class="msg-label">Date</span><span class="msg-value">{{ createdDate }}</span></div>
          </div>

          <div v-if="importanceLabel" class="msg-row">
            <span class="msg-icon-wrap"><Tag :size="16" class="msg-icon" /></span>
            <div class="msg-row-content">
              <span class="msg-label">Importance</span>
              <span class="msg-value" :style="{ color: importance === 2 ? '#dc2626' : '#2563eb', fontWeight: 500 }">
                {{ importanceLabel }}
              </span>
            </div>
          </div>

          <div v-if="sensitivityLabel" class="msg-row">
            <span class="msg-icon-wrap"><Tag :size="16" class="msg-icon" /></span>
            <div class="msg-row-content"><span class="msg-label">Sensitivity</span><span class="msg-value">{{ sensitivityLabel }}</span></div>
          </div>

          <div v-if="messageClass && messageClass !== 'Email'" class="msg-row">
            <span class="msg-icon-wrap"><Mail :size="16" class="msg-icon" /></span>
            <div class="msg-row-content"><span class="msg-label">Type</span><span class="msg-value">{{ messageClass }}</span></div>
          </div>

          <div v-if="attachments.length > 0" class="msg-row msg-row-bordered">
            <span class="msg-icon-wrap"><Paperclip :size="16" class="msg-icon" /></span>
            <div class="msg-row-content">
              <span class="msg-label">Attachments</span>
              <div class="msg-value msg-attachments">
                <span v-for="(a, i) in attachments" :key="i" class="msg-attachment">
                  {{ a.fileName || a.name || '未知文件' }}
                  <span v-if="formatAttachmentSize(a.contentLength)" class="msg-attachment-size">
                    ({{ formatAttachmentSize(a.contentLength) }})
                  </span>
                </span>
              </div>
            </div>
          </div>

          <div v-if="messageId" class="msg-row" :class="{ 'msg-row-bordered': attachments.length === 0 }">
            <span class="msg-icon-wrap"><Hash :size="16" class="msg-icon" /></span>
            <div class="msg-row-content">
              <span class="msg-label">Message-ID</span>
              <span class="msg-value msg-id">{{ messageId }}</span>
            </div>
          </div>

          <div v-if="lastModified && lastModified !== sentDate && lastModified !== receivedDate" class="msg-row">
            <span class="msg-icon-wrap"><Clock :size="16" class="msg-icon" /></span>
            <div class="msg-row-content">
              <span class="msg-label">Modified</span>
              <span class="msg-value msg-id">{{ lastModified }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- 邮件正文 -->
      <div class="msg-body" v-html="bodyHtml" />
    </div>
  </div>
</template>

<style scoped>
.msg-container {
  width: 100%;
  background: white;
  min-height: 100%;
}
.msg-header {
  border-bottom: 1px solid #e5e7eb;
  padding: clamp(12px, 3vw, 24px) clamp(16px, 3vw, 28px);
  background: #f9fafb;
}
.msg-subject {
  margin: 0 0 16px 0;
  font-size: clamp(16px, 2.5vw, 20px);
  font-weight: 600;
  color: #111827;
  line-height: 1.4;
}
.msg-meta {
  display: flex;
  flex-direction: column;
  font-size: clamp(12px, 1.8vw, 14px);
  color: #4b5563;
}
.msg-row {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  padding: 6px 0;
}
.msg-row-bordered {
  border-top: 1px solid #e5e7eb;
  margin-top: 4px;
  padding-top: 10px;
}
.msg-icon-wrap {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  height: 1.4em;
}
.msg-icon {
  flex-shrink: 0;
  color: #9ca3af;
}
.msg-row-content {
  display: flex;
  flex: 1;
}
.msg-label {
  flex-shrink: 0;
  color: #6b7280;
  font-weight: 500;
  margin-right: 8px;
  white-space: nowrap;
}
.msg-value {
  color: #111827;
  word-break: break-word;
  flex: 1;
}
.msg-id {
  font-size: 12px;
  color: #9ca3af;
  font-family: monospace;
}
.msg-attachments {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}
.msg-attachment {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 2px 8px;
  background: #f3f4f6;
  border-radius: 4px;
  font-size: 13px;
  color: #374151;
  border: 1px solid #e5e7eb;
}
.msg-attachment-size {
  color: #9ca3af;
  font-size: 12px;
}
.msg-body {
  padding: clamp(12px, 3vw, 24px) clamp(16px, 3vw, 28px);
  font-family: system-ui, -apple-system, sans-serif;
  line-height: 1.6;
  color: #333;
  overflow-x: auto;
}
</style>

// packages/react-file-preview/src/renderers/Msg/index.tsx
import { useState, useEffect } from 'react';
import MsgReader from '@kenjiuno/msgreader';
import type { FieldsData } from '@kenjiuno/msgreader';
import { User, Users, Paperclip, Calendar, Mail, Tag, Clock, Hash } from 'lucide-react';
import { useTranslator } from '../../i18n/LocaleContext';

interface MsgRendererProps {
  url: string;
}

function formatRecipients(recipients: FieldsData[] | undefined, type: 'to' | 'cc' | 'bcc'): string {
  if (!recipients) return '';
  return recipients
    .filter((r) => r.recipType === type)
    .map((r) => {
      const name = r.name || '';
      const email = r.smtpAddress || r.email || '';
      if (name && email && name !== email) {
        return `${name} <${email}>`;
      }
      return name || email;
    })
    .filter(Boolean)
    .join('; ');
}

function formatDate(dateStr: string | undefined): string {
  if (!dateStr) return '';
  try {
    const date = new Date(dateStr);
    if (isNaN(date.getTime())) return dateStr;
    return date.toLocaleString();
  } catch {
    return dateStr;
  }
}

function decodeHtmlBody(fields: FieldsData, emptyBodyText: string): string {
  // 优先使用 bodyHtml (string 类型)
  if (fields.bodyHtml) {
    return fields.bodyHtml;
  }
  // 其次尝试 html (Uint8Array 类型)
  if (fields.html) {
    try {
      const decoder = new TextDecoder('utf-8');
      return decoder.decode(fields.html);
    } catch {
      // fallback
    }
  }
  // 最后使用纯文本，转换为简单 HTML
  if (fields.body) {
    return `<pre style="white-space: pre-wrap; word-wrap: break-word; font-family: system-ui, sans-serif;">${fields.body.replace(/&/g, '&amp;').replace(/\x3c/g, '&lt;').replace(/>/g, '&gt;')
      }</pre>`;
  }
  return `<p style="color: #999;">${emptyBodyText}</p>`;
}

function formatMessageClass(messageClass: string | undefined): string {
  if (!messageClass) return '';
  const classMap: Record<string, string> = {
    'IPM.Note': 'Email',
    'IPM.Note.SMIME': 'Encrypted Email',
    'IPM.Note.SMIME.MultipartSigned': 'Signed Email',
    'IPM.Appointment': 'Appointment',
    'IPM.Schedule.Meeting.Request': 'Meeting Request',
    'IPM.Schedule.Meeting.Canceled': 'Meeting Cancellation',
    'IPM.Contact': 'Contact',
    'IPM.Task': 'Task',
    'IPM.StickyNote': 'Sticky Note',
  };
  return classMap[messageClass] || messageClass;
}

const labelStyle: React.CSSProperties = {
  flexShrink: 0,
  color: '#6b7280',
  fontWeight: 500,
  marginRight: '8px',
  whiteSpace: 'nowrap',
};

const rowStyle: React.CSSProperties = {
  display: 'flex',
  alignItems: 'flex-start',
  gap: '8px',
  padding: '6px 0',
};

const iconWrapStyle: React.CSSProperties = {
  flexShrink: 0,
  display: 'flex',
  alignItems: 'center',
  height: '1.4em',
};

const iconStyle: React.CSSProperties = {
  flexShrink: 0,
  color: '#9ca3af',
};

const valueStyle: React.CSSProperties = {
  color: '#111827',
  wordBreak: 'break-word' as const,
  flex: 1,
};

export const MsgRenderer: React.FC<MsgRendererProps> = ({ url }) => {
  const t = useTranslator();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [fields, setFields] = useState<FieldsData | null>(null);

  useEffect(() => {
    const loadMsg = async () => {
      setLoading(true);
      setError(null);
      setFields(null);

      try {
        const response = await fetch(url);
        if (!response.ok) {
          throw new Error('文件加载失败');
        }

        const arrayBuffer = await response.arrayBuffer();
        const msgReader = new MsgReader(arrayBuffer);
        const fileData = msgReader.getFileData();
        setFields(fileData);
      } catch (err) {
        console.error('MSG 解析错误:', err);
        setError(t('msg.parse_failed'));
      } finally {
        setLoading(false);
      }
    };

    loadMsg();
  }, [url]);

  if (loading) {
    return (
      <div className="rfp-flex rfp-items-center rfp-justify-center rfp-w-full rfp-h-full">
        <div className="rfp-w-12 rfp-h-12 rfp-border-4 rfp-border-line-strong rfp-border-t-spinner-head rfp-rounded-full rfp-animate-spin" />
      </div>
    );
  }

  if (error || !fields) {
    return (
      <div className="rfp-flex rfp-items-center rfp-justify-center rfp-w-full rfp-h-full">
        <div className="rfp-text-fg-secondary rfp-text-center">
          <p className="rfp-text-lg">{error || t('msg.parse_failed_short')}</p>
        </div>
      </div>
    );
  }

  const toStr = formatRecipients(fields.recipients, 'to');
  const ccStr = formatRecipients(fields.recipients, 'cc');
  const bccStr = formatRecipients(fields.recipients, 'bcc');
  const senderName = fields.senderName || '';
  const senderEmail = fields.senderSmtpAddress || fields.senderEmail || '';
  const sender = senderName && senderEmail && senderName !== senderEmail
    ? `${senderName} <${senderEmail}>`
    : senderName || senderEmail;
  const sentDate = formatDate(fields.clientSubmitTime);
  const receivedDate = formatDate(fields.messageDeliveryTime);
  const createdDate = formatDate(fields.creationTime);
  const lastModified = formatDate(fields.lastModificationTime);
  const subject = fields.subject || '（无主题）';
  const attachments = (fields.attachments || []).filter((a) => !a.attachmentHidden);
  const bodyHtml = decodeHtmlBody(fields, t('msg.empty_body'));
  const messageClass = formatMessageClass(fields.messageClass);
  const messageId = fields.messageId || '';
  const fieldsAny = fields as FieldsData & Record<string, unknown>;
  const importance = typeof fieldsAny.importance === 'number' ? fieldsAny.importance : undefined;
  const importanceLabel = importance === 2 ? 'High' : importance === 0 ? 'Low' : '';
  const sensitivity = typeof fieldsAny.sensitivity === 'number' ? fieldsAny.sensitivity : undefined;
  const sensitivityLabels: Record<number, string> = {
    0: 'Normal',
    1: 'Personal',
    2: 'Private',
    3: 'Confidential',
  };
  const sensitivityLabel = sensitivity !== undefined && sensitivity !== 0 ? sensitivityLabels[sensitivity] || '' : '';

  return (
    <div
      className="rfp-w-full rfp-h-full rfp-overflow-auto"
      style={{ background: 'white' }}
    >
      <div
        style={{
          width: '100%',
          background: 'white',
          minHeight: '100%',
        }}
      >
        {/* 邮件头部 */}
        <div style={{ borderBottom: '1px solid #e5e7eb', padding: 'clamp(12px, 3vw, 24px) clamp(16px, 3vw, 28px)', background: '#f9fafb' }}>
          {/* 主题 */}
          <h2 style={{ margin: '0 0 16px 0', fontSize: 'clamp(16px, 2.5vw, 20px)', fontWeight: 600, color: '#111827', lineHeight: 1.4 }}>
            {subject}
          </h2>

          {/* 元信息 */}
          <div style={{ display: 'flex', flexDirection: 'column', fontSize: 'clamp(12px, 1.8vw, 14px)', color: '#4b5563' }}>
            {sender && (
              <div style={rowStyle}>
                <span style={iconWrapStyle}><User size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>From</span>
                  <span style={valueStyle}>{sender}</span>
                </div>
              </div>
            )}

            {toStr && (
              <div style={rowStyle}>
                <span style={iconWrapStyle}><Users size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>To</span>
                  <span style={valueStyle}>{toStr}</span>
                </div>
              </div>
            )}

            {ccStr && (
              <div style={rowStyle}>
                <span style={iconWrapStyle}><Users size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>Cc</span>
                  <span style={valueStyle}>{ccStr}</span>
                </div>
              </div>
            )}

            {bccStr && (
              <div style={rowStyle}>
                <span style={iconWrapStyle}><Users size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>Bcc</span>
                  <span style={valueStyle}>{bccStr}</span>
                </div>
              </div>
            )}

            {sentDate && (
              <div style={rowStyle}>
                <span style={iconWrapStyle}><Calendar size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>Sent</span>
                  <span style={valueStyle}>{sentDate}</span>
                </div>
              </div>
            )}

            {receivedDate && receivedDate !== sentDate && (
              <div style={rowStyle}>
                <span style={iconWrapStyle}><Clock size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>Received</span>
                  <span style={valueStyle}>{receivedDate}</span>
                </div>
              </div>
            )}

            {!sentDate && !receivedDate && createdDate && (
              <div style={rowStyle}>
                <span style={iconWrapStyle}><Calendar size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>Date</span>
                  <span style={valueStyle}>{createdDate}</span>
                </div>
              </div>
            )}

            {importanceLabel && (
              <div style={rowStyle}>
                <span style={iconWrapStyle}><Tag size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>Importance</span>
                  <span style={{
                    ...valueStyle,
                    color: importance === 2 ? '#dc2626' : '#2563eb',
                    fontWeight: 500,
                  }}>
                    {importanceLabel}
                  </span>
                </div>
              </div>
            )}

            {sensitivityLabel && (
              <div style={rowStyle}>
                <span style={iconWrapStyle}><Tag size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>Sensitivity</span>
                  <span style={valueStyle}>{sensitivityLabel}</span>
                </div>
              </div>
            )}

            {messageClass && messageClass !== 'Email' && (
              <div style={rowStyle}>
                <span style={iconWrapStyle}><Mail size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>Type</span>
                  <span style={valueStyle}>{messageClass}</span>
                </div>
              </div>
            )}

            {attachments.length > 0 && (
              <div style={{ ...rowStyle, borderTop: '1px solid #e5e7eb', marginTop: '4px', paddingTop: '10px' }}>
                <span style={iconWrapStyle}><Paperclip size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>Attachments</span>
                  <div style={{ ...valueStyle, display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                    {attachments.map((a, i) => {
                      const name = a.fileName || a.name || '未知文件';
                      const size = a.contentLength;
                      const sizeStr = size
                        ? size > 1048576
                          ? `${(size / 1048576).toFixed(1)} MB`
                          : size > 1024
                            ? `${(size / 1024).toFixed(0)} KB`
                            : `${size} B`
                        : '';
                      return (
                        <span
                          key={i}
                          style={{
                            display: 'inline-flex',
                            alignItems: 'center',
                            gap: '4px',
                            padding: '2px 8px',
                            background: '#f3f4f6',
                            borderRadius: '4px',
                            fontSize: '13px',
                            color: '#374151',
                            border: '1px solid #e5e7eb',
                          }}
                        >
                          {name}
                          {sizeStr && (
                            <span style={{ color: '#9ca3af', fontSize: '12px' }}>({sizeStr})</span>
                          )}
                        </span>
                      );
                    })}
                  </div>
                </div>
              </div>
            )}

            {messageId && (
              <div style={{ ...rowStyle, borderTop: attachments.length > 0 ? 'none' : '1px solid #e5e7eb', marginTop: '4px', paddingTop: '10px' }}>
                <span style={iconWrapStyle}><Hash size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>Message-ID</span>
                  <span style={{ ...valueStyle, fontSize: '12px', color: '#9ca3af', fontFamily: 'monospace' }}>{messageId}</span>
                </div>
              </div>
            )}

            {lastModified && lastModified !== sentDate && lastModified !== receivedDate && (
              <div style={rowStyle}>
                <span style={iconWrapStyle}><Clock size={16} style={iconStyle} /></span>
                <div style={{ display: 'flex', flex: 1 }}>
                  <span style={labelStyle}>Modified</span>
                  <span style={{ ...valueStyle, fontSize: '12px', color: '#9ca3af' }}>{lastModified}</span>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* 邮件正文 */}
        <div
          style={{
            padding: 'clamp(12px, 3vw, 24px) clamp(16px, 3vw, 28px)',
            fontFamily: 'system-ui, -apple-system, sans-serif',
            lineHeight: '1.6',
            color: '#333',
            overflowX: 'auto',
          }}
          dangerouslySetInnerHTML={{ __html: bodyHtml }}
        />
      </div>
    </div>
  );
};
