// packages/vue-file-preview/src/renderers/Ppt/index.vue
<script setup lang="ts">
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';
import { ref, watch } from 'vue';
import { renderLegacyPptHtml } from '@eternalheart/file-preview-core';
import { useTranslator } from '../../composables/useTranslator';
import { useFetcher } from '../../composables/useRequest';
import RendererError from '../RendererError.vue';

const props = defineProps<{
  url: string;
}>();

const { t } = useTranslator();
const fetcher = useFetcher();

const html = ref('');
const loading = ref(true);
const error = ref<string | null>(null);

const loadPpt = async () => {
  loading.value = true;
  error.value = null;
  html.value = '';
  try {
    const response = await fetcher.value(props.url);
    if (!response.ok) throw new Error('load failed');
    const buffer = await response.arrayBuffer();
    html.value = await renderLegacyPptHtml(buffer);
  } catch (err) {
    console.error('Ppt 解析错误:', err);
    error.value = t.value('ppt.parse_failed');
  } finally {
    loading.value = false;
  }
};

watch(() => props.url, (newUrl) => {
  if (newUrl) void loadPpt();
}, { immediate: true });

const getToolbarGroups = (): ToolbarGroup[] => [];

defineExpose<RendererHandle>({
  getToolbarGroups,
});
</script>

<template>
  <div v-if="loading" class="vfp-flex vfp-items-center vfp-justify-center vfp-w-full vfp-h-full">
    <div
      class="vfp-w-12 vfp-h-12 vfp-border-4 vfp-border-line-strong vfp-border-t-spinner-head vfp-rounded-full vfp-animate-spin"
    />
  </div>

  <RendererError v-else-if="error" :message="error" />

  <div v-else class="vfp-w-full vfp-h-full vfp-overflow-auto vfp-py-6 vfp-px-4">
    <div class="vfp-legacy-ppt-wrap" v-html="html" />
  </div>
</template>

// packages/angular-file-preview/src/renderers/Ppt/index.ts
import {
  ChangeDetectionStrategy,
  Component,
  effect,
  inject,
  input,
  signal,
  untracked,
} from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { renderLegacyPptHtml } from '../../fp-core';
import { LocaleService, getFallbackTranslator } from '../../di/locale.service';
import { RequestService } from '../../di/request.service';
import { RendererError } from '../RendererError';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';

@Component({
  selector: 'afp-ppt-renderer',
  standalone: true,
  imports: [RendererError],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'afp-block afp-w-full afp-h-full' },
  template: `
    @if (loading()) {
      <div class="afp-flex afp-items-center afp-justify-center afp-w-full afp-h-full">
        <div
          class="afp-w-12 afp-h-12 afp-border-4 afp-border-line-strong afp-border-t-spinner-head afp-rounded-full afp-animate-spin"
        ></div>
      </div>
    } @else if (error()) {
      <afp-renderer-error [message]="error()!" />
    } @else {
      <div class="afp-w-full afp-h-full afp-overflow-auto afp-py-6 afp-px-4">
        <div class="afp-legacy-ppt-wrap" [innerHTML]="trust(html())"></div>
      </div>
    }
  `,
})
export class PptRenderer implements RendererHandle {
  url = input.required<string>();

  private readonly locale = inject(LocaleService, { optional: true });
  private readonly request = inject(RequestService, { optional: true });
  private readonly sanitizer = inject(DomSanitizer);
  private readonly t = this.locale?.t() ?? getFallbackTranslator();

  readonly html = signal('');
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);

  constructor() {
    effect(() => {
      const newUrl = this.url();
      if (newUrl) {
        untracked(() => {
          void this.loadPpt();
        });
      }
    });
  }

  getToolbarGroups = (): ToolbarGroup[] => [];

  protected trust(html: string) {
    return this.sanitizer.bypassSecurityTrustHtml(html);
  }

  private async loadPpt(): Promise<void> {
    this.loading.set(true);
    this.error.set(null);
    this.html.set('');

    try {
      const fetcher = this.request?.fetcher() ?? ((u: string, init?: RequestInit) => fetch(u, init));
      const response = await fetcher(this.url());
      if (!response.ok) throw new Error('load failed');
      const buffer = await response.arrayBuffer();
      this.html.set(await renderLegacyPptHtml(buffer));
    } catch (err) {
      console.error('Ppt 解析错误:', err);
      this.error.set(this.t('ppt.parse_failed'));
    } finally {
      this.loading.set(false);
    }
  }
}
