// packages/vue-file-preview/src/renderers/Mobi/index.vue
<script setup lang="ts">
import { ref, watch, onBeforeUnmount, defineComponent, h, type PropType } from 'vue';
import { X, ChevronLeft, ChevronRight, List, Maximize2, Minimize2 } from 'lucide-vue-next';
import 'foliate-js/view.js';
import { useTranslator } from '../../composables/useTranslator';
import { useFetcher } from '../../composables/useRequest';
import RendererError from '../RendererError.vue';
import { ToolbarEventEmitter } from '../base.types';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';

interface TocItem {
  label: string;
  href?: string;
  subitems?: TocItem[];
}

interface FoliateView extends HTMLElement {
  book: {
    sections: unknown[];
    toc?: TocItem[];
    destroy?: () => void;
  } | null;
  renderer: HTMLElement & {
    setStyles?: (css: string) => void;
    next?: () => Promise<void>;
    page?: number;
    pages?: number;
  };
  open(target: string | Blob | File | ArrayBuffer): Promise<void>;
  goTo(target: number | string): Promise<void>;
  prev(distance?: number): Promise<void>;
  next(distance?: number): Promise<void>;
}

const READER_CSS = `
  @namespace epub "http://www.idpf.org/2007/ops";
  html { color-scheme: light; }
  body {
    background: #ffffff !important;
    color: #1a1a1a !important;
    font-family: "Noto Serif SC", "Source Han Serif SC", Georgia, "Times New Roman", serif !important;
    font-size: 16px !important;
    line-height: 2 !important;
    max-width: 100% !important;
    box-sizing: border-box !important;
    word-break: break-word !important;
    overflow-wrap: break-word !important;
  }
  p, li, blockquote, dd { line-height: 2; text-align: justify; }
  p { text-indent: 2em; margin: 0.8em 0; }
  h1 { text-align: center; margin: 1.5em 0 1em; }
  h2 { margin: 1.2em 0 0.8em; }
  h3 { margin: 1em 0 0.6em; }
  img { max-width: 100% !important; height: auto !important; }
  a { color: #2563eb; text-decoration: none; }
  pre { white-space: pre-wrap !important; }
`;

const A4_WIDTH = 794;

const props = defineProps<{ url: string }>();

const emitter = new ToolbarEventEmitter();

const { t } = useTranslator();
const fetcher = useFetcher();

const hostRef = ref<HTMLDivElement | null>(null);
let viewInstance: FoliateView | null = null;
let totalLocations = 1;

// 内部状态
const currentChapter = ref(1);
const totalChapters = ref(1);

const loading = ref(true);
const error = ref<string | null>(null);
const toc = ref<TocItem[]>([]);
const showToc = ref(false);
const activeTocHref = ref('');
const isFullWidth = ref(false);

// 监听状态变化，通知工具栏更新（对齐 React：增加 toc.length 监听）
watch([currentChapter, totalChapters, isFullWidth, showToc, loading, () => toc.value.length], () => {
  emitter.notify();
});

const reportProgress = (current: number, total: number) => {
  if (total > 0) totalLocations = total;
  currentChapter.value = Math.max(1, current + 1);
  totalChapters.value = totalLocations;
};

const prevPage = () => { viewInstance?.prev().catch(() => {}); };
const nextPage = () => { viewInstance?.next().catch(() => {}); };
const toggleToc = () => { showToc.value = !showToc.value; };
const toggleFullWidth = () => {
  isFullWidth.value = !isFullWidth.value;
  if (viewInstance?.renderer) {
    viewInstance.renderer.setAttribute('max-inline-size', isFullWidth.value ? '9999' : '720');
  }
};

const handleTocClick = (href: string) => {
  activeTocHref.value = href;
  showToc.value = false;
  viewInstance?.goTo(href).catch(() => {});
};

// 工具栏配置（对齐 React：List 图标、disabled 代替条件、Minimize2/Maximize2 切换）
const getToolbarGroups = (): ToolbarGroup[] => [
  {
    items: [
      {
        type: 'button',
        icon: List,
        tooltip: t.value('toolbar.toc'),
        action: toggleToc,
        disabled: toc.value.length === 0,
        active: showToc.value,
      },
    ],
  },
  {
    items: [
      {
        type: 'button',
        icon: ChevronLeft,
        tooltip: t.value('toolbar.prev_page'),
        action: prevPage,
        disabled: currentChapter.value <= 1,
      },
      {
        type: 'text',
        content: `${currentChapter.value} / ${totalChapters.value}`,
        minWidth: '4rem',
      },
      {
        type: 'button',
        icon: ChevronRight,
        tooltip: t.value('toolbar.next_page'),
        action: nextPage,
        disabled: currentChapter.value >= totalChapters.value,
      },
    ],
  },
  {
    items: [
      {
        type: 'button',
        icon: isFullWidth.value ? Minimize2 : Maximize2,
        tooltip: isFullWidth.value ? t.value('toolbar.normal_width') : t.value('toolbar.full_width'),
        action: toggleFullWidth,
        active: isFullWidth.value,
      },
    ],
  },
];

defineExpose<RendererHandle>({
  getToolbarGroups,
  onToolbarChange: (listener) => emitter.subscribe(listener),
});

const load = async () => {
  const host = hostRef.value;
  if (!host) return;
  loading.value = true;
  error.value = null;
  toc.value = [];
  showToc.value = false;
  activeTocHref.value = '';
  host.replaceChildren();
  viewInstance = null;

  try {
    const view = document.createElement('foliate-view') as FoliateView;
    host.appendChild(view);
    viewInstance = view;

    // 先注册事件
    view.addEventListener('relocate', (e: Event) => {
      const detail = (e as CustomEvent).detail;
      if (!detail) return;
      const loc = detail.location as { current?: number; total?: number } | undefined;
      if (loc && typeof loc.current === 'number' && typeof loc.total === 'number') {
        reportProgress(loc.current, loc.total);
      } else {
        const sections = viewInstance?.book?.sections ?? [];
        const idx = detail.index ?? 0;
        const frac = detail.fraction ?? 0;
        const total = Math.max(sections.length, 1);
        reportProgress(Math.round((idx + frac) / total * total), total);
      }
      const tocItem = detail.tocItem as { href?: string } | undefined;
      if (tocItem?.href) activeTocHref.value = tocItem.href;
    });

    const res = await fetcher.value(props.url);
    if (!res.ok) throw new Error(`请求失败: ${res.status}`);
    const blob = await res.blob();
    let name = 'book.mobi';
    try {
      const u = new URL(props.url, window.location.href);
      const base = u.pathname.split('/').pop();
      if (base) name = decodeURIComponent(base);
    } catch { /* blob: URL */ }

    await view.open(new File([blob], name));

    // 配置 paginator：paginated 模式 + 动画
    const renderer = view.renderer;
    if (renderer) {
      renderer.setAttribute('animated', '');
      renderer.setAttribute('max-inline-size', '720');
      renderer.setAttribute('margin', '48');
      renderer.setAttribute('gap', '5%');
      renderer.setStyles?.(READER_CSS);
      await renderer.next?.();
    }

    toc.value = (view.book?.toc ?? []) as TocItem[];
    loading.value = false;
    reportProgress(0, view.book?.sections.length ?? 1);
  } catch (err) {
    console.error('MOBI/AZW3 加载错误:', err);
    error.value = t.value('mobi.load_failed');
    loading.value = false;
  }
};

watch(() => props.url, (newUrl) => {
  // 只有 URL 有效时才加载（避免空字符串或已 revoke 的 blob URL）
  if (newUrl) load();
}, { immediate: true });
onBeforeUnmount(() => {
  try { viewInstance?.book?.destroy?.(); } catch { /* ignore */ }
  viewInstance = null;
  hostRef.value?.replaceChildren();
});
</script>

<template>
  <div
    class="vfp-relative vfp-w-full vfp-h-full vfp-flex vfp-justify-center vfp-bg-surface-1 vfp-overflow-hidden"
  >
    <RendererError v-if="error" :message="error" class="vfp-absolute vfp-inset-0" />

    <div
      v-if="loading && !error"
      class="vfp-absolute vfp-inset-0 vfp-flex vfp-items-center vfp-justify-center vfp-z-10"
    >
      <div class="vfp-w-12 vfp-h-12 vfp-border-4 vfp-border-line-strong vfp-border-t-spinner-head vfp-rounded-full vfp-animate-spin" />
    </div>

    <!-- 目录侧栏 -->
    <div
      v-if="toc.length > 0"
      class="vfp-absolute vfp-inset-0 vfp-z-20 vfp-flex vfp-transition-opacity vfp-duration-300"
      :style="{ opacity: showToc ? 1 : 0, pointerEvents: showToc ? 'auto' : 'none' }"
    >
      <div
        class="vfp-w-72 vfp-max-w-[80%] vfp-h-full vfp-bg-surface-overlay vfp-backdrop-blur-xl vfp-border-r vfp-border-line-weak vfp-flex vfp-flex-col vfp-shadow-2xl vfp-transition-transform vfp-duration-300"
        :style="{ transform: showToc ? 'translateX(0)' : 'translateX(-100%)' }"
      >
        <div class="vfp-flex vfp-items-center vfp-justify-between vfp-px-4 vfp-py-3 vfp-border-b vfp-border-line-weak vfp-flex-shrink-0">
          <span class="vfp-text-fg-primary vfp-font-medium vfp-text-sm">{{ t('toolbar.toc') }}</span>
          <button class="toc-close-btn" @click="showToc = false">
            <X class="vfp-w-4 vfp-h-4" />
          </button>
        </div>
        <div class="vfp-flex-1 vfp-overflow-y-auto vfp-py-4 vfp-px-1">
          <MobiTocList :items="toc" :active-href="activeTocHref" @select="handleTocClick" />
        </div>
      </div>
      <div
        class="vfp-flex-1 vfp-transition-opacity vfp-duration-300"
        :style="{ background: showToc ? 'rgba(0,0,0,0.3)' : 'transparent' }"
        @click="showToc = false"
      />
    </div>

    <div
      v-if="!error"
      ref="hostRef"
      class="vfp-h-full vfp-bg-surface-toolbar vfp-shadow-lg"
      :style="{ width: isFullWidth ? '100%' : A4_WIDTH + 'px', maxWidth: '100%', transition: 'width 0.3s ease' }"
    />
  </div>
</template>

<script lang="ts">
interface TocItemLocal {
  label: string;
  href?: string;
  subitems?: TocItemLocal[];
}

const MobiTocList = defineComponent({
  name: 'MobiTocList',
  props: {
    items: { type: Array as PropType<TocItemLocal[]>, required: true },
    activeHref: { type: String, default: '' },
    depth: { type: Number, default: 0 },
  },
  emits: ['select'],
  render(): ReturnType<typeof h> {
    return h(
      'ul',
      { style: { listStyle: 'none', padding: 0, margin: this.depth > 0 ? '0 0 0 16px' : 0 } },
      this.items.map((item: TocItemLocal, i: number) =>
        h('li', { key: `${item.href ?? item.label}-${i}` }, [
          item.href
            ? h(
                'button',
                {
                  onClick: () => this.$emit('select', item.href),
                  class: [
                    'vfp-w-full vfp-text-left vfp-py-2 vfp-px-3 vfp-text-sm vfp-rounded vfp-transition-all vfp-truncate',
                    this.activeHref === item.href
                      ? 'vfp-text-fg-primary vfp-bg-surface-3 vfp-font-medium'
                      : 'vfp-text-fg-secondary hover:vfp-text-fg-primary hover:vfp-bg-surface-2',
                  ],
                  title: item.label,
                  style: 'background: none; border: none; cursor: pointer',
                },
                item.label?.trim()
              )
            : h(
                'div',
                { class: 'vfp-w-full vfp-py-2 vfp-px-3 vfp-text-sm vfp-text-fg-tertiary vfp-truncate' },
                item.label?.trim()
              ),
          item.subitems?.length
            ? h(MobiTocList, {
                items: item.subitems,
                activeHref: this.activeHref,
                depth: (this.depth as number) + 1,
                onSelect: (href: string) => this.$emit('select', href),
              })
            : null,
        ])
      )
    );
  },
});

export default { name: 'MobiRenderer' };
</script>

<style scoped>
.toc-close-btn {
  color: var(--fp-fg-tertiary);
  background: none;
  border: none;
  cursor: pointer;
  transition: color 0.15s;
}
.toc-close-btn:hover { color: #fff; }
</style>

// packages/angular-file-preview/src/renderers/Mobi/index.ts
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  input,
  output,
  signal,
  untracked,
  viewChild,
} from '@angular/core';
import { X, ChevronLeft, ChevronRight, List, Maximize2, Minimize2 } from 'lucide-angular';
import { LucideAngularModule } from 'lucide-angular';
import 'foliate-js/view.js';
import { LocaleService, getFallbackTranslator } from '../../di/locale.service';
import { RequestService } from '../../di/request.service';
import { RendererError } from '../RendererError';
import { ToolbarEventEmitter } from '../base.types';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';

interface TocItem {
  label: string;
  href?: string;
  subitems?: TocItem[];
}

interface FoliateView extends HTMLElement {
  book: {
    sections: unknown[];
    toc?: TocItem[];
    destroy?: () => void;
  } | null;
  renderer: HTMLElement & {
    setStyles?: (css: string) => void;
    next?: () => Promise<void>;
    page?: number;
    pages?: number;
  };
  open(target: string | Blob | File | ArrayBuffer): Promise<void>;
  goTo(target: number | string): Promise<void>;
  prev(distance?: number): Promise<void>;
  next(distance?: number): Promise<void>;
}

const READER_CSS = `
  @namespace epub "http://www.idpf.org/2007/ops";
  html { color-scheme: light; }
  body {
    background: #ffffff !important;
    color: #1a1a1a !important;
    font-family: "Noto Serif SC", "Source Han Serif SC", Georgia, "Times New Roman", serif !important;
    font-size: 16px !important;
    line-height: 2 !important;
    max-width: 100% !important;
    box-sizing: border-box !important;
    word-break: break-word !important;
    overflow-wrap: break-word !important;
  }
  p, li, blockquote, dd { line-height: 2; text-align: justify; }
  p { text-indent: 2em; margin: 0.8em 0; }
  h1 { text-align: center; margin: 1.5em 0 1em; }
  h2 { margin: 1.2em 0 0.8em; }
  h3 { margin: 1em 0 0.6em; }
  img { max-width: 100% !important; height: auto !important; }
  a { color: #2563eb; text-decoration: none; }
  pre { white-space: pre-wrap !important; }
`;

const A4_WIDTH = 794;

@Component({
  selector: 'afp-mobi-toc-list',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ul [style.listStyle]="'none'" [style.padding]="'0'" [style.margin]="depth() > 0 ? '0 0 0 16px' : '0'">
      @for (item of items(); track (item.href ?? item.label) + '-' + $index) {
        <li>
          @if (item.href) {
            <button
              type="button"
              class="afp-w-full afp-text-left afp-py-2 afp-px-3 afp-text-sm afp-rounded afp-transition-all afp-truncate"
              [class.afp-text-fg-primary]="activeHref() === item.href"
              [class.afp-bg-surface-3]="activeHref() === item.href"
              [class.afp-font-medium]="activeHref() === item.href"
              [class.afp-text-fg-secondary]="activeHref() !== item.href"
              [class.hover:afp-text-fg-primary]="activeHref() !== item.href"
              [class.hover:afp-bg-surface-2]="activeHref() !== item.href"
              [title]="item.label"
              style="background: none; border: none; cursor: pointer"
              (click)="select.emit(item.href)"
            >
              {{ item.label?.trim() }}
            </button>
          } @else {
            <div class="afp-w-full afp-py-2 afp-px-3 afp-text-sm afp-text-fg-tertiary afp-truncate">
              {{ item.label?.trim() }}
            </div>
          }
          @if (item.subitems?.length) {
            <afp-mobi-toc-list
              [items]="item.subitems!"
              [activeHref]="activeHref()"
              [depth]="depth() + 1"
              (select)="select.emit($event)"
            />
          }
        </li>
      }
    </ul>
  `,
})
export class MobiTocList {
  items = input.required<TocItem[]>();
  activeHref = input('');
  depth = input(0);
  select = output<string>();
}

@Component({
  selector: 'afp-mobi-renderer',
  standalone: true,
  imports: [RendererError, LucideAngularModule, MobiTocList],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'afp-block afp-w-full afp-h-full' },
  template: `
    <div class="afp-relative afp-w-full afp-h-full afp-flex afp-justify-center afp-bg-surface-1 afp-overflow-hidden">
      @if (error()) {
        <afp-renderer-error [message]="error()!" class="afp-absolute afp-inset-0" />
      }

      @if (loading() && !error()) {
        <div class="afp-absolute afp-inset-0 afp-flex afp-items-center afp-justify-center afp-z-10">
          <div class="afp-w-12 afp-h-12 afp-border-4 afp-border-line-strong afp-border-t-spinner-head afp-rounded-full afp-animate-spin"></div>
        </div>
      }

      @if (toc().length > 0) {
        <div
          class="afp-absolute afp-inset-0 afp-z-20 afp-flex afp-transition-opacity afp-duration-300"
          [style.opacity]="showToc() ? 1 : 0"
          [style.pointerEvents]="showToc() ? 'auto' : 'none'"
        >
          <div
            class="afp-w-72 afp-max-w-[80%] afp-h-full afp-bg-surface-overlay afp-backdrop-blur-xl afp-border-r afp-border-line-weak afp-flex afp-flex-col afp-shadow-2xl afp-transition-transform afp-duration-300"
            [style.transform]="showToc() ? 'translateX(0)' : 'translateX(-100%)'"
          >
            <div class="afp-flex afp-items-center afp-justify-between afp-px-4 afp-py-3 afp-border-b afp-border-line-weak afp-flex-shrink-0">
              <span class="afp-text-fg-primary afp-font-medium afp-text-sm">{{ t('toolbar.toc') }}</span>
              <button type="button" class="toc-close-btn" (click)="showToc.set(false)">
                <i-lucide [img]="xIcon" class="afp-w-4 afp-h-4" />
              </button>
            </div>
            <div class="afp-flex-1 afp-overflow-y-auto afp-py-4 afp-px-1">
              <afp-mobi-toc-list [items]="toc()" [activeHref]="activeTocHref()" (select)="handleTocClick($event)" />
            </div>
          </div>
          <div
            class="afp-flex-1 afp-transition-opacity afp-duration-300"
            [style.background]="showToc() ? 'rgba(0,0,0,0.3)' : 'transparent'"
            (click)="showToc.set(false)"
          ></div>
        </div>
      }

      @if (!error()) {
        <div
          #hostRef
          class="afp-h-full afp-bg-surface-toolbar afp-shadow-lg"
          [style.width]="isFullWidth() ? '100%' : a4Width + 'px'"
          [style.maxWidth]="'100%'"
          [style.transition]="'width 0.3s ease'"
        ></div>
      }
    </div>
  `,
  styles: [`
    .toc-close-btn {
      color: var(--fp-fg-tertiary);
      background: none;
      border: none;
      cursor: pointer;
      transition: color 0.15s;
    }
    .toc-close-btn:hover { color: var(--fp-fg-primary); }
  `],
})
export class MobiRenderer implements RendererHandle {
  url = input.required<string>();

  private readonly emitter = new ToolbarEventEmitter();
  private readonly locale = inject(LocaleService, { optional: true });
  private readonly request = inject(RequestService, { optional: true });
  protected readonly t = this.locale?.t() ?? getFallbackTranslator();
  private readonly host = viewChild<ElementRef<HTMLDivElement>>('hostRef');

  protected readonly xIcon = X;
  protected readonly a4Width = A4_WIDTH;

  readonly currentChapter = signal(1);
  readonly totalChapters = signal(1);
  readonly loading = signal(false);
  readonly error = signal<string | null>(null);
  readonly toc = signal<TocItem[]>([]);
  readonly showToc = signal(false);
  readonly activeTocHref = signal('');
  readonly isFullWidth = signal(false);

  private readonly mounted = signal(false);
  private viewInstance: FoliateView | null = null;
  private totalLocations = 1;

  constructor() {
    afterNextRender(() => this.mounted.set(true));

    effect(() => {
      const url = this.url();
      const mounted = this.mounted();
      if (!mounted || !url) return;
      untracked(() => { void this.load(); });
    });

    effect(() => {
      this.currentChapter();
      this.totalChapters();
      this.isFullWidth();
      this.showToc();
      this.loading();
      this.toc().length;
      this.emitter.notify();
    });

    const paginatorErrorHandler = (e: ErrorEvent) => {
      if (e.filename?.includes('paginator')) {
        e.preventDefault();
      }
    };
    window.addEventListener('error', paginatorErrorHandler);

    inject(DestroyRef).onDestroy(() => {
      window.removeEventListener('error', paginatorErrorHandler);
      try { (this.viewInstance as unknown as { close?: () => void })?.close?.(); } catch { /* ignore */ }
      try { this.viewInstance?.book?.destroy?.(); } catch { /* ignore */ }
      this.viewInstance = null;
      this.host()?.nativeElement?.replaceChildren();
    });
  }

  getToolbarGroups = (): ToolbarGroup[] => [
    {
      items: [
        {
          type: 'button',
          icon: List,
          tooltip: this.t('toolbar.toc'),
          action: () => this.toggleToc(),
          disabled: this.toc().length === 0,
          active: this.showToc(),
        },
      ],
    },
    {
      items: [
        {
          type: 'button',
          icon: ChevronLeft,
          tooltip: this.t('toolbar.prev_page'),
          action: () => this.prevPage(),
          disabled: this.currentChapter() <= 1,
        },
        {
          type: 'text',
          content: `${this.currentChapter()} / ${this.totalChapters()}`,
          minWidth: '4rem',
        },
        {
          type: 'button',
          icon: ChevronRight,
          tooltip: this.t('toolbar.next_page'),
          action: () => this.nextPage(),
          disabled: this.currentChapter() >= this.totalChapters(),
        },
      ],
    },
    {
      items: [
        {
          type: 'button',
          icon: this.isFullWidth() ? Minimize2 : Maximize2,
          tooltip: this.isFullWidth() ? this.t('toolbar.normal_width') : this.t('toolbar.full_width'),
          action: () => this.toggleFullWidth(),
          active: this.isFullWidth(),
        },
      ],
    },
  ];

  onToolbarChange = (listener: () => void) => this.emitter.subscribe(listener);

  protected handleTocClick(href: string): void {
    this.activeTocHref.set(href);
    this.showToc.set(false);
    this.viewInstance?.goTo(href).catch(() => {});
  }

  private prevPage(): void {
    this.viewInstance?.prev().catch(() => {});
  }

  private nextPage(): void {
    this.viewInstance?.next().catch(() => {});
  }

  private toggleToc(): void {
    this.showToc.update((v) => !v);
  }

  private toggleFullWidth(): void {
    this.isFullWidth.update((v) => !v);
    if (this.viewInstance?.renderer) {
      this.viewInstance.renderer.setAttribute('max-inline-size', this.isFullWidth() ? '9999' : '720');
    }
  }

  private reportProgress(current: number, total: number): void {
    if (total > 0) this.totalLocations = total;
    this.currentChapter.set(Math.max(1, current + 1));
    this.totalChapters.set(this.totalLocations);
  }

  private async load(): Promise<void> {
    const host = this.host()?.nativeElement;
    if (!host) return;
    this.loading.set(true);
    this.error.set(null);
    this.toc.set([]);
    this.showToc.set(false);
    this.activeTocHref.set('');
    host.replaceChildren();
    this.viewInstance = null;
    let progressReported = false;
    const sectionPagesMap = new Map<number, number>();

    try {
      const view = document.createElement('foliate-view') as FoliateView;
      host.appendChild(view);
      this.viewInstance = view;

      view.addEventListener('relocate', (e: Event) => {
        const detail = (e as CustomEvent).detail;
        if (!detail) return;

        const sectionCount = this.viewInstance?.book?.sections.length ?? 0;
        const renderer = this.viewInstance?.renderer as
          | {
              page?: number;
              pages?: number;
              getContents?: () => Array<{ index: number }>;
            }
          | undefined;

        const sectionIdx = renderer?.getContents?.()[0]?.index ?? -1;
        if (
          renderer
          && typeof renderer.page === 'number'
          && typeof renderer.pages === 'number'
          && renderer.pages > 2
          && sectionIdx >= 0
        ) {
          progressReported = true;
          const curSectionPages = renderer.pages - 2;
          sectionPagesMap.set(sectionIdx, curSectionPages);

          let pagesBefore = 0;
          for (let i = 0; i < sectionIdx; i++) {
            pagesBefore += sectionPagesMap.get(i) ?? 0;
          }
          const currentPage = pagesBefore + Math.min(curSectionPages, Math.max(1, renderer.page));

          const atEnd = (detail.fraction ?? 0) >= 0.999;
          let total: number;
          if (sectionCount === 1) {
            total = curSectionPages;
          } else if (atEnd) {
            total = currentPage;
          } else {
            const sections = this.viewInstance?.book?.sections ?? [];
            const curSize = (sections[sectionIdx] as { size?: number } | undefined)?.size ?? 0;
            const ratio = curSize > 0 ? curSectionPages / curSize : 0;
            let est = 0;
            for (let i = 0; i < sectionCount; i++) {
              if (sectionPagesMap.has(i)) {
                est += sectionPagesMap.get(i)!;
              } else {
                const s = (sections[i] as { size?: number } | undefined)?.size ?? 0;
                est += Math.max(1, Math.round(s * ratio));
              }
            }
            total = Math.max(currentPage, est);
          }

          this.reportProgress(currentPage - 1, total);
          const tocItem = detail.tocItem as { href?: string } | undefined;
          if (tocItem?.href) this.activeTocHref.set(tocItem.href);
          return;
        }

        const loc = detail.location as { current?: number; total?: number } | undefined;
        if (loc && typeof loc.current === 'number' && typeof loc.total === 'number') {
          progressReported = true;
          const atEnd = (detail.fraction ?? 0) >= 0.999;
          const actualTotal = atEnd ? loc.current + 1 : loc.total;
          this.reportProgress(loc.current, actualTotal);
        } else {
          const sections = this.viewInstance?.book?.sections ?? [];
          const idx = detail.index ?? 0;
          const frac = detail.fraction ?? 0;
          const total = Math.max(sections.length, 1);
          this.reportProgress(Math.round((idx + frac) / total * total), total);
        }
        const tocItem = detail.tocItem as { href?: string } | undefined;
        if (tocItem?.href) this.activeTocHref.set(tocItem.href);
      });

      const fetcher = this.request?.fetcher() ?? ((u: string, init?: RequestInit) => fetch(u, init));
      const res = await fetcher(this.url());
      if (!res.ok) throw new Error(`请求失败: ${res.status}`);
      const blob = await res.blob();
      let name = 'book.mobi';
      try {
        const u = new URL(this.url(), window.location.href);
        const base = u.pathname.split('/').pop();
        if (base) name = decodeURIComponent(base);
      } catch { /* blob: URL */ }

      await view.open(new File([blob], name));

      const renderer = view.renderer;
      if (renderer) {
        renderer.setAttribute('animated', '');
        renderer.setAttribute('max-inline-size', '720');
        renderer.setAttribute('margin', '48');
        renderer.setAttribute('gap', '5%');
        await renderer.next?.();
        renderer.setStyles?.(READER_CSS);
      }

      this.toc.set((view.book?.toc ?? []) as TocItem[]);
      this.loading.set(false);
      if (!progressReported) {
        this.reportProgress(0, view.book?.sections.length ?? 1);
      }
    } catch (err) {
      console.error('MOBI/AZW3 加载错误:', err);
      this.error.set(this.t('mobi.load_failed'));
      this.loading.set(false);
    }
  }
}
