// packages/angular-file-preview/src/components/resizable-split.component.ts
import {
  Component,
  computed,
  contentChild,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  input,
  signal,
  TemplateRef,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';

@Component({
  selector: 'afp-resizable-split',
  standalone: true,
  imports: [NgTemplateOutlet],
  template: `
    <div
      #containerRef
      class="afp-w-full afp-h-full afp-flex afp-flex-col md:afp-flex-row afp-min-h-0 afp-min-w-0"
    >
      @if (mobileTabMode() && !isDesktop()) {
        <div class="afp-flex afp-flex-shrink-0 afp-border-b afp-border-line-weak afp-bg-surface-toolbar">
          <button
            type="button"
            class="afp-flex-1 afp-py-2.5 afp-text-sm afp-transition-colors"
            [class.afp-text-fg-primary]="activeTab() === 'left'"
            [class.afp-border-b-2]="activeTab() === 'left'"
            [class.afp-border-fg-primary]="activeTab() === 'left'"
            [class.-afp-mb-px]="activeTab() === 'left'"
            [class.afp-text-fg-secondary]="activeTab() !== 'left'"
            (click)="switchTab('left')"
          >
            {{ leftTabLabel() }}
          </button>
          <button
            type="button"
            class="afp-flex-1 afp-py-2.5 afp-text-sm afp-transition-colors"
            [class.afp-text-fg-primary]="activeTab() === 'right'"
            [class.afp-border-b-2]="activeTab() === 'right'"
            [class.afp-border-fg-primary]="activeTab() === 'right'"
            [class.-afp-mb-px]="activeTab() === 'right'"
            [class.afp-text-fg-secondary]="activeTab() !== 'right'"
            (click)="switchTab('right')"
          >
            {{ rightTabLabel() }}
          </button>
        </div>
        <div [hidden]="activeTab() !== 'left'" class="afp-flex-1 afp-min-h-0 afp-min-w-0 afp-w-full afp-overflow-hidden">
          <ng-container *ngTemplateOutlet="leftTpl()" />
        </div>
        <div [hidden]="activeTab() !== 'right'" class="afp-flex-1 afp-min-h-0 afp-min-w-0 afp-w-full afp-overflow-hidden">
          <ng-container *ngTemplateOutlet="rightTpl()" />
        </div>
      } @else {
        <div
          class="afp-min-h-0 afp-min-w-0 afp-flex-shrink-0 afp-w-full afp-max-h-60 md:afp-h-full md:afp-max-h-none"
          [style]="leftStyle()"
        >
          <ng-container *ngTemplateOutlet="leftTpl()" />
        </div>
        <div
          role="separator"
          aria-orientation="vertical"
          class="split-divider afp-hidden md:afp-block afp-relative afp-w-1.5 afp-flex-shrink-0 afp-cursor-col-resize afp-transition-colors"
          [class.dragging]="dragging()"
          (mousedown)="onDividerDown($event)"
        >
          <span class="afp-absolute afp-inset-y-0 hit-area"></span>
        </div>
        <div class="afp-flex-1 afp-min-w-0 afp-min-h-0 afp-overflow-hidden">
          <ng-container *ngTemplateOutlet="rightTpl()" />
        </div>
      }
    </div>
  `,
  styles: [`
    .split-divider { background: var(--fp-line-weak); }
    .split-divider:hover { background: var(--fp-line); }
    .split-divider.dragging { background: var(--fp-line-strong); }
    .hit-area { left: -4px; right: -4px; }
  `],
})
export class ResizableSplitComponent {
  readonly initialLeftWidth = input(280);
  readonly minLeftWidth = input(160);
  readonly maxLeftWidth = input(640);
  readonly minRightWidth = input(200);
  readonly storageKey = input<string>();
  readonly desktopMedia = input('(min-width: 768px)');
  readonly mobileTabMode = input(false);
  readonly leftTabLabel = input('文件树');
  readonly rightTabLabel = input('预览');

  readonly left = contentChild<TemplateRef<unknown>>('left');
  readonly right = contentChild<TemplateRef<unknown>>('right');

  readonly leftTpl = computed(() => this.left() ?? null);
  readonly rightTpl = computed(() => this.right() ?? null);

  readonly leftWidth = signal(280);
  readonly dragging = signal(false);
  readonly isDesktop = signal(false);
  readonly activeTab = signal<'left' | 'right'>('left');
  readonly leftStyle = computed(() =>
    this.isDesktop() ? { width: `${this.leftWidth()}px` } : undefined,
  );

  private readonly containerRef = inject(ElementRef<HTMLElement>);
  private mq: MediaQueryList | null = null;

  constructor() {
    const key = this.storageKey();
    if (key && typeof window !== 'undefined') {
      const saved = Number(window.localStorage.getItem(key));
      this.leftWidth.set(!isNaN(saved) && saved > 0 ? saved : this.initialLeftWidth());
    } else {
      this.leftWidth.set(this.initialLeftWidth());
    }

    const mqHandler = () => {
      if (this.mq) this.isDesktop.set(this.mq.matches);
    };
    if (typeof window !== 'undefined') {
      this.mq = window.matchMedia(this.desktopMedia());
      mqHandler();
      this.mq.addEventListener('change', mqHandler);
    }

    effect(() => {
      if (!this.storageKey()) this.leftWidth.set(this.initialLeftWidth());
    });

    inject(DestroyRef).onDestroy(() => {
      this.mq?.removeEventListener('change', mqHandler);
      window.removeEventListener('mousemove', this.onMove);
      window.removeEventListener('mouseup', this.onUp);
      if (this.dragging()) {
        document.body.style.cursor = '';
        document.body.style.userSelect = '';
      }
    });
  }

  switchTab(tab: 'left' | 'right') {
    this.activeTab.set(tab);
  }

  onDividerDown(e: MouseEvent) {
    e.preventDefault();
    this.dragging.set(true);
    window.addEventListener('mousemove', this.onMove);
    window.addEventListener('mouseup', this.onUp);
    document.body.style.cursor = 'col-resize';
    document.body.style.userSelect = 'none';
  }

  private onMove = (e: MouseEvent) => {
    const el = this.containerRef.nativeElement.querySelector('div');
    if (!el) return;
    const rect = el.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const cap = rect.width - this.minRightWidth() - 6;
    const effectiveMax = Math.min(this.maxLeftWidth(), cap);
    this.leftWidth.set(Math.max(this.minLeftWidth(), Math.min(effectiveMax, x)));
  };

  private onUp = () => {
    if (!this.dragging()) return;
    this.dragging.set(false);
    window.removeEventListener('mousemove', this.onMove);
    window.removeEventListener('mouseup', this.onUp);
    document.body.style.cursor = '';
    document.body.style.userSelect = '';
    const key = this.storageKey();
    if (key) {
      try {
        window.localStorage.setItem(key, String(this.leftWidth()));
      } catch {
        // ignore
      }
    }
  };
}

// packages/vue-file-preview/src/components/ResizableSplit.vue
<script setup lang="ts">
import { ref, computed, onBeforeUnmount, onMounted, watch } from 'vue';

interface Props {
  /** 左侧初始宽度（px）；传入 storageKey 时会从 localStorage 读取 */
  initialLeftWidth?: number;
  /** 左侧最小宽度（px） */
  minLeftWidth?: number;
  /** 左侧最大宽度（px） */
  maxLeftWidth?: number;
  /** 右侧至少保留的宽度（px） */
  minRightWidth?: number;
  /** localStorage 持久化 key */
  storageKey?: string;
  /** 启用横向拖动的媒体查询 */
  desktopMedia?: string;
  /** 移动端使用 Tab 切换而非上下堆叠 */
  mobileTabMode?: boolean;
  /** Tab 模式下左侧标题 */
  leftTabLabel?: string;
  /** Tab 模式下右侧标题 */
  rightTabLabel?: string;
}

const props = withDefaults(defineProps<Props>(), {
  initialLeftWidth: 280,
  minLeftWidth: 160,
  maxLeftWidth: 640,
  minRightWidth: 200,
  desktopMedia: '(min-width: 768px)',
  mobileTabMode: false,
  leftTabLabel: '文件树',
  rightTabLabel: '预览',
});

defineOptions({ name: 'ResizableSplit' });

const containerRef = ref<HTMLDivElement | null>(null);
const leftWidth = ref<number>(
  (() => {
    if (props.storageKey && typeof window !== 'undefined') {
      const saved = Number(window.localStorage.getItem(props.storageKey));
      if (!isNaN(saved) && saved > 0) return saved;
    }
    return props.initialLeftWidth;
  })()
);
const dragging = ref(false);
const isDesktop = ref(false);
const activeTab = ref<'left' | 'right'>('left');

let mq: MediaQueryList | null = null;
const mqHandler = () => {
  if (mq) isDesktop.value = mq.matches;
};

const leftStyle = computed(() =>
  isDesktop.value ? { width: `${leftWidth.value}px` } : undefined
);

const onMove = (e: MouseEvent) => {
  if (!containerRef.value) return;
  const rect = containerRef.value.getBoundingClientRect();
  const x = e.clientX - rect.left;
  const cap = rect.width - props.minRightWidth - 6;
  const effectiveMax = Math.min(props.maxLeftWidth, cap);
  leftWidth.value = Math.max(
    props.minLeftWidth,
    Math.min(effectiveMax, x)
  );
};

const onUp = () => {
  if (!dragging.value) return;
  dragging.value = false;
  window.removeEventListener('mousemove', onMove);
  window.removeEventListener('mouseup', onUp);
  document.body.style.cursor = '';
  document.body.style.userSelect = '';
  if (props.storageKey) {
    try {
      window.localStorage.setItem(props.storageKey, String(leftWidth.value));
    } catch {
      // ignore
    }
  }
};

const onDividerDown = (e: MouseEvent) => {
  e.preventDefault();
  dragging.value = true;
  window.addEventListener('mousemove', onMove);
  window.addEventListener('mouseup', onUp);
  document.body.style.cursor = 'col-resize';
  document.body.style.userSelect = 'none';
};

onMounted(() => {
  if (typeof window !== 'undefined') {
    mq = window.matchMedia(props.desktopMedia);
    mqHandler();
    mq.addEventListener('change', mqHandler);
  }
});

onBeforeUnmount(() => {
  if (mq) mq.removeEventListener('change', mqHandler);
  window.removeEventListener('mousemove', onMove);
  window.removeEventListener('mouseup', onUp);
  if (dragging.value) {
    document.body.style.cursor = '';
    document.body.style.userSelect = '';
  }
});

watch(
  () => props.initialLeftWidth,
  (w) => {
    if (!props.storageKey) leftWidth.value = w;
  }
);

const switchTab = (tab: 'left' | 'right') => {
  activeTab.value = tab;
};

defineExpose({ switchTab });
</script>

<template>
  <div
    ref="containerRef"
    class="vfp-w-full vfp-h-full vfp-flex vfp-flex-col md:vfp-flex-row vfp-min-h-0 vfp-min-w-0"
  >
    <!-- 移动端 Tab 模式 -->
    <template v-if="mobileTabMode && !isDesktop">
      <div class="vfp-flex vfp-flex-shrink-0 vfp-border-b vfp-border-line-weak vfp-bg-surface-toolbar">
        <button
          type="button"
          class="vfp-flex-1 vfp-py-2.5 vfp-text-sm vfp-transition-colors"
          :class="activeTab === 'left'
            ? 'vfp-text-fg-primary vfp-border-b-2 vfp-border-fg-primary -vfp-mb-px'
            : 'vfp-text-fg-secondary'"
          @click="switchTab('left')"
        >
          {{ leftTabLabel }}
        </button>
        <button
          type="button"
          class="vfp-flex-1 vfp-py-2.5 vfp-text-sm vfp-transition-colors"
          :class="activeTab === 'right'
            ? 'vfp-text-fg-primary vfp-border-b-2 vfp-border-fg-primary -vfp-mb-px'
            : 'vfp-text-fg-secondary'"
          @click="switchTab('right')"
        >
          {{ rightTabLabel }}
        </button>
      </div>
      <div v-show="activeTab === 'left'" class="vfp-flex-1 vfp-min-h-0 vfp-min-w-0 vfp-w-full vfp-overflow-hidden">
        <slot name="left" />
      </div>
      <div v-show="activeTab === 'right'" class="vfp-flex-1 vfp-min-h-0 vfp-min-w-0 vfp-w-full vfp-overflow-hidden">
        <slot name="right" />
      </div>
    </template>

    <!-- 桌面端 / 移动端默认堆叠模式 -->
    <template v-else>
      <div
        class="vfp-min-h-0 vfp-min-w-0 vfp-flex-shrink-0 vfp-w-full vfp-max-h-60 md:vfp-h-full md:vfp-max-h-none"
        :style="leftStyle"
      >
        <slot name="left" />
      </div>
      <div
        role="separator"
        aria-orientation="vertical"
        class="split-divider vfp-hidden md:vfp-block vfp-relative vfp-w-1.5 vfp-flex-shrink-0 vfp-cursor-col-resize vfp-transition-colors"
        :class="dragging ? 'dragging' : ''"
        @mousedown="onDividerDown"
      >
        <span class="vfp-absolute vfp-inset-y-0 hit-area" />
      </div>
      <div class="vfp-flex-1 vfp-min-w-0 vfp-min-h-0 vfp-overflow-hidden">
        <slot name="right" />
      </div>
    </template>
  </div>
</template>

<style scoped>
.split-divider {
  background: rgba(255, 255, 255, 0.1);
}
.split-divider:hover {
  background: rgba(255, 255, 255, 0.3);
}
.split-divider.dragging {
  background: rgba(255, 255, 255, 0.4);
}
.hit-area {
  left: -4px;
  right: -4px;
}
</style>
