// packages/angular-file-preview/src/file-preview-content.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import {
  downloadFileWithFetcher,
  getFileType,
  normalizeFiles,
  resolveShowClose,
  type Locale,
  type Messages,
  type PreviewFile,
  type PreviewFileInput,
  type RequestHandler,
  type RequestInitFactory,
  type ShouldFetchAsBlob,
  type Theme,
  type CustomRendererEventPayload,
} from './fp-core';
import type { CustomRenderer, CustomRendererContext } from './types';
import type { RendererHandle } from './renderers/base.types';
import type { ToolbarGroup } from './renderers/toolbar.types';
import { LocaleService } from './di/locale.service';
import { ThemeService } from './di/theme.service';
import { RequestService, needsBlobUrl } from './di/request.service';
import { createSystemDarkSignal, resolveTheme } from './di/theme-mode';
import { BUILTIN_RENDERERS } from './renderers/registry';
import type { RendererLoader } from './renderers/lazy';
import { FilePreviewToolbar } from './components/preview/file-preview-toolbar';
import { NavArrows } from './components/preview/nav-arrows';
import { RendererOutlet } from './components/preview/renderer-outlet';
import { UnsupportedRenderer } from './renderers/Unsupported/index';

const MAX_ZIP_NESTING_DEPTH = 3;

@Component({
  selector: 'FilePreviewContent, afp-file-preview-content',
  standalone: true,
  imports: [FilePreviewToolbar, NavArrows, RendererOutlet, UnsupportedRenderer],
  providers: [LocaleService, ThemeService, RequestService],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'afp-block afp-w-full afp-h-full' },
  template: `
    @if (currentFile(); as file) {
      <div
        #rootRef
        [attr.tabindex]="mode() === 'embed' ? 0 : -1"
        [attr.data-theme]="resolvedTheme()"
        class="afp-root afp-relative afp-w-full afp-h-full afp-flex afp-flex-col afp-overflow-hidden afp-outline-none"
      >
        @if (!headless()) {
          <afp-file-preview-toolbar
            [fileName]="file.name"
            [currentIndex]="currentIndex()"
            [totalFiles]="normalizedFiles().length"
            [toolGroups]="toolGroups()"
            [t]="t()"
            [showClose]="showCloseButton()"
            [showDownload]="showDownload()"
            (download)="handleDownload()"
            (close)="close.emit()"
          />
        }

        <div
          #contentRef
          class="afp-flex-1 afp-flex afp-items-center afp-justify-center afp-overflow-auto"
        >
          @if (customRendererCmp()) {
            <afp-renderer-outlet
              [componentType]="customRendererCmp()"
              [inputs]="customInputs()"
              (handleChange)="onRendererHandle($event)"
            />
          } @else if (fileType() === 'zip' && zipNestingDepth() >= maxZipDepth) {
            <afp-unsupported-renderer
              [fileName]="file.name"
              [fileType]="file.type"
              (download)="handleDownload()"
            />
          } @else if (builtinLoader()) {
            <afp-renderer-outlet
              [loader]="builtinLoader()"
              [inputs]="builtinInputs()"
              (handleChange)="onRendererHandle($event)"
            />
          } @else {
            <afp-unsupported-renderer
              [fileName]="file.name"
              [fileType]="file.type"
              (download)="handleDownload()"
            />
          }
        </div>

        @if (!headless() && showNavigation() && normalizedFiles().length > 1) {
          <afp-nav-arrows
            [container]="contentEl()"
            [hasPrev]="loopNavigation() || currentIndex() > 0"
            [hasNext]="loopNavigation() || currentIndex() < normalizedFiles().length - 1"
            [resetKey]="currentIndex()"
            [t]="t()"
            (prev)="navigatePrevious()"
            (next)="navigateNext()"
          />
        }
      </div>
    }
  `,
})
export class FilePreviewContent {
  files = input.required<PreviewFileInput[]>();
  currentIndex = input(0);
  customRenderers = input<CustomRenderer[]>([]);
  mode = input<'modal' | 'embed'>('modal');
  zipNestingDepth = input(0);
  locale = input<Locale | undefined>(undefined);
  messages = input<Partial<Record<Locale, Partial<Messages>>> | undefined>(undefined);
  headless = input(false);
  theme = input<Theme>('dark');
  requestInit = input<RequestInitFactory | undefined>(undefined);
  requestHandler = input<RequestHandler | undefined>(undefined);
  shouldFetchAsBlob = input<ShouldFetchAsBlob | undefined>(undefined);
  onDownload = input<((file: PreviewFile) => void | Promise<void>) | undefined>(undefined);
  showClose = input<boolean | undefined>(undefined);
  showDownload = input(true);
  showNavigation = input(true);
  loopNavigation = input(false);

  navigate = output<number>();
  close = output<void>();
  customEvent = output<CustomRendererEventPayload>();

  protected readonly maxZipDepth = MAX_ZIP_NESTING_DEPTH;

  private readonly localeService = inject(LocaleService);
  private readonly themeService = inject(ThemeService);
  private readonly requestService = inject(RequestService);
  private readonly destroyRef = inject(DestroyRef);

  private readonly root = viewChild<ElementRef<HTMLDivElement>>('rootRef');
  private readonly content = viewChild<ElementRef<HTMLDivElement>>('contentRef');

  private readonly system = createSystemDarkSignal();
  readonly resolvedUrl = signal('');
  private createdBlobUrl: string | null = null;
  private unsubscribeToolbar: (() => void) | null = null;
  readonly rendererToolbarGroups = signal<ToolbarGroup[]>([]);

  readonly normalizedFiles = computed(() => normalizeFiles(this.files()));
  readonly currentFile = computed(() => this.normalizedFiles()[this.currentIndex()] as PreviewFile | undefined);
  readonly fileType = computed(() => {
    const file = this.currentFile();
    return file ? getFileType(file) : 'unsupported';
  });
  readonly t = computed(() => this.localeService.t());
  readonly resolvedTheme = computed(() => resolveTheme(this.theme(), this.system.systemDark()));
  readonly showCloseButton = computed(() => resolveShowClose(this.mode(), this.showClose()));
  readonly contentEl = computed(() => this.content()?.nativeElement ?? null);

  readonly customRenderer = computed(() => {
    const file = this.currentFile();
    if (!file) return null;
    return this.customRenderers().find((r) => r.test(file)) ?? null;
  });

  readonly customCtx = computed<CustomRendererContext>(() => ({
    emit: (name, payload) => {
      const file = this.currentFile();
      if (!file) return;
      this.customEvent.emit({ name, payload, file });
    },
    t: this.t(),
    theme: this.resolvedTheme(),
    locale: this.locale() ?? 'zh-CN',
  }));

  readonly customRendererCmp = computed(() => {
    const renderer = this.customRenderer();
    const file = this.currentFile();
    if (!renderer || !file) return null;
    return renderer.render(file, this.customCtx());
  });

  readonly customInputs = computed(() => ({
    file: this.currentFile(),
    ctx: this.customCtx(),
  }));

  readonly builtinConfig = computed(() => {
    const type = this.fileType();
    return (
      BUILTIN_RENDERERS.find((r) => r.fileType === type) ??
      (type === 'xls' ? BUILTIN_RENDERERS.find((r) => r.fileType === 'xlsx') : null) ??
      null
    );
  });

  readonly builtinLoader = computed<RendererLoader | null>(() => this.builtinConfig()?.loader ?? null);

  readonly builtinInputs = computed(() => {
    const config = this.builtinConfig();
    const file = this.currentFile();
    if (!config || !file) return {};
    return config.getProps({
      resolvedUrl: this.resolvedUrl(),
      zipNestingDepth: this.zipNestingDepth(),
      currentFile: file,
    });
  });

  readonly toolGroups = computed(() => {
    const custom = this.customRenderer();
    const file = this.currentFile();
    if (custom && file) {
      return custom.getToolbarGroups?.(file, this.customCtx()) ?? [];
    }
    return this.rendererToolbarGroups();
  });

  constructor() {
    effect(() => {
      this.localeService.configure(this.locale(), this.messages());
    });
    effect(() => {
      this.themeService.setTheme(this.resolvedTheme());
    });
    effect(() => {
      this.system.bind(this.theme());
    });
    effect(() => {
      this.requestService.configure({
        requestInit: this.requestInit(),
        requestHandler: this.requestHandler(),
        shouldFetchAsBlob: this.shouldFetchAsBlob(),
      });
    });
    effect(() => {
      const file = this.currentFile();
      const need = needsBlobUrl(file, this.requestService.shouldFetchAsBlob());
      void this.refreshResolvedUrl(file, need);
    });

    this.destroyRef.onDestroy(() => {
      this.cleanupSubscription();
      this.revokeBlob();
    });

    effect((onCleanup) => {
      const mode = this.mode();
      const rootEl = this.root()?.nativeElement;
      const handler = this.handleKeyDown;
      if (mode === 'modal') {
        window.addEventListener('keydown', handler);
        onCleanup(() => window.removeEventListener('keydown', handler));
      } else if (rootEl) {
        rootEl.addEventListener('keydown', handler);
        onCleanup(() => rootEl.removeEventListener('keydown', handler));
      }
    });
  }

  onRendererHandle(handle: RendererHandle | null): void {
    this.cleanupSubscription();
    if (!handle) {
      this.rendererToolbarGroups.set([]);
      return;
    }
    this.rendererToolbarGroups.set(handle.getToolbarGroups?.() ?? []);
    if (handle.onToolbarChange) {
      this.unsubscribeToolbar = handle.onToolbarChange(() => {
        this.rendererToolbarGroups.set(handle.getToolbarGroups?.() ?? []);
      });
    }
  }

  async handleDownload(): Promise<void> {
    const file = this.currentFile();
    if (!file) return;
    const custom = this.onDownload();
    if (custom) {
      await custom(file);
      return;
    }
    try {
      await downloadFileWithFetcher(file.url, file.name, this.requestService.fetcher());
    } catch (err) {
      console.error('[file-preview] download failed:', err);
    }
  }

  navigatePrevious(): void {
    const total = this.normalizedFiles().length;
    if (total <= 1) return;
    if (this.currentIndex() > 0) {
      this.navigate.emit(this.currentIndex() - 1);
    } else if (this.loopNavigation()) {
      this.navigate.emit(total - 1);
    }
  }

  navigateNext(): void {
    const total = this.normalizedFiles().length;
    if (total <= 1) return;
    if (this.currentIndex() < total - 1) {
      this.navigate.emit(this.currentIndex() + 1);
    } else if (this.loopNavigation()) {
      this.navigate.emit(0);
    }
  }

  private handleKeyDown = (e: KeyboardEvent): void => {
    if (e.key === 'Escape' && this.mode() === 'modal') {
      this.close.emit();
    } else if (e.key === 'ArrowLeft') {
      this.navigatePrevious();
    } else if (e.key === 'ArrowRight') {
      this.navigateNext();
    } else if (
      e.key === 'Home' &&
      this.normalizedFiles().length > 0 &&
      this.currentIndex() !== 0
    ) {
      this.navigate.emit(0);
    } else if (
      e.key === 'End' &&
      this.normalizedFiles().length > 0 &&
      this.currentIndex() !== this.normalizedFiles().length - 1
    ) {
      this.navigate.emit(this.normalizedFiles().length - 1);
    }
  };

  private cleanupSubscription(): void {
    this.unsubscribeToolbar?.();
    this.unsubscribeToolbar = null;
  }

  private revokeBlob(): void {
    if (this.createdBlobUrl) {
      URL.revokeObjectURL(this.createdBlobUrl);
      this.createdBlobUrl = null;
    }
  }

  private async refreshResolvedUrl(file: PreviewFile | undefined, need: boolean): Promise<void> {
    if (!file) {
      this.revokeBlob();
      this.resolvedUrl.set('');
      return;
    }
    if (!need) {
      this.revokeBlob();
      this.resolvedUrl.set(file.url);
      return;
    }
    this.resolvedUrl.set('');
    try {
      const blobUrl = await this.requestService.resolveBlobUrl(file.url);
      this.revokeBlob();
      this.createdBlobUrl = blobUrl;
      this.resolvedUrl.set(blobUrl);
    } catch (err) {
      console.error('[file-preview] resolve blob url failed:', err);
      this.resolvedUrl.set(file.url);
    }
  }
}

// packages/react-file-preview/src/FilePreviewContent.tsx
import React, { useCallback, useMemo, useRef, useState, useEffect } from 'react';
import { getFileType, createTranslator, resolveShowClose, type Locale, type Messages, type Translator, type Theme, downloadFileWithFetcher } from '@eternalheart/file-preview-core';
import { LocaleProvider } from './i18n/LocaleContext';
import { ThemeProvider } from './ThemeContext';
import type { PreviewFileInput, CustomRenderer, CustomRendererContext } from './types';
import type { CustomRendererEventPayload, PreviewFile, RequestHandler, RequestInitFactory, ShouldFetchAsBlob } from '@eternalheart/file-preview-core';
import { normalizeFiles } from './utils/fileNormalizer';
import { RequestProvider, useResolvedUrl, useFetcher } from './RequestContext';
import type { RendererHandle } from './renderers/base.types';
import type { ToolbarGroup } from './renderers/toolbar.types';
import { UnsupportedRenderer } from './renderers/Unsupported';
import {
  useKeyboardNavigation,
  useThemeMode,
} from './hooks';
import { FilePreviewToolbar, FilePreviewRenderer, NavArrows } from './components/preview';
import { BUILTIN_RENDERERS } from './renderers/registry';

const MAX_ZIP_NESTING_DEPTH = 3;

export interface FilePreviewContentProps {
  files: PreviewFileInput[];
  currentIndex: number;
  onNavigate?: (index: number) => void;
  customRenderers?: CustomRenderer[];
  mode?: 'modal' | 'embed';
  onClose?: () => void;
  zipNestingDepth?: number;
  locale?: Locale;
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  headless?: boolean;
  theme?: Theme;
  onCustomEvent?: (event: CustomRendererEventPayload) => void;
  requestInit?: RequestInitFactory;
  requestHandler?: RequestHandler;
  shouldFetchAsBlob?: ShouldFetchAsBlob;
  onDownload?: (file: PreviewFile) => void;
  onError?: (error: Error, errorInfo: React.ErrorInfo) => void;
  /** 是否显示关闭按钮，默认根据 mode 决定（modal: true, embed: false） */
  showClose?: boolean;
  showDownload?: boolean;
  /** 是否显示文件导航箭头，默认 true */
  showNavigation?: boolean;
  /** 是否循环导航文件，默认 false */
  loopNavigation?: boolean;
}

export const FilePreviewContent: React.FC<FilePreviewContentProps> = (props) => {
  const { requestInit, requestHandler, shouldFetchAsBlob } = props;
  return (
    <RequestProvider
      requestInit={requestInit}
      requestHandler={requestHandler}
      shouldFetchAsBlob={shouldFetchAsBlob}
    >
      <FilePreviewContentInner {...props} />
    </RequestProvider>
  );
};

const FilePreviewContentInner: React.FC<FilePreviewContentProps> = ({
  files,
  currentIndex,
  onNavigate,
  customRenderers = [],
  mode = 'modal',
  onClose,
  zipNestingDepth = 0,
  locale = 'zh-CN',
  messages: userMessages,
  headless = false,
  theme = 'dark',
  onCustomEvent,
  onDownload,
  onError,
  showClose,
  showDownload = true,
  showNavigation = true,
  loopNavigation = false,
  requestInit: _requestInit,
  requestHandler: _requestHandler,
  shouldFetchAsBlob: _shouldFetchAsBlob,
}) => {
  const t: Translator = useMemo(
    () => createTranslator({ locale, messages: userMessages }),
    [locale, userMessages],
  );

  const normalizedFiles = useMemo(() => normalizeFiles(files), [files]);
  const currentFile = normalizedFiles[currentIndex];
  const resolvedUrl = useResolvedUrl(currentFile);
  const fetcher = useFetcher();

  const customRenderer = useMemo(() => {
    if (!currentFile) return null;
    return customRenderers.find(renderer => renderer.test(currentFile));
  }, [currentFile, customRenderers]);

  const fileType = currentFile ? getFileType(currentFile) : 'unsupported';

  // 主题
  const resolvedTheme = useThemeMode(theme);

  // Refs
  const contentRef = useRef<HTMLDivElement>(null);
  const rootRef = useRef<HTMLDivElement>(null);

  // 新架构：通用渲染器 ref，用于获取工具栏配置
  const rendererInstanceRef = useRef<RendererHandle | null>(null);
  const [rendererToolbarGroups, setRendererToolbarGroups] = useState<ToolbarGroup[]>([]);
  const cleanupRef = useRef<(() => void) | null>(null);

  // 设置渲染器并初始化工具栏（在渲染器挂载/更新时同步触发）
  const setupRenderer = useCallback((renderer: RendererHandle | null) => {
    // 清理旧的订阅
    if (cleanupRef.current) {
      cleanupRef.current();
      cleanupRef.current = null;
    }

    rendererInstanceRef.current = renderer;

    if (!renderer?.getToolbarGroups) {
      setRendererToolbarGroups([]);
      return;
    }

    // 立即获取一次初始状态
    const initialGroups = renderer.getToolbarGroups();
    setRendererToolbarGroups(initialGroups);

    // 如果渲染器支持事件订阅，使用事件机制
    if (renderer.onToolbarChange) {
      const unsubscribe = renderer.onToolbarChange(() => {
        const groups = renderer.getToolbarGroups();
        setRendererToolbarGroups(groups);
      });

      cleanupRef.current = unsubscribe;
      return;
    }

    // 回退机制：如果渲染器不支持事件，使用轮询
    const interval = setInterval(() => {
      const groups = renderer.getToolbarGroups();
      setRendererToolbarGroups(groups);
    }, 100);
    cleanupRef.current = () => clearInterval(interval);
  }, []);

  // Callback ref：在渲染器挂载/卸载时立即触发
  const rendererRef = useCallback((renderer: RendererHandle | null) => {
    setupRenderer(renderer);
  }, [setupRenderer]);

  // 组件卸载时清理
  useEffect(() => {
    return () => {
      if (cleanupRef.current) {
        cleanupRef.current();
        cleanupRef.current = null;
      }
    };
  }, []);

  // 键盘导航
  useKeyboardNavigation({
    mode,
    currentIndex,
    totalFiles: normalizedFiles.length,
    onNavigate,
    onClose,
    loopNavigation,
    rootRef,
  });

  const navigatePrevious = useCallback(() => {
    if (!onNavigate || normalizedFiles.length <= 1) return;
    if (currentIndex > 0) {
      onNavigate(currentIndex - 1);
    } else if (loopNavigation) {
      onNavigate(normalizedFiles.length - 1);
    }
  }, [currentIndex, loopNavigation, normalizedFiles.length, onNavigate]);

  const navigateNext = useCallback(() => {
    if (!onNavigate || normalizedFiles.length <= 1) return;
    if (currentIndex < normalizedFiles.length - 1) {
      onNavigate(currentIndex + 1);
    } else if (loopNavigation) {
      onNavigate(0);
    }
  }, [currentIndex, loopNavigation, normalizedFiles.length, onNavigate]);

  // 图片自动适应窗口（已禁用，改为手动点击"适应窗口"按钮）
  // useImageAutoFit({
  //   enabled: fileType === 'image',
  //   naturalWidth: state.image.naturalWidth,
  //   naturalHeight: state.image.naturalHeight,
  //   containerRef: contentRef,
  //   onZoomChange: (zoom) => dispatch({ type: 'SET_ZOOM', payload: zoom }),
  // });

  // 自定义渲染器上下文
  const emitCustom = useCallback(
    (name: string, payload?: unknown) => {
      if (!currentFile) return;
      onCustomEvent?.({ name, payload, file: currentFile });
    },
    [currentFile, onCustomEvent],
  );

  const customCtx = useMemo<CustomRendererContext>(
    () => ({ emit: emitCustom, t, theme: resolvedTheme, locale }),
    [emitCustom, t, resolvedTheme, locale],
  );

  const handleDownload = useCallback(async () => {
    if (!currentFile) return;
    if (onDownload) {
      await onDownload(currentFile);
      return;
    }
    try {
      await downloadFileWithFetcher(currentFile.url, currentFile.name, fetcher);
    } catch (err) {
      console.error('[file-preview] download failed:', err);
    }
  }, [currentFile, onDownload, fetcher]);

  if (!currentFile) return null;

  return (
    <LocaleProvider locale={locale} messages={userMessages}>
      <ThemeProvider theme={resolvedTheme}>
        <div
          ref={rootRef}
          tabIndex={mode === 'embed' ? 0 : -1}
          data-theme={resolvedTheme}
          className="rfp-relative rfp-w-full rfp-h-full rfp-flex rfp-flex-col rfp-overflow-hidden rfp-outline-none"
        >
          {!headless && (
            <FilePreviewToolbar
              fileName={currentFile.name}
              currentIndex={currentIndex}
              totalFiles={normalizedFiles.length}
              toolGroups={rendererToolbarGroups}
              t={t}
              onDownload={handleDownload}
              onClose={onClose}
              showClose={resolveShowClose(mode, showClose)}
              showDownload={showDownload}
            />
          )}

          <div
            ref={contentRef}
            className="rfp-flex-1 rfp-flex rfp-items-center rfp-justify-center rfp-overflow-auto"
          >
            <FilePreviewRenderer
              currentFile={currentFile}
              customRenderer={customRenderer}
              customRendererContext={customCtx}
              t={t}
              onDownload={handleDownload}
              onError={onError}
            >
              {(() => {
                // ZIP 嵌套深度超限：fallback 到 Unsupported
                if (fileType === 'zip' && zipNestingDepth >= MAX_ZIP_NESTING_DEPTH) {
                  return (
                    <UnsupportedRenderer
                      fileName={currentFile.name}
                      fileType={currentFile.type}
                      onDownload={handleDownload}
                    />
                  );
                }

                // 从注册表查找匹配的渲染器
                const rendererConfig =
                  BUILTIN_RENDERERS.find((r) => r.fileType === fileType) ??
                  (fileType === 'xls'
                    ? BUILTIN_RENDERERS.find((r) => r.fileType === 'xlsx')
                    : undefined);

                if (rendererConfig) {
                  const RendererComponent = rendererConfig.component;
                  const rendererProps = rendererConfig.getProps({
                    resolvedUrl,
                    zipNestingDepth,
                    currentFile,
                  });
                  return <RendererComponent ref={rendererRef} {...rendererProps} />;
                }

                // 未匹配：fallback 到 UnsupportedRenderer
                return (
                  <UnsupportedRenderer
                    fileName={currentFile.name}
                    fileType={currentFile.type}
                    onDownload={handleDownload}
                  />
                );
              })()}
            </FilePreviewRenderer>
          </div>

          {!headless && showNavigation && normalizedFiles.length > 1 && (
            <NavArrows
              containerRef={contentRef}
              hasPrev={loopNavigation || currentIndex > 0}
              hasNext={loopNavigation || currentIndex < normalizedFiles.length - 1}
              onPrev={navigatePrevious}
              onNext={navigateNext}
              resetKey={currentIndex}
              t={t}
            />
          )}
        </div>
      </ThemeProvider>
    </LocaleProvider>
  );
};
