// packages/angular-file-preview/src/file-preview-embed.component.ts
import {
  Component,
  computed,
  DestroyRef,
  effect,
  inject,
  input,
  output,
  signal,
} from '@angular/core';
import type {
  CustomRendererEventPayload,
  Locale,
  Messages,
  PreviewFile,
  PreviewFileInput,
  RequestHandler,
  RequestInitFactory,
  ShouldFetchAsBlob,
  Theme,
} from '@eternalheart/file-preview-core';
import type { CustomRenderer } from './types';
import { FilePreviewContentComponent } from './file-preview-content.component';

@Component({
  selector: 'afp-file-preview-embed',
  standalone: true,
  imports: [FilePreviewContentComponent],
  template: `
    <div class="afp-root" [style]="wrapperStyle()" [attr.data-theme]="resolvedTheme()">
      <div class="afp-relative afp-w-full afp-h-full afp-overflow-hidden afp-bg-surface-overlay">
        <afp-file-preview-content
          mode="embed"
          [files]="files()"
          [currentIndex]="currentIndex()"
          [customRenderers]="customRenderers()"
          [locale]="locale()"
          [messages]="messages()"
          [headless]="headless()"
          [theme]="theme()"
          [requestInit]="requestInit()"
          [requestHandler]="requestHandler()"
          [shouldFetchAsBlob]="shouldFetchAsBlob()"
          [onDownload]="onDownload()"
          [onClose]="onClose()"
          [showClose]="showClose()"
          [showDownload]="showDownload()"
          (navigate)="navigate.emit($event)"
          (customEvent)="customEvent.emit($event)"
          (close)="close.emit()"
        />
      </div>
    </div>
  `,
})
export class FilePreviewEmbedComponent {
  readonly files = input.required<PreviewFileInput[]>();
  readonly currentIndex = input(0);
  readonly customRenderers = input<CustomRenderer[]>([]);
  readonly width = input<number | string>('100%');
  readonly height = input<number | string>('100%');
  readonly locale = input<Locale>();
  readonly messages = input<Partial<Record<Locale, Partial<Messages>>>>();
  readonly headless = input(false);
  readonly theme = input<Theme>('dark');
  readonly requestInit = input<RequestInitFactory>();
  readonly requestHandler = input<RequestHandler>();
  readonly shouldFetchAsBlob = input<ShouldFetchAsBlob>();
  readonly onDownload = input<(file: PreviewFile) => void | Promise<void>>();
  readonly onClose = input<() => void>();
  readonly showClose = input<boolean>();
  readonly showDownload = input(true);

  readonly navigate = output<number>();
  readonly customEvent = output<CustomRendererEventPayload>();
  readonly close = output<void>();

  readonly systemDark = signal(
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-color-scheme: dark)').matches
      : true,
  );

  readonly resolvedTheme = computed(() =>
    this.theme() === 'auto' ? (this.systemDark() ? 'dark' : 'light') : this.theme(),
  );

  readonly wrapperStyle = computed(() => {
    const w = this.width();
    const h = this.height();
    return {
      width: typeof w === 'number' ? `${w}px` : w,
      height: typeof h === 'number' ? `${h}px` : h,
    };
  });

  constructor() {
    effect(() => {
      const theme = this.theme();
      if (typeof window === 'undefined' || theme !== 'auto') return;
      const mql = window.matchMedia('(prefers-color-scheme: dark)');
      const handler = (e: MediaQueryListEvent) => this.systemDark.set(e.matches);
      mql.addEventListener('change', handler);
      this.systemDark.set(mql.matches);
      return () => mql.removeEventListener('change', handler);
    });
    inject(DestroyRef);
  }
}

// packages/react-file-preview/src/FilePreviewEmbed.tsx
import { useEffect, useState } from 'react';
import { PreviewFileInput, CustomRenderer } from './types';
import { FilePreviewContent } from './FilePreviewContent';
import type { Locale, Messages, Theme, CustomRendererEventPayload } from '@eternalheart/file-preview-core';

interface FilePreviewEmbedProps {
  files: PreviewFileInput[];
  currentIndex?: number;
  onNavigate?: (index: number) => void;
  customRenderers?: CustomRenderer[];
  /** 宽度,默认 100% 填充父容器 */
  width?: number | string;
  /** 高度,默认 100% 填充父容器 */
  height?: number | string;
  className?: string;
  style?: React.CSSProperties;
  /** 国际化语言，默认 'zh-CN' */
  locale?: Locale;
  /** 用户自定义翻译字典 */
  messages?: Partial<Record<Locale, Partial<Messages>>>;
  /** 无头模式：隐藏工具栏和导航箭头 */
  headless?: boolean;
  /** 主题模式，默认 'dark' */
  theme?: Theme;
  /** 自定义渲染器派发的事件出口 */
  onCustomEvent?: (event: CustomRendererEventPayload) => void;
}

export const FilePreviewEmbed: React.FC<FilePreviewEmbedProps> = ({
  files,
  currentIndex = 0,
  onNavigate,
  customRenderers = [],
  width = '100%',
  height = '100%',
  className,
  style,
  locale,
  messages,
  headless,
  theme = 'dark',
  onCustomEvent,
}) => {
  const [systemDark, setSystemDark] = useState(() =>
    typeof window !== 'undefined'
      ? window.matchMedia('(prefers-color-scheme: dark)').matches
      : true,
  );

  useEffect(() => {
    if (theme !== 'auto') return;
    const mql = window.matchMedia('(prefers-color-scheme: dark)');
    const handler = (e: MediaQueryListEvent) => setSystemDark(e.matches);
    mql.addEventListener('change', handler);
    return () => mql.removeEventListener('change', handler);
  }, [theme]);

  const resolvedTheme = theme === 'auto' ? (systemDark ? 'dark' : 'light') : theme;

  return (
    <div
      className={`rfp-root ${className ?? ''}`}
      style={{ width, height, ...style }}
      data-theme={resolvedTheme}
    >
      <div className="rfp-relative rfp-w-full rfp-h-full rfp-overflow-hidden rfp-bg-surface-overlay">
        <FilePreviewContent
          mode="embed"
          files={files}
          currentIndex={currentIndex}
          onNavigate={onNavigate}
          customRenderers={customRenderers}
          locale={locale}
          messages={messages}
          headless={headless}
          theme={theme}
          onCustomEvent={onCustomEvent}
        />
      </div>
    </div>
  );
};
