// packages/react-file-preview/src/components/preview/FilePreviewToolbar.tsx
import React from 'react';
import { Download, X } from 'lucide-react';
import type { ToolbarGroup } from '../../renderers/toolbar.types';
import type { Translator } from '@eternalheart/file-preview-core';
import { renderToolbarItems } from '../../toolbar/renderItems';

export interface FilePreviewToolbarProps {
  fileName: string;
  currentIndex: number;
  totalFiles: number;
  toolGroups: ToolbarGroup[];
  t: Translator;
  onDownload: () => void;
  onClose?: () => void;
  showClose: boolean;
  showDownload: boolean;
}

/**
 * 文件预览顶部工具栏组件
 * - 桌面端：单行显示所有按钮
 * - 移动端：第一行显示文件名 + 下载/关闭，第二行显示工具按钮
 */
export const FilePreviewToolbar: React.FC<FilePreviewToolbarProps> = ({
  fileName,
  currentIndex,
  totalFiles,
  toolGroups,
  t,
  onDownload,
  onClose,
  showClose,
  showDownload,
}) => {
  const showCloseButton = showClose;

  // 操作组：下载、关闭（通用，不属于任何 Renderer）
  const actionGroups: ToolbarGroup[] = [
    ...(showDownload
      ? [
          {
            items: [
              {
                type: 'button' as const,
                icon: <Download className="rfp-w-4 rfp-h-4" />,
                tooltip: t('accessibility.downloadFile'),
                action: onDownload,
              },
            ],
          },
        ]
      : []),
    ...(showCloseButton
      ? [
          {
            items: [
              {
                type: 'button' as const,
                icon: <X className="rfp-w-4 rfp-h-4" />,
                tooltip: t('accessibility.closePreview'),
                action: onClose!,
                ariaKeyshortcuts: 'Escape',
              },
            ],
          },
        ]
      : []),
  ];

  return (
    <div
      className="rfp-flex-shrink-0 rfp-z-10 rfp-backdrop-blur-md rfp-border-b rfp-bg-surface-toolbar rfp-border-line"
      style={{ paddingTop: 'env(safe-area-inset-top, 0px)' }}
    >
      {/* 第一行：文件名 + 分页 + 关闭/下载（移动端右侧）/全部按钮（桌面端） */}
      <div className="rfp-flex rfp-items-center rfp-justify-between rfp-px-3 md:rfp-px-5 rfp-py-1.5 md:rfp-py-2.5">
        {/* 左侧：文件名 + 分页 */}
        <div className="rfp-flex rfp-items-center rfp-flex-1 rfp-min-w-0 rfp-mr-2 md:rfp-mr-3">
          <h2 className="rfp-font-medium rfp-text-xs md:rfp-text-sm rfp-truncate rfp-text-fg-primary">
            {fileName}
          </h2>
          <span
            className="rfp-text-xs rfp-ml-2 rfp-flex-shrink-0 rfp-text-fg-muted"
            aria-live="polite"
            aria-atomic="true"
          >
            {currentIndex + 1}/{totalFiles}
          </span>
        </div>

        {/* 移动端：仅显示下载 + 关闭 */}
        <div className="rfp-flex rfp-items-center rfp-gap-1 md:rfp-hidden rfp-flex-shrink-0">
          {renderToolbarItems(actionGroups, 'rfp-mx-0.5')}
        </div>

        {/* 桌面端：所有工具按钮 */}
        <div className="rfp-hidden md:rfp-flex rfp-items-center rfp-gap-1 rfp-flex-shrink-0">
          {renderToolbarItems(toolGroups, 'rfp-mx-1')}
          {toolGroups.length > 0 && actionGroups.length > 0 && (
            <div className="rfp-w-px rfp-h-4 rfp-mx-1 rfp-bg-divide" />
          )}
          {renderToolbarItems(actionGroups, 'rfp-mx-1')}
        </div>
      </div>

      {/* 第二行：移动端工具按钮 */}
      {toolGroups.length > 0 && (
        <div className="rfp-flex rfp-items-center rfp-gap-1 rfp-px-3 rfp-pb-1.5 rfp-overflow-x-auto scrollbar-hide md:rfp-hidden">
          {renderToolbarItems(toolGroups, 'rfp-mx-0.5')}
        </div>
      )}
    </div>
  );
};

// packages/angular-file-preview/src/components/preview/file-preview-toolbar.ts
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';
import { Download, X } from 'lucide-angular';
import type { Translator } from '../../fp-core';
import type { ToolbarGroup } from '../../renderers/toolbar.types';
import { ToolbarButton } from './toolbar-button';

@Component({
  selector: 'afp-file-preview-toolbar',
  standalone: true,
  imports: [ToolbarButton],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      class="afp-flex-shrink-0 afp-z-10 afp-backdrop-blur-md afp-border-b afp-bg-surface-toolbar afp-border-line"
      style="padding-top: env(safe-area-inset-top, 0px)"
    >
      <div class="afp-flex afp-items-center afp-justify-between afp-px-3 md:afp-px-5 afp-py-1.5 md:afp-py-2.5">
        <div class="afp-flex afp-items-center afp-flex-1 afp-min-w-0 afp-mr-2 md:afp-mr-3">
          <h2 class="afp-font-medium afp-text-xs md:afp-text-sm afp-truncate afp-text-fg-primary">
            {{ fileName() }}
          </h2>
          <span
            class="afp-text-xs afp-ml-2 afp-flex-shrink-0 afp-text-fg-muted"
            aria-live="polite"
            aria-atomic="true"
          >
            {{ currentIndex() + 1 }}/{{ totalFiles() }}
          </span>
        </div>

        <div class="afp-flex afp-items-center afp-gap-1 md:afp-hidden afp-flex-shrink-0">
          @for (group of actionGroups(); track $index; let last = $last) {
            @for (item of group.items; track $index) {
              @if (item.type === 'button') {
                <afp-toolbar-button
                  [icon]="item.icon"
                  [label]="item.tooltip"
                  [onClick]="item.action"
                  [disabled]="!!item.disabled"
                  [active]="!!item.active"
                  [ariaKeyshortcuts]="item.ariaKeyshortcuts"
                />
              }
            }
          }
        </div>

        <div class="afp-hidden md:afp-flex afp-items-center afp-gap-1 afp-flex-shrink-0">
          @for (group of toolGroups(); track $index; let last = $last) {
            @for (item of group.items; track $index) {
              @if (item.type === 'button') {
                <afp-toolbar-button
                  [icon]="item.icon"
                  [label]="item.tooltip"
                  [onClick]="item.action"
                  [disabled]="!!item.disabled"
                  [active]="!!item.active"
                  [ariaKeyshortcuts]="item.ariaKeyshortcuts"
                />
              } @else {
                <span
                  class="afp-text-xs afp-text-center afp-font-medium afp-tabular-nums afp-text-fg-tertiary"
                  [style.minWidth]="item.minWidth || 'auto'"
                >
                  {{ item.content }}
                </span>
              }
            }
            @if (!last || actionGroups().length > 0) {
              <div class="afp-w-px afp-h-4 afp-mx-1 afp-bg-divide"></div>
            }
          }
          @for (group of actionGroups(); track $index) {
            @for (item of group.items; track $index) {
              @if (item.type === 'button') {
                <afp-toolbar-button
                  [icon]="item.icon"
                  [label]="item.tooltip"
                  [onClick]="item.action"
                  [disabled]="!!item.disabled"
                  [active]="!!item.active"
                  [ariaKeyshortcuts]="item.ariaKeyshortcuts"
                />
              }
            }
          }
        </div>
      </div>

      @if (toolGroups().length > 0) {
        <div class="afp-flex afp-items-center afp-gap-1 afp-px-3 afp-pb-1.5 afp-overflow-x-auto scrollbar-hide md:afp-hidden">
          @for (group of toolGroups(); track $index; let first = $first) {
            @if (!first) {
              <div class="afp-w-px afp-h-4 afp-mx-0.5 afp-bg-divide"></div>
            }
            @for (item of group.items; track $index) {
              @if (item.type === 'button') {
                <afp-toolbar-button
                  [icon]="item.icon"
                  [label]="item.tooltip"
                  [onClick]="item.action"
                  [disabled]="!!item.disabled"
                  [active]="!!item.active"
                  [ariaKeyshortcuts]="item.ariaKeyshortcuts"
                />
              } @else {
                <span
                  class="afp-text-xs afp-text-center afp-font-medium afp-tabular-nums afp-text-fg-tertiary"
                  [style.minWidth]="item.minWidth || 'auto'"
                >
                  {{ item.content }}
                </span>
              }
            }
          }
        </div>
      }
    </div>
  `,
})
export class FilePreviewToolbar {
  fileName = input.required<string>();
  currentIndex = input.required<number>();
  totalFiles = input.required<number>();
  toolGroups = input<ToolbarGroup[]>([]);
  t = input.required<Translator>();
  showClose = input(true);
  showDownload = input(true);
  download = output<void>();
  close = output<void>();

  protected readonly downloadIcon = Download;
  protected readonly closeIcon = X;

  readonly actionGroups = computed<ToolbarGroup[]>(() => {
    const groups: ToolbarGroup[] = [];
    const t = this.t();
    if (this.showDownload()) {
      groups.push({
        items: [
          {
            type: 'button',
            icon: Download,
            tooltip: t('accessibility.downloadFile') || t('common.download'),
            action: () => this.download.emit(),
          },
        ],
      });
    }
    if (this.showClose()) {
      groups.push({
        items: [
          {
            type: 'button',
            icon: X,
            tooltip: t('accessibility.closePreview') || t('common.close'),
            action: () => this.close.emit(),
            ariaKeyshortcuts: 'Escape',
          },
        ],
      });
    }
    return groups;
  });
}
