// packages/vue-file-preview/src/components/NavArrows.vue
<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount } from 'vue';
import { ChevronLeft, ChevronRight } from 'lucide-vue-next';

interface Props {
  /** 父级内容容器 DOM（mousemove 监听挂到它身上） */
  containerRef: HTMLDivElement | null;
  hasPrev: boolean;
  hasNext: boolean;
  /** 用于触发"显示并重置定时器"的外部信号,通常传 currentIndex */
  resetKey: number;
}

const props = defineProps<Props>();
const emit = defineEmits<{ prev: []; next: [] }>();

const NAV_HIDE_DELAY = 2000;
const visible = ref(true);
let hideTimer: number | null = null;

const scheduleHide = () => {
  if (hideTimer !== null) clearTimeout(hideTimer);
  hideTimer = window.setTimeout(() => {
    visible.value = false;
  }, NAV_HIDE_DELAY);
};

const show = () => {
  if (!visible.value) visible.value = true;
  scheduleHide();
};

let attached: HTMLDivElement | null = null;
const detach = () => {
  if (attached) {
    attached.removeEventListener('mousemove', show);
    attached = null;
  }
};
const attach = (el: HTMLDivElement | null) => {
  if (attached === el) return;
  detach();
  if (el) {
    el.addEventListener('mousemove', show);
    attached = el;
  }
};

watch(() => props.containerRef, (el) => attach(el), { immediate: true });
watch(() => props.resetKey, () => {
  visible.value = true;
  scheduleHide();
});

onMounted(() => {
  scheduleHide();
});

onBeforeUnmount(() => {
  if (hideTimer !== null) clearTimeout(hideTimer);
  detach();
});
</script>

<template>
  <button
    v-if="hasPrev"
    :style="{
      opacity: visible ? 1 : 0,
      transform: visible ? 'translateY(-50%)' : 'translateY(-50%) translateX(-20px)',
      pointerEvents: visible ? 'auto' : 'none',
      transition: 'opacity 0.2s, transform 0.2s',
    }"
    class="vfp-absolute vfp-z-20 vfp-left-2 md:vfp-left-4 vfp-top-1/2 vfp-w-10 vfp-h-10 md:vfp-w-12 md:vfp-h-12 vfp-rounded-full vfp-backdrop-blur-xl vfp-border vfp-flex vfp-items-center vfp-justify-center vfp-transition-colors vfp-shadow-2xl vfp-bg-surface-nav vfp-border-line hover:vfp-bg-surface-nav-hover vfp-text-fg-primary"
    @click="emit('prev')"
    @mouseenter="show"
  >
    <ChevronLeft class="vfp-w-5 vfp-h-5 md:vfp-w-6 md:vfp-h-6" />
  </button>

  <button
    v-if="hasNext"
    :style="{
      opacity: visible ? 1 : 0,
      transform: visible ? 'translateY(-50%)' : 'translateY(-50%) translateX(20px)',
      pointerEvents: visible ? 'auto' : 'none',
      transition: 'opacity 0.2s, transform 0.2s',
    }"
    class="vfp-absolute vfp-z-20 vfp-right-2 md:vfp-right-4 vfp-top-1/2 vfp-w-10 vfp-h-10 md:vfp-w-12 md:vfp-h-12 vfp-rounded-full vfp-backdrop-blur-xl vfp-border vfp-flex vfp-items-center vfp-justify-center vfp-transition-colors vfp-shadow-2xl vfp-bg-surface-nav vfp-border-line hover:vfp-bg-surface-nav-hover vfp-text-fg-primary"
    @click="emit('next')"
    @mouseenter="show"
  >
    <ChevronRight class="vfp-w-5 vfp-h-5 md:vfp-w-6 md:vfp-h-6" />
  </button>
</template>

// packages/angular-file-preview/src/components/preview/nav-arrows.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  effect,
  inject,
  input,
  output,
  signal,
} from '@angular/core';
import { ChevronLeft, ChevronRight } from 'lucide-angular';
import { LucideAngularModule } from 'lucide-angular';
import type { Translator } from '../../fp-core';

const NAV_HIDE_DELAY = 2000;

@Component({
  selector: 'afp-nav-arrows',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (hasPrev()) {
      <button
        type="button"
        class="afp-absolute afp-z-20 afp-left-2 md:afp-left-4 afp-top-1/2 afp-w-10 afp-h-10 md:afp-w-12 md:afp-h-12 afp-rounded-full afp-backdrop-blur-xl afp-border afp-flex afp-items-center afp-justify-center afp-shadow-2xl afp-bg-surface-nav afp-border-line hover:afp-bg-surface-nav-hover afp-text-fg-primary"
        [style.opacity]="visible() ? 1 : 0"
        [style.transform]="visible() ? 'translateY(-50%)' : 'translateY(-50%) translateX(-20px)'"
        [style.pointerEvents]="visible() ? 'auto' : 'none'"
        [style.transition]="'opacity 0.2s, transform 0.2s'"
        [attr.aria-label]="t()('accessibility.previousFile')"
        aria-keyshortcuts="ArrowLeft"
        (click)="prev.emit()"
        (mouseenter)="show()"
      >
        <i-lucide [img]="chevronLeft" class="afp-w-5 afp-h-5 md:afp-w-6 md:afp-h-6" />
      </button>
    }
    @if (hasNext()) {
      <button
        type="button"
        class="afp-absolute afp-z-20 afp-right-2 md:afp-right-4 afp-top-1/2 afp-w-10 afp-h-10 md:afp-w-12 md:afp-h-12 afp-rounded-full afp-backdrop-blur-xl afp-border afp-flex afp-items-center afp-justify-center afp-shadow-2xl afp-bg-surface-nav afp-border-line hover:afp-bg-surface-nav-hover afp-text-fg-primary"
        [style.opacity]="visible() ? 1 : 0"
        [style.transform]="visible() ? 'translateY(-50%)' : 'translateY(-50%) translateX(20px)'"
        [style.pointerEvents]="visible() ? 'auto' : 'none'"
        [style.transition]="'opacity 0.2s, transform 0.2s'"
        [attr.aria-label]="t()('accessibility.nextFile')"
        aria-keyshortcuts="ArrowRight"
        (click)="next.emit()"
        (mouseenter)="show()"
      >
        <i-lucide [img]="chevronRight" class="afp-w-5 afp-h-5 md:afp-w-6 md:afp-h-6" />
      </button>
    }
  `,
})
export class NavArrows {
  container = input<HTMLElement | null>(null);
  hasPrev = input(false);
  hasNext = input(false);
  resetKey = input(0);
  t = input.required<Translator>();
  prev = output<void>();
  next = output<void>();

  protected readonly chevronLeft = ChevronLeft;
  protected readonly chevronRight = ChevronRight;
  readonly visible = signal(true);

  private hideTimer: number | null = null;
  private attached: HTMLElement | null = null;
  private readonly destroyRef = inject(DestroyRef);

  constructor() {
    this.destroyRef.onDestroy(() => {
      this.clearTimer();
      this.detach();
    });

    effect(() => {
      this.attach(this.container());
    });

    effect(() => {
      this.resetKey();
      this.visible.set(true);
      this.scheduleHide();
    });
  }

  show = (): void => {
    if (!this.visible()) this.visible.set(true);
    this.scheduleHide();
  };

  private scheduleHide(): void {
    this.clearTimer();
    this.hideTimer = window.setTimeout(() => this.visible.set(false), NAV_HIDE_DELAY);
  }

  private clearTimer(): void {
    if (this.hideTimer !== null) {
      clearTimeout(this.hideTimer);
      this.hideTimer = null;
    }
  }

  private detach(): void {
    if (this.attached) {
      this.attached.removeEventListener('mousemove', this.show);
      this.attached = null;
    }
  }

  private attach(el: HTMLElement | null): void {
    if (this.attached === el) return;
    this.detach();
    if (el) {
      el.addEventListener('mousemove', this.show);
      this.attached = el;
    }
  }
}
