// packages/react-file-preview/src/components/preview/ToolbarButton.tsx
import React from 'react';

export interface ToolbarButtonProps {
  icon: React.ReactNode;
  label: string;
  onClick: () => void;
  disabled?: boolean;
  ariaKeyshortcuts?: string;
}

/**
 * 工具栏按钮组件
 * 支持 tooltip、disabled 状态和 aria 属性
 */
export const ToolbarButton: React.FC<ToolbarButtonProps> = ({
  icon,
  label,
  onClick,
  disabled,
  ariaKeyshortcuts,
}) => {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      aria-label={label}
      aria-keyshortcuts={ariaKeyshortcuts}
      aria-disabled={disabled}
      className={`rfp-relative rfp-group rfp-p-2 md:rfp-p-1.5 rfp-rounded-md rfp-transition-all rfp-select-none ${
        disabled
          ? 'rfp-text-fg-disabled rfp-cursor-not-allowed'
          : 'rfp-text-fg-primary hover:rfp-bg-surface-2 active:rfp-bg-surface-3'
      }`}
    >
      {icon}
      <span className="rfp-absolute rfp-left-1/2 -rfp-translate-x-1/2 rfp-top-full rfp-mt-1.5 rfp-px-2 rfp-py-1 rfp-text-xs rfp-rounded rfp-whitespace-nowrap rfp-pointer-events-none rfp-opacity-0 rfp-invisible group-hover:rfp-opacity-100 group-hover:rfp-visible rfp-transition-opacity rfp-duration-200 rfp-z-50 rfp-bg-fg-primary rfp-text-fg-inverse max-[1023px]:!rfp-hidden">
        <span className="rfp-absolute rfp-left-1/2 -rfp-translate-x-1/2 -rfp-top-1 rfp-w-2 rfp-h-2 rfp-rotate-45 rfp-bg-fg-primary" />
        <span className="rfp-relative">{label}</span>
      </span>
    </button>
  );
};

// packages/angular-file-preview/src/components/preview/toolbar-button.ts
import {
  ChangeDetectionStrategy,
  Component,
  input,
} from '@angular/core';
import { LucideAngularModule } from 'lucide-angular';
import type { LucideIconData } from 'lucide-angular';

@Component({
  selector: 'afp-toolbar-button',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      type="button"
      [disabled]="disabled()"
      [attr.aria-label]="label()"
      [attr.aria-pressed]="active()"
      [attr.aria-keyshortcuts]="ariaKeyshortcuts() || null"
      [attr.aria-disabled]="disabled()"
      class="toolbar-btn"
      [class.active]="active()"
      (click)="onClick()()"
    >
      <i-lucide [img]="icon()" class="afp-w-4 afp-h-4" />
      <span class="toolbar-tooltip" aria-hidden="true">
        <span class="toolbar-tooltip-arrow"></span>
        <span class="toolbar-tooltip-label">{{ label() }}</span>
      </span>
    </button>
  `,
  styles: [`
    :host { display: contents; }
    .toolbar-btn {
      position: relative;
      padding: 0.5rem;
      border-radius: 0.375rem;
      transition: all 0.15s;
      user-select: none;
      color: var(--fp-fg-primary);
      background: transparent;
      border: 0;
      cursor: pointer;
    }
    @media (min-width: 768px) {
      .toolbar-btn { padding: 0.375rem; }
    }
    .toolbar-btn:hover { background: var(--fp-surface-2); }
    .toolbar-btn:active { background: var(--fp-surface-3); }
    .toolbar-btn.active,
    .toolbar-btn.active:hover,
    .toolbar-btn.active:active { background: var(--fp-surface-3); }
    .toolbar-btn:disabled {
      color: var(--fp-fg-disabled);
      cursor: not-allowed;
    }
    .toolbar-tooltip {
      position: absolute;
      left: 50%;
      top: 100%;
      transform: translateX(-50%);
      margin-top: 6px;
      padding: 4px 8px;
      background: var(--fp-fg-primary);
      color: var(--fp-fg-inverse);
      font-size: 12px;
      line-height: 1.5;
      border-radius: 4px;
      white-space: nowrap;
      pointer-events: none;
      opacity: 0;
      visibility: hidden;
      transition: opacity 0.2s, visibility 0.2s;
      z-index: 50;
    }

    .toolbar-tooltip-arrow {
      position: absolute;
      left: 50%;
      top: -4px;
      width: 8px;
      height: 8px;
      transform: translateX(-50%) rotate(45deg);
      background: var(--fp-fg-primary);
    }

    .toolbar-tooltip-label {
      position: relative;
    }

    .toolbar-btn:hover .toolbar-tooltip {
      opacity: 1;
      visibility: visible;
    }
    @media (max-width: 1023px) {
      .toolbar-tooltip {
        display: none !important;
      }
    }
  `],
})
export class ToolbarButton {
  icon = input.required<LucideIconData>();
  label = input.required<string>();
  onClick = input.required<() => void>();
  disabled = input(false);
  active = input(false);
  ariaKeyshortcuts = input<string | undefined>(undefined);
}
