// packages/vue-file-preview/src/renderers/Cad/index.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls';
import { DXFLoader } from 'three-dxf-loader';
import { STLLoader } from 'three/examples/jsm/loaders/STLLoader';
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { useTranslator } from '../../composables/useTranslator';
import { useFetcher } from '../../composables/useRequest';
import RendererError from '../RendererError.vue';
import { ToolbarEventEmitter } from '../base.types';
import type { RendererHandle } from '../base.types';
import { getCadToolbarGroups } from './toolbar';

const getAssetBasePath = (url: string): string => {
  if (!url || url.startsWith('blob:') || url.startsWith('data:')) return '';
  try {
    return new URL('.', new URL(url, document.baseURI)).href;
  } catch {
    return '';
  }
};

const fitCameraToModel = (
  camera: THREE.PerspectiveCamera,
  controls: OrbitControls,
  center: THREE.Vector3,
  maxDim: number,
) => {
  const safeMaxDim = Number.isFinite(maxDim) && maxDim > 0 ? maxDim : 1;
  const fov = camera.fov * (Math.PI / 180);
  const cameraZ = Math.abs(safeMaxDim / 2 / Math.tan(fov / 2)) * 1.5;

  camera.near = Math.max(safeMaxDim * 1e-3, 1e-4);
  camera.far = Math.max(cameraZ * 4, center.length() * 2 + safeMaxDim * 4, camera.near * 100);
  camera.position.set(center.x + cameraZ, center.y + cameraZ, center.z + cameraZ);
  camera.lookAt(center);
  controls.target.copy(center);
  controls.update();
  camera.updateProjectionMatrix();
};

interface Props {
  url: string;
  file?: File;
  fileName?: string;
  baseUrl?: string;
}

const props = defineProps<Props>();
const { t } = useTranslator();
const fetcher = useFetcher();

const containerRef = ref<HTMLDivElement | null>(null);
const loading = ref(true);
const error = ref<string | null>(null);
const wireframe = ref(false);
const showGrid = ref(true);
const showAxes = ref(true);

let scene: THREE.Scene | null = null;
let camera: THREE.PerspectiveCamera | null = null;
let renderer: THREE.WebGLRenderer | null = null;
let controls: OrbitControls | null = null;
let model: THREE.Object3D | null = null;
let grid: THREE.GridHelper | null = null;
let axes: THREE.AxesHelper | null = null;
let animationId: number | null = null;
let abortController: AbortController | null = null;
let isCleanedUp = false;
let renderPending = true;

const toolbarEmitter = new ToolbarEventEmitter();

// 获取文件扩展名
const getExtension = (url: string, fileName?: string, file?: File): string => {
  // 优先从 file.name 获取
  if (file?.name) {
    return file.name.split('.').pop()?.toLowerCase() || '';
  }
  // 其次从 fileName 获取
  if (fileName) {
    return fileName.split('.').pop()?.toLowerCase() || '';
  }
  // 最后从 URL 获取（但 blob URL 没有扩展名）
  return url.split('.').pop()?.toLowerCase().split('?')[0] || '';
};

// 重置视图
const resetView = () => {
  if (!controls || !camera || !model) return;

  const box = new THREE.Box3().setFromObject(model);
  const center = box.getCenter(new THREE.Vector3());
  const size = box.getSize(new THREE.Vector3());
  const maxDim = Math.max(size.x, size.y, size.z);
  fitCameraToModel(camera, controls, center, maxDim);
  renderPending = true;
};

// 切换线框模式
const toggleWireframe = () => {
  wireframe.value = !wireframe.value;
  if (model) {
    model.traverse((child: any) => {
      if (child instanceof THREE.Mesh) {
        const material = child.material;
        if (material) {
          if (Array.isArray(material)) {
            material.forEach((mat: any) => {
              mat.wireframe = wireframe.value;
            });
          } else {
            material.wireframe = wireframe.value;
          }
        }
      }
    });
  }
  renderPending = true;
  toolbarEmitter.notify();
};

// 切换网格
const toggleGrid = () => {
  showGrid.value = !showGrid.value;
  if (grid) {
    grid.visible = showGrid.value;
  }
  renderPending = true;
  toolbarEmitter.notify();
};

// 切换坐标轴
const toggleAxes = () => {
  showAxes.value = !showAxes.value;
  if (axes) {
    axes.visible = showAxes.value;
  }
  renderPending = true;
  toolbarEmitter.notify();
};

// 根据模型包围盒调整参考物大小，避免 OBJ/STL 单位差异造成参考线比例失真
const updateReferenceHelpers = (box: THREE.Box3) => {
  if (!scene) return;

  const size = box.getSize(new THREE.Vector3());
  const maxDim = Math.max(size.x, size.y, size.z);
  const safeMaxDim = Number.isFinite(maxDim) && maxDim > 0 ? maxDim : 1;
  const rawExtent = Math.max(
    Math.abs(box.min.x), Math.abs(box.max.x),
    Math.abs(box.min.y), Math.abs(box.max.y),
    Math.abs(box.min.z), Math.abs(box.max.z),
  );
  const extent = Number.isFinite(rawExtent) ? rawExtent : safeMaxDim;
  const axesSize = Math.max(safeMaxDim, extent * 1.25);
  const gridSize = Math.max(safeMaxDim * 2, extent * 2.5);

  if (grid) {
    grid.geometry.dispose();
    (grid.material as any).dispose();
    scene.remove(grid);
  }
  if (axes) {
    axes.geometry.dispose();
    (axes.material as any).dispose();
    scene.remove(axes);
  }

  grid = new THREE.GridHelper(gridSize, 20, 0x444444, 0x222222);
  grid.visible = showGrid.value;
  scene.add(grid);

  axes = new THREE.AxesHelper(axesSize);
  axes.visible = showAxes.value;
  scene.add(axes);
};

// 暴露 RendererHandle 接口
defineExpose<RendererHandle>({
  getToolbarGroups: () => {
    return getCadToolbarGroups({
      cadRef: { resetView, toggleWireframe, toggleGrid, toggleAxes },
      wireframe: wireframe.value,
      showGrid: showGrid.value,
      showAxes: showAxes.value,
      t: t.value,
    });
  },
  onToolbarChange: (listener: () => void) => {
    return toolbarEmitter.subscribe(listener);
  },
});

// 释放 THREE.js 资源
const disposeThreeResources = (obj: THREE.Object3D) => {
  obj.traverse((child: any) => {
    if (child.geometry) {
      child.geometry.dispose();
    }
    if (child.material) {
      if (Array.isArray(child.material)) {
        child.material.forEach((mat: any) => {
          disposeMaterial(mat);
        });
      } else {
        disposeMaterial(child.material);
      }
    }
  });
};

const disposeMaterial = (material: any) => {
  if (material.map) material.map.dispose();
  if (material.lightMap) material.lightMap.dispose();
  if (material.bumpMap) material.bumpMap.dispose();
  if (material.normalMap) material.normalMap.dispose();
  if (material.specularMap) material.specularMap.dispose();
  if (material.envMap) material.envMap.dispose();
  material.dispose();
};

// 初始化场景
const initScene = () => {
  if (!containerRef.value) return;

  // 重置清理状态
  isCleanedUp = false;
  abortController = new AbortController();

  const container = containerRef.value;
  const width = container.clientWidth;
  const height = container.clientHeight;

  // 创建场景
  scene = new THREE.Scene();
  scene.background = new THREE.Color(0x1a1a1a);

  // 创建相机
  camera = new THREE.PerspectiveCamera(45, width / height, 0.01, 1_000_000);
  camera.position.set(100, 100, 100);

  // 创建渲染器
  renderer = new THREE.WebGLRenderer({ antialias: true });
  renderer.setSize(width, height);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderPending = true;
  container.appendChild(renderer.domElement);

  // 创建控制器
  controls = new OrbitControls(camera, renderer.domElement);
  controls.enableDamping = true;
  controls.dampingFactor = 0.05;

  // 添加灯光
  const ambientLight = new THREE.AmbientLight(0xffffff, 0.6);
  scene.add(ambientLight);

  const directionalLight1 = new THREE.DirectionalLight(0xffffff, 0.8);
  directionalLight1.position.set(1, 1, 1);
  scene.add(directionalLight1);

  const directionalLight2 = new THREE.DirectionalLight(0xffffff, 0.4);
  directionalLight2.position.set(-1, -1, -1);
  scene.add(directionalLight2);

  // 加载模型
  loadModel();

  // 动画循环
  const animate = () => {
    if (isCleanedUp) return;
    animationId = requestAnimationFrame(animate);
    const cameraChanged = controls?.update();
    if ((cameraChanged || renderPending) && scene && camera && renderer) {
      renderer.render(scene, camera);
      renderPending = false;
    }
  };
  animate();

  // 处理窗口大小变化
  window.addEventListener('resize', handleResize);
};

// 加载模型
const loadModel = () => {
  if (!scene || !camera || !controls || isCleanedUp) return;

  const ext = getExtension(props.url, props.fileName, props.file);
  let loader: any;

  // 创建 LoadingManager
  const manager = new THREE.LoadingManager();

  if (ext === 'dxf') {
    loader = new DXFLoader();
  } else if (ext === 'stl') {
    loader = new STLLoader(manager);
  } else if (ext === 'obj') {
    loader = new OBJLoader(manager);
  } else if (ext === 'gltf' || ext === 'glb') {
    loader = new GLTFLoader(manager);
  } else {
    error.value = t.value('cad.parse_failed');
    loading.value = false;
    return;
  }

  // 处理加载成功
  const handleLoadSuccess = (object: any, ext: string) => {
    if (isCleanedUp) return;

    // 验证对象有效性
    if (!object) {
      error.value = t.value('cad.parse_failed');
      loading.value = false;
      return;
    }

    let loadedModel: THREE.Object3D;

    if (ext === 'stl') {
      // STL 返回 geometry
      const geometry = object as THREE.BufferGeometry;
      const material = new THREE.MeshPhongMaterial({
        color: 0x888888,
        flatShading: true,
        side: THREE.DoubleSide,
      });
      loadedModel = new THREE.Mesh(geometry, material);
    } else if (ext === 'gltf' || ext === 'glb') {
      // GLTF/GLB 返回 { scene, ... }
      loadedModel = object.scene as THREE.Object3D;
      if (!loadedModel) {
        error.value = t.value('cad.parse_failed');
        loading.value = false;
        return;
      }
    } else {
      // DXF 和 OBJ 返回 Object3D
      loadedModel = object as THREE.Object3D;

      // 为没有材质的对象添加默认材质
      loadedModel.traverse((child: any) => {
        if (child instanceof THREE.Mesh && !child.material) {
          child.material = new THREE.MeshPhongMaterial({
            color: 0x888888,
            side: THREE.DoubleSide,
          });
        }
      });
    }

    const box = new THREE.Box3().setFromObject(loadedModel);
    if (box.isEmpty()) {
      error.value = t.value('cad.parse_failed');
      loading.value = false;
      return;
    }
    scene!.add(loadedModel);
    model = loadedModel;

    // 自动调整视角
    const center = box.getCenter(new THREE.Vector3());
    const size = box.getSize(new THREE.Vector3());
    const maxDim = Math.max(size.x, size.y, size.z);
    updateReferenceHelpers(box);
    fitCameraToModel(camera!, controls!, center, maxDim);
    renderPending = true;

    loading.value = false;
    toolbarEmitter.notify();
  };

  // 处理加载错误
  const handleLoadError = (err: any) => {
    if (isCleanedUp) return;
    if (err.name === 'AbortError') {
      return;
    }
    error.value = t.value('cad.load_failed');
    loading.value = false;
  };

  // 如果有 File 对象，直接读取；否则使用 fetcher
  const loadPromise = props.file
    ? props.file.arrayBuffer()
    : fetcher.value(props.url, { signal: abortController?.signal }).then(response => {
        if (isCleanedUp) return undefined;
        if (!response.ok) throw new Error('Failed to fetch file');
        return response.arrayBuffer();
      });

  loadPromise
    .then((data: ArrayBuffer | undefined) => {
      if (isCleanedUp || !data) return;

      if (ext === 'stl') {
        const object = loader.parse(data);
        handleLoadSuccess(object, ext);
      } else if (ext === 'obj') {
        // OBJLoader 需要字符串，转换 ArrayBuffer
        const decoder = new TextDecoder('utf-8');
        const text = decoder.decode(data);
        const object = loader.parse(text);
        handleLoadSuccess(object, ext);
      } else if (ext === 'gltf' || ext === 'glb') {
        loader.parse(
          data,
          getAssetBasePath(props.baseUrl || props.url),
          (gltf: any) => {
            if (!isCleanedUp) {
              handleLoadSuccess(gltf, ext);
            }
          },
          (err: any) => handleLoadError(err)
        );
      } else if (ext === 'dxf') {
        // DXFLoader 需要字符串
        const decoder = new TextDecoder('utf-8');
        const text = decoder.decode(data);

        // three-dxf-loader 对某些实体（如 3D polyface mesh）会生成 undefined 顶点，
        // 导致 THREE.BufferGeometry.setFromPoints 抛 "reading 'x'"。
        // 临时 patch 过滤坏点，加载完成后立即恢复。
        const origSetFromPoints = (THREE.BufferGeometry.prototype as any).setFromPoints;
        (THREE.BufferGeometry.prototype as any).setFromPoints = function (points: any[]) {
          const filtered = (points || []).filter(
            (p: any) => p && p.x !== undefined && p.y !== undefined
          );
          return origSetFromPoints.call(this, filtered);
        };

        try {
          (loader as any).loadString(
            text,
            (dxfData: any) => {
              if (!isCleanedUp) {
                // three-dxf-loader 返回的是 { entity: Object3D }
                const obj = dxfData?.entity || dxfData;
                handleLoadSuccess(obj, ext);
              }
            },
            (err: any) => {
              handleLoadError(err);
            }
          );
        } catch (err) {
          // loadString 可能同步抛出解析错误
          handleLoadError(err);
        } finally {
          (THREE.BufferGeometry.prototype as any).setFromPoints = origSetFromPoints;
        }
      }
    })
    .catch((err) => {
      if (!isCleanedUp) {
        handleLoadError(err);
      }
    });
};

// 处理窗口大小变化
const handleResize = () => {
  if (!containerRef.value || !camera || !renderer || isCleanedUp) return;
  const newWidth = containerRef.value.clientWidth;
  const newHeight = containerRef.value.clientHeight;
  camera.aspect = newWidth / newHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(newWidth, newHeight);
  renderPending = true;
};

// 清理
const cleanup = () => {
  isCleanedUp = true;
  if (abortController) {
    abortController.abort();
  }
  if (animationId !== null) {
    cancelAnimationFrame(animationId);
    animationId = null;
  }
  window.removeEventListener('resize', handleResize);

  // 释放 THREE.js 资源
  if (model) {
    disposeThreeResources(model);
    scene?.remove(model);
    model = null;
  }
  if (grid) {
    grid.geometry.dispose();
    (grid.material as any).dispose();
    scene?.remove(grid);
    grid = null;
  }
  if (axes) {
    axes.geometry.dispose();
    (axes.material as any).dispose();
    scene?.remove(axes);
    axes = null;
  }

  controls?.dispose();
  renderer?.dispose();
  if (containerRef.value && renderer?.domElement && containerRef.value.contains(renderer.domElement)) {
    containerRef.value.removeChild(renderer.domElement);
  }

  scene = null;
  camera = null;
  renderer = null;
  controls = null;
};

onMounted(() => {
  initScene();
});

onUnmounted(() => {
  cleanup();
});

watch(() => props.url, () => {
  cleanup();
  loading.value = true;
  error.value = null;
  if (containerRef.value) {
    initScene();
  }
});
</script>

<template>
  <div ref="containerRef" class="vfp-relative vfp-w-full vfp-h-full vfp-bg-media-bg">
    <!-- 错误覆盖层 -->
    <div v-if="error" class="vfp-absolute vfp-inset-0 vfp-bg-surface-3 vfp-z-10">
      <RendererError :message="error" />
    </div>

    <!-- 加载覆盖层 -->
    <div
      v-if="loading"
      class="vfp-absolute vfp-inset-0 vfp-renderer-loading vfp-bg-surface-3 vfp-z-10"
    >
      <div class="vfp-renderer-loading-content">
        <div class="vfp-renderer-spinner" />
        <p class="vfp-renderer-loading-text vfp-text-fg-secondary">{{ t('cad.loading') }}</p>
      </div>
    </div>
  </div>
</template>

// packages/angular-file-preview/src/renderers/Cad/index.ts
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  effect,
  ElementRef,
  inject,
  input,
  signal,
  untracked,
  viewChild,
} from '@angular/core';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
// @ts-expect-error three-dxf-loader has no types
import { DXFLoader } from 'three-dxf-loader';
import { STLLoader } from 'three/examples/jsm/loaders/STLLoader.js';
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { LocaleService, getFallbackTranslator } from '../../di/locale.service';
import { RequestService } from '../../di/request.service';
import { RendererError } from '../RendererError';
import { ToolbarEventEmitter } from '../base.types';
import type { RendererHandle } from '../base.types';
import type { ToolbarGroup } from '../toolbar.types';
import { getCadToolbarGroups } from './toolbar';

function getAssetBasePath(url: string): string {
  if (!url || url.startsWith('blob:') || url.startsWith('data:')) return '';
  try {
    return new URL('.', new URL(url, document.baseURI)).href;
  } catch {
    return '';
  }
}

function fitCameraToModel(
  camera: THREE.PerspectiveCamera,
  controls: OrbitControls,
  center: THREE.Vector3,
  maxDim: number,
): void {
  const safeMaxDim = Number.isFinite(maxDim) && maxDim > 0 ? maxDim : 1;
  const fov = camera.fov * (Math.PI / 180);
  const cameraZ = Math.abs(safeMaxDim / 2 / Math.tan(fov / 2)) * 1.5;

  camera.near = Math.max(safeMaxDim * 1e-3, 1e-4);
  camera.far = Math.max(cameraZ * 4, center.length() * 2 + safeMaxDim * 4, camera.near * 100);
  camera.position.set(center.x + cameraZ, center.y + cameraZ, center.z + cameraZ);
  camera.lookAt(center);
  controls.target.copy(center);
  controls.update();
  camera.updateProjectionMatrix();
}

@Component({
  selector: 'afp-cad-renderer',
  standalone: true,
  imports: [RendererError],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'afp-block afp-w-full afp-h-full' },
  template: `
    <div #containerRef class="afp-relative afp-w-full afp-h-full afp-bg-media-bg">
      @if (error()) {
        <afp-renderer-error [message]="error()!" class="afp-absolute afp-inset-0 afp-bg-surface-3 afp-z-10" />
      }

      @if (loading()) {
        <div class="afp-absolute afp-inset-0 afp-renderer-loading afp-bg-surface-3 afp-z-10">
          <div class="afp-renderer-loading-content">
            <div class="afp-renderer-spinner"></div>
            <p class="afp-renderer-loading-text afp-text-fg-secondary">{{ t('cad.loading') }}</p>
          </div>
        </div>
      }
    </div>
  `,
})
export class CadRenderer implements RendererHandle {
  url = input.required<string>();
  file = input<File | undefined>(undefined);
  fileName = input<string | undefined>(undefined);
  baseUrl = input<string | undefined>(undefined);

  private readonly locale = inject(LocaleService, { optional: true });
  private readonly request = inject(RequestService, { optional: true });
  protected readonly t = this.locale?.t() ?? getFallbackTranslator();
  private readonly container = viewChild<ElementRef<HTMLDivElement>>('containerRef');
  private readonly toolbarEmitter = new ToolbarEventEmitter();
  private readonly mounted = signal(false);

  readonly loading = signal(true);
  readonly error = signal<string | null>(null);
  readonly wireframe = signal(false);
  readonly showGrid = signal(true);
  readonly showAxes = signal(true);

  private scene: THREE.Scene | null = null;
  private camera: THREE.PerspectiveCamera | null = null;
  private renderer: THREE.WebGLRenderer | null = null;
  private controls: OrbitControls | null = null;
  private model: THREE.Object3D | null = null;
  private grid: THREE.GridHelper | null = null;
  private axes: THREE.AxesHelper | null = null;
  private animationId: number | null = null;
  private abortController: AbortController | null = null;
  private isCleanedUp = false;
  private renderPending = true;

  constructor() {
    afterNextRender(() => this.mounted.set(true));

    effect(() => {
      const url = this.url();
      const mounted = this.mounted();
      if (!mounted || !url) return;
      untracked(() => {
        this.cleanup();
        this.loading.set(true);
        this.error.set(null);
        this.initScene();
      });
    });

    inject(DestroyRef).onDestroy(() => this.cleanup());
  }

  getToolbarGroups = (): ToolbarGroup[] => {
    return getCadToolbarGroups({
      cadRef: {
        resetView: () => this.resetView(),
        toggleWireframe: () => this.toggleWireframe(),
        toggleGrid: () => this.toggleGrid(),
        toggleAxes: () => this.toggleAxes(),
      },
      wireframe: this.wireframe(),
      showGrid: this.showGrid(),
      showAxes: this.showAxes(),
      t: this.t,
    });
  };

  onToolbarChange = (listener: () => void) => this.toolbarEmitter.subscribe(listener);

  private getExtension(url: string, fileName?: string, file?: File): string {
    if (file?.name) {
      return file.name.split('.').pop()?.toLowerCase() || '';
    }
    if (fileName) {
      return fileName.split('.').pop()?.toLowerCase() || '';
    }
    return url.split('.').pop()?.toLowerCase().split('?')[0] || '';
  }

  private resetView(): void {
    if (!this.controls || !this.camera || !this.model) return;

    const box = new THREE.Box3().setFromObject(this.model);
    const center = box.getCenter(new THREE.Vector3());
    const size = box.getSize(new THREE.Vector3());
    const maxDim = Math.max(size.x, size.y, size.z);
    fitCameraToModel(this.camera, this.controls, center, maxDim);
    this.renderPending = true;
  }

  private toggleWireframe(): void {
    this.wireframe.update((v) => !v);
    const wf = this.wireframe();
    if (this.model) {
      this.model.traverse((child: any) => {
        if (child instanceof THREE.Mesh) {
          const material = child.material;
          if (material) {
            if (Array.isArray(material)) {
              material.forEach((mat: any) => {
                mat.wireframe = wf;
              });
            } else {
              material.wireframe = wf;
            }
          }
        }
      });
    }
    this.renderPending = true;
    this.toolbarEmitter.notify();
  }

  private toggleGrid(): void {
    this.showGrid.update((v) => !v);
    if (this.grid) {
      this.grid.visible = this.showGrid();
    }
    this.renderPending = true;
    this.toolbarEmitter.notify();
  }

  private toggleAxes(): void {
    this.showAxes.update((v) => !v);
    if (this.axes) {
      this.axes.visible = this.showAxes();
    }
    this.renderPending = true;
    this.toolbarEmitter.notify();
  }

  // 根据模型包围盒调整参考物大小，避免 OBJ/STL 单位差异造成参考线比例失真
  private updateReferenceHelpers(box: THREE.Box3): void {
    if (!this.scene) return;

    const size = box.getSize(new THREE.Vector3());
    const maxDim = Math.max(size.x, size.y, size.z);
    const safeMaxDim = Number.isFinite(maxDim) && maxDim > 0 ? maxDim : 1;
    const rawExtent = Math.max(
      Math.abs(box.min.x), Math.abs(box.max.x),
      Math.abs(box.min.y), Math.abs(box.max.y),
      Math.abs(box.min.z), Math.abs(box.max.z),
    );
    const extent = Number.isFinite(rawExtent) ? rawExtent : safeMaxDim;
    const axesSize = Math.max(safeMaxDim, extent * 1.25);
    const gridSize = Math.max(safeMaxDim * 2, extent * 2.5);

    if (this.grid) {
      this.grid.geometry.dispose();
      (this.grid.material as any).dispose();
      this.scene.remove(this.grid);
    }
    if (this.axes) {
      this.axes.geometry.dispose();
      (this.axes.material as any).dispose();
      this.scene.remove(this.axes);
    }

    this.grid = new THREE.GridHelper(gridSize, 20, 0x444444, 0x222222);
    this.grid.visible = this.showGrid();
    this.scene.add(this.grid);

    this.axes = new THREE.AxesHelper(axesSize);
    this.axes.visible = this.showAxes();
    this.scene.add(this.axes);
  }

  private disposeMaterial(material: any): void {
    if (material.map) material.map.dispose();
    if (material.lightMap) material.lightMap.dispose();
    if (material.bumpMap) material.bumpMap.dispose();
    if (material.normalMap) material.normalMap.dispose();
    if (material.specularMap) material.specularMap.dispose();
    if (material.envMap) material.envMap.dispose();
    material.dispose();
  }

  private disposeThreeResources(obj: THREE.Object3D): void {
    obj.traverse((child: any) => {
      if (child.geometry) {
        child.geometry.dispose();
      }
      if (child.material) {
        if (Array.isArray(child.material)) {
          child.material.forEach((mat: any) => {
            this.disposeMaterial(mat);
          });
        } else {
          this.disposeMaterial(child.material);
        }
      }
    });
  }

  private initScene(): void {
    const container = this.container()?.nativeElement;
    if (!container) return;

    this.isCleanedUp = false;
    this.abortController = new AbortController();

    const width = container.clientWidth;
    const height = container.clientHeight;

    this.scene = new THREE.Scene();
    this.scene.background = new THREE.Color(0x1a1a1a);

    this.camera = new THREE.PerspectiveCamera(45, width / height, 0.01, 1_000_000);
    this.camera.position.set(100, 100, 100);

    this.renderer = new THREE.WebGLRenderer({ antialias: true });
    this.renderer.setSize(width, height);
    this.renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    this.renderPending = true;
    container.appendChild(this.renderer.domElement);

    this.controls = new OrbitControls(this.camera, this.renderer.domElement);
    this.controls.enableDamping = true;
    this.controls.dampingFactor = 0.05;

    const ambientLight = new THREE.AmbientLight(0xffffff, 0.6);
    this.scene.add(ambientLight);

    const directionalLight1 = new THREE.DirectionalLight(0xffffff, 0.8);
    directionalLight1.position.set(1, 1, 1);
    this.scene.add(directionalLight1);

    const directionalLight2 = new THREE.DirectionalLight(0xffffff, 0.4);
    directionalLight2.position.set(-1, -1, -1);
    this.scene.add(directionalLight2);

    this.loadModel();

    const animate = () => {
      if (this.isCleanedUp) return;
      this.animationId = requestAnimationFrame(animate);
      const cameraChanged = this.controls?.update();
      if ((cameraChanged || this.renderPending) && this.scene && this.camera && this.renderer) {
        this.renderer.render(this.scene, this.camera);
        this.renderPending = false;
      }
    };
    animate();

    window.addEventListener('resize', this.handleResize);
  }

  private loadModel(): void {
    if (!this.scene || !this.camera || !this.controls || this.isCleanedUp) return;

    const ext = this.getExtension(this.url(), this.fileName(), this.file());
    let loader: any;

    const manager = new THREE.LoadingManager();

    if (ext === 'dxf') {
      loader = new DXFLoader();
    } else if (ext === 'stl') {
      loader = new STLLoader(manager);
    } else if (ext === 'obj') {
      loader = new OBJLoader(manager);
    } else if (ext === 'gltf' || ext === 'glb') {
      loader = new GLTFLoader(manager);
    } else {
      this.error.set(this.t('cad.parse_failed'));
      this.loading.set(false);
      return;
    }

    const handleLoadSuccess = (object: any, loadedExt: string) => {
      if (this.isCleanedUp) return;

      if (!object) {
        this.error.set(this.t('cad.parse_failed'));
        this.loading.set(false);
        return;
      }

      let loadedModel: THREE.Object3D;

      if (loadedExt === 'stl') {
        const geometry = object as THREE.BufferGeometry;
        const material = new THREE.MeshPhongMaterial({
          color: 0x888888,
          flatShading: true,
          side: THREE.DoubleSide,
        });
        loadedModel = new THREE.Mesh(geometry, material);
      } else if (loadedExt === 'gltf' || loadedExt === 'glb') {
        loadedModel = object.scene as THREE.Object3D;
        if (!loadedModel) {
          this.error.set(this.t('cad.parse_failed'));
          this.loading.set(false);
          return;
        }
      } else {
        loadedModel = object as THREE.Object3D;

        loadedModel.traverse((child: any) => {
          if (child instanceof THREE.Mesh && !child.material) {
            child.material = new THREE.MeshPhongMaterial({
              color: 0x888888,
              side: THREE.DoubleSide,
            });
          }
        });
      }

      const box = new THREE.Box3().setFromObject(loadedModel);
      if (box.isEmpty()) {
        this.error.set(this.t('cad.parse_failed'));
        this.loading.set(false);
        return;
      }
      this.scene!.add(loadedModel);
      this.model = loadedModel;

      const center = box.getCenter(new THREE.Vector3());
      const size = box.getSize(new THREE.Vector3());
      const maxDim = Math.max(size.x, size.y, size.z);
      this.updateReferenceHelpers(box);
      fitCameraToModel(this.camera!, this.controls!, center, maxDim);
      this.renderPending = true;

      this.loading.set(false);
      this.toolbarEmitter.notify();
    };

    const handleLoadError = (err: any) => {
      if (this.isCleanedUp) return;
      if (err.name === 'AbortError') {
        return;
      }
      this.error.set(this.t('cad.load_failed'));
      this.loading.set(false);
    };

    const file = this.file();
    const fetcher = this.request?.fetcher() ?? ((u: string, init?: RequestInit) => fetch(u, init));
    const loadPromise = file
      ? file.arrayBuffer()
      : fetcher(this.url(), { signal: this.abortController?.signal }).then(response => {
          if (this.isCleanedUp) return undefined;
          if (!response.ok) throw new Error('Failed to fetch file');
          return response.arrayBuffer();
        });

    loadPromise
      .then((data: ArrayBuffer | undefined) => {
        if (this.isCleanedUp || !data) return;

        if (ext === 'stl') {
          const object = loader.parse(data);
          handleLoadSuccess(object, ext);
        } else if (ext === 'obj') {
          const decoder = new TextDecoder('utf-8');
          const text = decoder.decode(data);
          const object = loader.parse(text);
          handleLoadSuccess(object, ext);
        } else if (ext === 'gltf' || ext === 'glb') {
          loader.parse(
            data,
            getAssetBasePath(this.baseUrl() || this.url()),
            (gltf: any) => {
              if (!this.isCleanedUp) {
                handleLoadSuccess(gltf, ext);
              }
            },
            (err: any) => handleLoadError(err),
          );
        } else if (ext === 'dxf') {
          const decoder = new TextDecoder('utf-8');
          const text = decoder.decode(data);

          const origSetFromPoints = (THREE.BufferGeometry.prototype as any).setFromPoints;
          (THREE.BufferGeometry.prototype as any).setFromPoints = function (points: any[]) {
            const filtered = (points || []).filter(
              (p: any) => p && p.x !== undefined && p.y !== undefined,
            );
            return origSetFromPoints.call(this, filtered);
          };

          try {
            (loader as any).loadString(
              text,
              (dxfData: any) => {
                if (!this.isCleanedUp) {
                  const obj = dxfData?.entity || dxfData;
                  handleLoadSuccess(obj, ext);
                }
              },
              (err: any) => {
                handleLoadError(err);
              },
            );
          } catch (err) {
            handleLoadError(err);
          } finally {
            (THREE.BufferGeometry.prototype as any).setFromPoints = origSetFromPoints;
          }
        }
      })
      .catch((err) => {
        if (!this.isCleanedUp) {
          handleLoadError(err);
        }
      });
  }

  private readonly handleResize = (): void => {
    const container = this.container()?.nativeElement;
    if (!container || !this.camera || !this.renderer || this.isCleanedUp) return;
    const newWidth = container.clientWidth;
    const newHeight = container.clientHeight;
    this.camera.aspect = newWidth / newHeight;
    this.camera.updateProjectionMatrix();
    this.renderer.setSize(newWidth, newHeight);
  };

  private cleanup(): void {
    this.isCleanedUp = true;
    if (this.abortController) {
      this.abortController.abort();
    }
    if (this.animationId !== null) {
      cancelAnimationFrame(this.animationId);
      this.animationId = null;
    }
    window.removeEventListener('resize', this.handleResize);

    if (this.model) {
      this.disposeThreeResources(this.model);
      this.scene?.remove(this.model);
      this.model = null;
    }
    if (this.grid) {
      this.grid.geometry.dispose();
      (this.grid.material as any).dispose();
      this.scene?.remove(this.grid);
      this.grid = null;
    }
    if (this.axes) {
      this.axes.geometry.dispose();
      (this.axes.material as any).dispose();
      this.scene?.remove(this.axes);
      this.axes = null;
    }

    this.controls?.dispose();
    this.renderer?.dispose();
    const container = this.container()?.nativeElement;
    if (container && this.renderer?.domElement && container.contains(this.renderer.domElement)) {
      container.removeChild(this.renderer.domElement);
    }

    this.scene = null;
    this.camera = null;
    this.renderer = null;
    this.controls = null;
  }
}
