// packages/angular-file-preview/src/components/preview/nav-arrows.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  effect,
  inject,
  input,
  output,
  signal,
} from '@angular/core';
import { ChevronLeft, ChevronRight } from 'lucide-angular';
import { LucideAngularModule } from 'lucide-angular';
import type { Translator } from '../../fp-core';

const NAV_HIDE_DELAY = 2000;

@Component({
  selector: 'afp-nav-arrows',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (hasPrev()) {
      <button
        type="button"
        class="afp-absolute afp-z-20 afp-left-2 md:afp-left-4 afp-top-1/2 afp-w-10 afp-h-10 md:afp-w-12 md:afp-h-12 afp-rounded-full afp-backdrop-blur-xl afp-border afp-flex afp-items-center afp-justify-center afp-shadow-2xl afp-bg-surface-nav afp-border-line hover:afp-bg-surface-nav-hover afp-text-fg-primary"
        [style.opacity]="visible() ? 1 : 0"
        [style.transform]="visible() ? 'translateY(-50%)' : 'translateY(-50%) translateX(-20px)'"
        [style.pointerEvents]="visible() ? 'auto' : 'none'"
        [style.transition]="'opacity 0.2s, transform 0.2s'"
        [attr.aria-label]="t()('accessibility.previousFile')"
        aria-keyshortcuts="ArrowLeft"
        (click)="prev.emit()"
        (mouseenter)="show()"
      >
        <i-lucide [img]="chevronLeft" class="afp-w-5 afp-h-5 md:afp-w-6 md:afp-h-6" />
      </button>
    }
    @if (hasNext()) {
      <button
        type="button"
        class="afp-absolute afp-z-20 afp-right-2 md:afp-right-4 afp-top-1/2 afp-w-10 afp-h-10 md:afp-w-12 md:afp-h-12 afp-rounded-full afp-backdrop-blur-xl afp-border afp-flex afp-items-center afp-justify-center afp-shadow-2xl afp-bg-surface-nav afp-border-line hover:afp-bg-surface-nav-hover afp-text-fg-primary"
        [style.opacity]="visible() ? 1 : 0"
        [style.transform]="visible() ? 'translateY(-50%)' : 'translateY(-50%) translateX(20px)'"
        [style.pointerEvents]="visible() ? 'auto' : 'none'"
        [style.transition]="'opacity 0.2s, transform 0.2s'"
        [attr.aria-label]="t()('accessibility.nextFile')"
        aria-keyshortcuts="ArrowRight"
        (click)="next.emit()"
        (mouseenter)="show()"
      >
        <i-lucide [img]="chevronRight" class="afp-w-5 afp-h-5 md:afp-w-6 md:afp-h-6" />
      </button>
    }
  `,
})
export class NavArrows {
  container = input<HTMLElement | null>(null);
  hasPrev = input(false);
  hasNext = input(false);
  resetKey = input(0);
  t = input.required<Translator>();
  prev = output<void>();
  next = output<void>();

  protected readonly chevronLeft = ChevronLeft;
  protected readonly chevronRight = ChevronRight;
  readonly visible = signal(true);

  private hideTimer: number | null = null;
  private attached: HTMLElement | null = null;
  private readonly destroyRef = inject(DestroyRef);

  constructor() {
    this.destroyRef.onDestroy(() => {
      this.clearTimer();
      this.detach();
    });

    effect(() => {
      this.attach(this.container());
    });

    effect(() => {
      this.resetKey();
      this.visible.set(true);
      this.scheduleHide();
    });
  }

  show = (): void => {
    if (!this.visible()) this.visible.set(true);
    this.scheduleHide();
  };

  private scheduleHide(): void {
    this.clearTimer();
    this.hideTimer = window.setTimeout(() => this.visible.set(false), NAV_HIDE_DELAY);
  }

  private clearTimer(): void {
    if (this.hideTimer !== null) {
      clearTimeout(this.hideTimer);
      this.hideTimer = null;
    }
  }

  private detach(): void {
    if (this.attached) {
      this.attached.removeEventListener('mousemove', this.show);
      this.attached = null;
    }
  }

  private attach(el: HTMLElement | null): void {
    if (this.attached === el) return;
    this.detach();
    if (el) {
      el.addEventListener('mousemove', this.show);
      this.attached = el;
    }
  }
}

// packages/react-file-preview/src/components/preview/NavArrows.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { motion } from 'framer-motion';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import type { Translator } from '@eternalheart/file-preview-core';

export interface NavArrowsProps {
  containerRef: React.RefObject<HTMLDivElement | null>;
  hasPrev: boolean;
  hasNext: boolean;
  onPrev: () => void;
  onNext: () => void;
  resetKey: number;
  t: Translator;
}

const NAV_HIDE_DELAY = 2000;

/**
 * 导航箭头组件
 * 自带 mousemove 监听 + 2s 自动隐藏定时器
 * state 隔离在本组件，避免父组件因 navVisible 变化而 re-render
 */
export const NavArrows: React.FC<NavArrowsProps> = ({
  containerRef,
  hasPrev,
  hasNext,
  onPrev,
  onNext,
  resetKey,
  t,
}) => {
  const [visible, setVisible] = useState(true);
  const timerRef = useRef<number | null>(null);

  const scheduleHide = useCallback(() => {
    if (timerRef.current) clearTimeout(timerRef.current);
    timerRef.current = window.setTimeout(() => setVisible(false), NAV_HIDE_DELAY);
  }, []);

  const show = useCallback(() => {
    setVisible((prev) => (prev ? prev : true));
    scheduleHide();
  }, [scheduleHide]);

  // 监听容器的 mousemove，触发显示 + 重置隐藏定时器
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const handler = () => show();
    el.addEventListener('mousemove', handler);
    return () => {
      el.removeEventListener('mousemove', handler);
    };
  }, [containerRef, show]);

  // currentIndex 切换时，显示一次并重置定时器
  useEffect(() => {
    setVisible(true);
    scheduleHide();
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [resetKey, scheduleHide]);

  return (
    <>
      {hasPrev && (
        <motion.button
          initial={{ opacity: 0 }}
          animate={{ opacity: visible ? 1 : 0, x: visible ? 0 : -20 }}
          transition={{ duration: 0.2 }}
          onClick={onPrev}
          onMouseEnter={show}
          style={{ pointerEvents: visible ? 'auto' : 'none' }}
          aria-label={t('accessibility.previousFile') || '上一个文件'}
          aria-keyshortcuts="ArrowLeft"
          className="rfp-absolute rfp-z-20 rfp-left-2 md:rfp-left-4 rfp-top-1/2 -rfp-translate-y-1/2 rfp-w-10 rfp-h-10 md:rfp-w-12 md:rfp-h-12 rfp-rounded-full rfp-backdrop-blur-xl rfp-border rfp-flex rfp-items-center rfp-justify-center rfp-transition-colors rfp-shadow-2xl rfp-bg-surface-nav rfp-border-line hover:rfp-bg-surface-nav-hover rfp-text-fg-primary"
        >
          <ChevronLeft className="rfp-w-5 rfp-h-5 md:rfp-w-6 md:rfp-h-6" />
        </motion.button>
      )}
      {hasNext && (
        <motion.button
          initial={{ opacity: 0 }}
          animate={{ opacity: visible ? 1 : 0, x: visible ? 0 : 20 }}
          transition={{ duration: 0.2 }}
          onClick={onNext}
          onMouseEnter={show}
          style={{ pointerEvents: visible ? 'auto' : 'none' }}
          aria-label={t('accessibility.nextFile') || '下一个文件'}
          aria-keyshortcuts="ArrowRight"
          className="rfp-absolute rfp-z-20 rfp-right-2 md:rfp-right-4 rfp-top-1/2 -rfp-translate-y-1/2 rfp-w-10 rfp-h-10 md:rfp-w-12 md:rfp-h-12 rfp-rounded-full rfp-backdrop-blur-xl rfp-border rfp-flex rfp-items-center rfp-justify-center rfp-transition-colors rfp-shadow-2xl rfp-bg-surface-nav rfp-border-line hover:rfp-bg-surface-nav-hover rfp-text-fg-primary"
        >
          <ChevronRight className="rfp-w-5 rfp-h-5 md:rfp-w-6 md:rfp-h-6" />
        </motion.button>
      )}
    </>
  );
};
