// packages/vue-file-preview/src/renderers/Unsupported/index.vue
<script setup lang="ts">
import { FileQuestion, Download } from 'lucide-vue-next';
import { useTranslator } from '../../composables/useTranslator';

defineProps<{
  fileName: string;
  fileType: string;
}>();

const { t } = useTranslator();

const emit = defineEmits<{
  (e: 'download'): void;
}>();
</script>

<template>
  <div
    class="vfp-flex vfp-flex-col vfp-items-center vfp-justify-center vfp-w-full vfp-h-full vfp-p-6 vfp-gap-4"
  >
    <div
      class="vfp-w-20 vfp-h-20 vfp-rounded-full vfp-bg-surface-2 vfp-flex vfp-items-center vfp-justify-center"
    >
      <FileQuestion class="vfp-w-10 vfp-h-10 vfp-text-fg-secondary" />
    </div>

    <div class="vfp-text-fg-primary vfp-text-center">
      <p class="vfp-text-lg vfp-font-medium vfp-mb-2">{{ fileName }}</p>
      <p class="vfp-text-fg-secondary">{{ t('common.unsupported_preview', { type: fileType }) }}</p>
    </div>

    <button
      class="vfp-flex vfp-items-center vfp-gap-2 vfp-px-4 vfp-py-2 vfp-bg-surface-2 hover:vfp-bg-surface-3 vfp-backdrop-blur-sm vfp-rounded-lg vfp-text-fg-primary vfp-font-medium vfp-transition-all"
      @click="emit('download')"
    >
      <Download class="vfp-w-5 vfp-h-5" />
      {{ t('common.download') }}
    </button>
  </div>
</template>

// packages/react-file-preview/src/renderers/Unsupported/index.tsx
import { FileQuestion, Download } from 'lucide-react';
import { useTranslator } from '../../i18n/LocaleContext';

interface UnsupportedRendererProps {
  fileName: string;
  fileType: string;
  onDownload: () => void;
}

export const UnsupportedRenderer: React.FC<UnsupportedRendererProps> = ({
  fileName,
  fileType,
  onDownload,
}) => {
  const t = useTranslator();
  return (
    <div className="rfp-flex rfp-flex-col rfp-items-center rfp-justify-center rfp-w-full rfp-h-full rfp-p-6 rfp-gap-4">
      <div className="rfp-w-20 rfp-h-20 rfp-rounded-full rfp-bg-surface-2 rfp-flex rfp-items-center rfp-justify-center">
        <FileQuestion className="rfp-w-10 rfp-h-10 rfp-text-fg-secondary" />
      </div>

      <div className="rfp-text-fg-primary rfp-text-center">
        <p className="rfp-text-lg rfp-font-medium rfp-mb-2">{fileName}</p>
        <p className="rfp-text-fg-secondary">{t('common.unsupported_preview', { type: fileType })}</p>
      </div>

      <button
        onClick={onDownload}
        className="rfp-flex rfp-items-center rfp-gap-2 rfp-px-4 rfp-py-2 rfp-bg-surface-2 hover:rfp-bg-surface-3 rfp-backdrop-blur-sm rfp-rounded-lg rfp-text-fg-primary rfp-font-medium rfp-transition-all"
      >
        <Download className="rfp-w-5 rfp-h-5" />
        {t('common.download')}
      </button>
    </div>
  );
};
