// packages/react-file-preview/src/renderers/RendererLoading.tsx
import React from 'react';
import { useTranslator } from '../i18n/LocaleContext';

export const RendererLoading: React.FC = () => {
  const t = useTranslator();
  return (
    <div className="rfp-flex rfp-items-center rfp-justify-center rfp-w-full rfp-h-full rfp-text-fg-muted">
      <div className="rfp-flex rfp-flex-col rfp-items-center rfp-gap-3">
        <div className="rfp-w-8 rfp-h-8 rfp-rounded-full rfp-border-2 rfp-border-fg-muted rfp-border-t-transparent rfp-animate-spin" />
        <span className="rfp-text-sm">{t('common.loading') ?? 'Loading...'}</span>
      </div>
    </div>
  );
};

// packages/angular-file-preview/src/renderers/RendererLoading.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { LocaleService, getFallbackTranslator } from '../di/locale.service';

@Component({
  selector: 'afp-renderer-loading',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'afp-block afp-w-full afp-h-full' },
  template: `
    <div class="afp-flex afp-items-center afp-justify-center afp-w-full afp-h-full afp-text-fg-muted">
      <div class="afp-flex afp-flex-col afp-items-center afp-gap-3">
        <div class="afp-w-8 afp-h-8 afp-rounded-full afp-border-2 afp-border-fg-muted afp-border-t-transparent afp-animate-spin"></div>
        <span class="afp-text-sm">{{ t('common.loading') }}</span>
      </div>
    </div>
  `,
})
export class RendererLoading {
  private readonly locale = inject(LocaleService, { optional: true });
  protected readonly t = this.locale?.t() ?? getFallbackTranslator();
}
