// packages/react-file-preview/src/renderers/RendererError.tsx
import { AlertCircle } from 'lucide-react';

interface RendererErrorProps {
  message: string;
  detail?: string;
  showIcon?: boolean;
}

export const RendererError: React.FC<RendererErrorProps> = ({
  message,
  detail,
  showIcon = true,
}) => {
  return (
    <div className="rfp-flex rfp-items-center rfp-justify-center rfp-w-full rfp-h-full">
      <div className="rfp-text-center">
        {showIcon && (
          <div className="rfp-w-12 rfp-h-12 rfp-mx-auto rfp-mb-3 rfp-rounded-full rfp-bg-red-500/10 rfp-flex rfp-items-center rfp-justify-center">
            <AlertCircle className="rfp-w-6 rfp-h-6 rfp-text-red-400" />
          </div>
        )}
        <p className="rfp-text-base rfp-font-medium rfp-text-fg-primary rfp-mb-1">
          {message}
        </p>
        {detail && (
          <p className="rfp-text-xs rfp-text-fg-tertiary">{detail}</p>
        )}
      </div>
    </div>
  );
};

// packages/angular-file-preview/src/renderers/RendererError.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { AlertCircle } from 'lucide-angular';
import { LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'afp-renderer-error',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="afp-flex afp-items-center afp-justify-center afp-w-full afp-h-full">
      <div class="afp-text-center">
        @if (showIcon()) {
          <div class="afp-w-12 afp-h-12 afp-mx-auto afp-mb-3 afp-rounded-full afp-flex afp-items-center afp-justify-center"
               style="background: color-mix(in srgb, #ef4444 10%, transparent)">
            <i-lucide [img]="alertCircle" class="afp-w-6 afp-h-6" style="color: #f87171" />
          </div>
        }
        <p class="afp-text-base afp-font-medium afp-text-fg-primary afp-mb-1">{{ message() }}</p>
        @if (detail()) {
          <p class="afp-text-xs afp-text-fg-tertiary">{{ detail() }}</p>
        }
      </div>
    </div>
  `,
})
export class RendererError {
  message = input.required<string>();
  detail = input<string | undefined>(undefined);
  showIcon = input(true);
  protected readonly alertCircle = AlertCircle;
}
